Repository discordia-space/CEV-Eris, pull requests merged in 2018-09, with the labels that each got.

#1806 Chemsmoke runtime fix
  code/game/objects/effects/chem/chemsmoke.dm
  code/game/objects/effects/effect_system.dm
Labels: Minor, runtime error

#1805 Loyal Robotic Servants
  cev_eris.dme
  code/__defines/items_clothing.dm
  code/_helpers/icons.dm
  code/_helpers/unsorted.dm
  code/_onclick/click.dm
  code/_onclick/cyborg.dm
  code/_onclick/drag_drop.dm
  code/_onclick/item_attack.dm
  code/game/machinery/recharger.dm
  code/game/objects/items/devices/lighting/toggleable/flashlight.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/weapons/clown_items.dm
  code/game/objects/items/weapons/power_cells.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/girders.dm
  code/global.dm
  code/modules/client/preference_setup/general/06_flavor.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/silicon/robot/death.dm
  code/modules/mob/living/silicon/robot/drone/drone_items.dm
  code/modules/mob/living/silicon/robot/gripper.dm
  code/modules/mob/living/silicon/robot/inventory.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_items.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_movement.dm
  code/modules/power/apc.dm
  code/modules/projectiles/guns/Hatton.dm
  code/modules/reagents/Chemistry-Machinery.dm
  code/modules/reagents/reagent_containers/borghydro.dm
  code/modules/recycling/disposal.dm
  code/modules/research/destructive_analyzer.dm
  code/modules/tables/interactions.dm
  icons/mob/robots.dmi
  icons/obj/robot_items.dmi
Labels: Fix, High Risk, New features, Rebalance, Refactoring

#1820 Metal Table Fix
  code/modules/materials/materials.dm
  icons/turf/wall_masks.dmi
Labels: Fix

#1818 Attack Animation Fixes
  code/_onclick/item_attack.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/window.dm
  code/game/turfs/simulated/wall_attacks.dm
  code/modules/mob/animations.dm
Labels: Fix, enhancement

#1817 Minor Bleeding Rebalance
  code/__defines/mobs.dm
  code/modules/organs/blood.dm
Labels: Rebalance

#1824 Mining shuttle fix
  code/game/machinery/embedded_controller/airlock_controllers.dm
  code/game/machinery/embedded_controller/airlock_docking_controller.dm
  code/game/machinery/embedded_controller/airlock_docking_controller_multi.dm
  code/game/machinery/embedded_controller/docking_program.dm
  code/game/machinery/embedded_controller/embedded_program_base.dm
  code/modules/shuttles/landmarks.dm
Labels: Critical

#1812 New window spawner are now used.
  code/game/objects/structures/window.dm
  code/game/objects/structures/window_spawner.dm
  code/game/turfs/flooring/flooring_decals.dm
  icons/obj/structures.dmi
  maps/CEVEris/_CEV_Eris.dmm
  maps/CEVEris/backup/_CEV_Eris.dmm
  maps/CEVEris/centcomm.dmm
  maps/encounters/asteroid/asteroid.dmm
  maps/encounters/spacefortress/spacefortress.dmm
Labels: Map

#1816 Surgery Fixes 2
  code/game/objects/items.dm
  code/modules/surgery/implant.dm
  code/modules/surgery/surgery.dm
Labels: runtime error

#1814 Surgery Fixes 1
  code/game/machinery/OpTable.dm
  code/game/objects/items/weapons/autopsy.dm
  code/modules/surgery/generic.dm
  code/modules/surgery/organs_internal.dm
  code/modules/surgery/surgery.dm
Labels: Important

#1864 You can now store all stacks of ammo in your tactical belt.
  code/game/objects/items/weapons/storage/belt.dm
Labels: Rebalance

#1867 Spider Runtime Fix 2
  code/game/objects/effects/spiders.dm
Labels: runtime error

#1873 Hydroponics Fixes
  code/game/machinery/biogenerator.dm
  code/game/machinery/vending.dm
  code/game/objects/effects/decals/Cleanable/fuel.dm
  code/modules/hydroponics/trays/tray_reagents.dm
  nano/templates/biogenerator.tmpl
Labels: Fix, Important, Rebalance

#1880 Stairway Lighting Redesign
  code/modules/multiz/structures.dm
  icons/obj/stairs.dmi
  maps/CEVEris/_CEV_Eris.dmm
Labels: enhancement

#1876 Fix ban panel, fix bans check, fix admin flags
  .gitignore
  code/modules/admin/DB ban/functions.dm
  code/modules/admin/IsBanned.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/banjob.dm
  code/modules/admin/permissionverbs/permissionedit.dm
  code/modules/admin/topic.dm
  code/modules/admin/view_variables/view_variables.dm
Labels: Admin, Important, READY FOR REVIEW

#1852 VentcrawlGrav
  code/modules/mob/mob_movement.dm
Labels: Important

#1861 Hardsuit fix
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/mob/inventory.dm
Labels: Important

#1866 Robot Fixes and Falldamage Balancing
  code/_helpers/matrices.dm
  code/_onclick/hud/screen_objects/robot_screen_objects.dm
  code/datums/datum_hud.dm
  code/game/atoms.dm
  code/game/objects/items/robot/robot_items.dm
  code/modules/mob/animations.dm
  code/modules/mob/living/carbon/human/body_build.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/robot/drone/drone.dm
  code/modules/mob/living/silicon/robot/drone/drone_damage.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot_damage.dm
  code/modules/mob/living/silicon/robot/robot_hud.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_helpers.dm
  code/modules/multiz/structures.dm
  code/modules/multiz/turf.dm
Labels: Fix, READY FOR REVIEW, Rebalance, Refactoring

#1879 Ports the Paradise runtime handler
  cev_eris.dme
  code/ATMOSPHERICS/mainspipe.dm
  code/__defines/error_handler.dm
  code/_helpers/lists.dm
  code/_helpers/logging.dm
  code/_helpers/type2type.dm
  code/_macros.dm
  code/controllers/configuration.dm
  code/controllers/subsystems.dm
  code/datums/helper_datums/getrev.dm
  code/datums/mind.dm
  code/game/gamemodes/changeling/changeling_powers.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/computer/supply.dm
  code/game/machinery/telecomms/broadcaster.dm
  code/game/objects/explosion.dm
  code/global.dm
  code/modules/admin/DB ban/functions.dm
  code/modules/admin/IsBanned.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/debug.dm
  code/modules/admin/verbs/modifyvariables.dm
  code/modules/client/client procs.dm
  code/modules/error_handler/error_handler.dm
  code/modules/error_handler/error_viewer.dm
  code/modules/events/prison_break.dm
  code/modules/maps/swapmaps.dm
  code/modules/mob/angel/say.dm
  code/modules/mob/living/carbon/human/body_build.dm
  code/modules/mob/new_player/poll.dm
  code/modules/multiz/controller.dm
  code/modules/multiz/structures.dm
  code/modules/nano/nanomapgen.dm
  code/modules/power/power.dm
  code/world.dm
Labels: Minor

#1886 Mining barge map fixes
  icons/turf/shuttlemining.dmi
  maps/CEVEris/_CEV_Eris.dmm
  maps/encounters/asteroid/asteroid.dmm
  maps/encounters/spacefortress/spacefortress.dmm
Labels: Map, Minor

#1885 Doors now can be force opened faster.
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/blast_door.dm
  code/game/machinery/doors/firedoor.dm
Labels: Minor, Rebalance

#1808 Changeling abilities on mouse!
  cev_eris.dme
  code/_macros.dm
  code/_onclick/click.dm
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/datums/datum_click_handlers.dm
  code/game/gamemodes/changeling/changeling_powers.dm
  code/game/gamemodes/changeling/modularchangling.dm
  code/modules/client/client defines.dm
  code/modules/client/client procs.dm
  code/modules/mob/death.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/mob.dm
  icons/changeling_mouse_icons.dmi
Labels: High Risk, Testing required, enhancement

#1894 Small map fixes.
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map

#1891 Through the Looking Glass
  cev_eris.dme
  code/__defines/_planes+layers.dm
  code/__defines/tools_and_qualities.dm
  code/_helpers/mobs.dm
  code/_helpers/text.dm
  code/_helpers/turfs.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/weapons/material/twohanded.dm
  code/game/objects/structures.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/low_wall.dm
  code/game/objects/structures/window.dm
  code/game/objects/structures/window_spawner.dm
  code/game/turfs/simulated/wall_attacks.dm
  code/game/turfs/simulated/wall_icon.dm
  code/game/turfs/space/space.dm
  code/game/turfs/turf.dm
  code/modules/materials/material_recipes.dm
  code/modules/materials/materials.dm
  code/modules/mob/living/living_powers.dm
  code/modules/multiz/turf.dm
  code/modules/tables/interactions.dm
  code/modules/tables/tables.dm
  icons/obj/structures.dmi
  icons/obj/structures/low_wall.dmi
  icons/obj/structures/windows.dmi
Labels: High Risk, New features, Rebalance, Refactoring, Sprites, enhancement

#1912 Double Click Fix
  cev_eris.dme
  code/_onclick/click.dm
  code/_onclick/hud/screen_objects/robot_screen_objects.dm
  code/controllers/admin.dm
  code/modules/clothing/spacesuits/rig/modules/modules.dm
  code/modules/mob/living/silicon/subsystems.dm
Labels: Critical, High Risk

#1913 Drone fixes
  code/game/gamemodes/meteor/meteors.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/robot/drone/drone.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Critical, Fix

#1914 Welder Fix
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/tools/weldingtools.dm
  code/game/objects/items/weapons/tools/wirecutters.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/living/superior_animal/defense.dm
Labels: Important

#1917 Hallucination Tweaks
  code/game/sound.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/mob/living/carbon/human/life.dm
Labels: enhancement

#1944 Suit storage unit handling update
  code/game/machinery/suit_storage_unit.dm
Labels: Important, Minor, READY FOR REVIEW

#1918 Dawn of the Dead
  code/__defines/mobs.dm
  code/_helpers/time.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/client/preferences.dm
  code/modules/mob/death.dm
  code/modules/mob/living/silicon/robot/drone/drone_manufacturer.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_helpers.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/mob/observer/ghost/ghost.dm
Labels: READY FOR REVIEW, Refactoring, enhancement

#1945 And What of the Immortal Soul?
  code/modules/core_implant/cruciform/cruciform.dm
  code/modules/core_implant/cruciform/modules.dm
  code/modules/core_implant/cruciform/rituals/base.dm
  code/modules/core_implant/cruciform/rituals/group.dm
  code/modules/core_implant/cruciform/rituals/inquisitor.dm
  code/modules/core_implant/cruciform/rituals/priest.dm
  code/modules/core_implant/ritual.dm
  code/modules/core_implant/ritual_book.dm
Labels: Fix, enhancement

#1920 Day of the Dead
  code/__defines/mobs.dm
  code/_helpers/game.dm
  code/_helpers/type2type.dm
  code/game/atoms_movable.dm
  code/game/machinery/cryopod.dm
  code/game/objects/structures/crates_lockers/closets/coffin.dm
  code/game/objects/structures/morgue.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/client/preferences.dm
  code/modules/mob/death.dm
  code/modules/mob/living/silicon/robot/drone/drone_manufacturer.dm
  code/modules/mob/mob_helpers.dm
  code/modules/mob/observer/ghost/ghost.dm
  sound/effects/magic/Blind.ogg
Labels: New features, enhancement

#2005 Double damage gun fix
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Critical

#1951 Fuel and Water Tank sprites
  icons/obj/objects.dmi
Labels: Sprites, enhancement

#2003 Ranged weapons rebalancing
  code/modules/mob/mob_helpers.dm
  code/modules/organs/external/_external.dm
  code/modules/organs/external/damage.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/bullettypes.dm
Labels: Important, READY FOR REVIEW, Rebalance

#2046 General medical and science access united in one.
  code/game/jobs/access_datum.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/deployable.dm
  code/game/machinery/kitchen/smartfridge.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/cart.dm
  code/game/objects/items/weapons/policetape.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/cargo/packs.dm
  code/modules/mob/living/bot/medbot.dm
  code/modules/modular_computers/file_system/programs/_medical.dm
  code/modules/research/rdconsole.dm
  code/modules/research/xenoarchaeology/misc.dm
  code/modules/research/xenoarchaeology/tools/suspension_generator.dm
  code/modules/shuttles/departmental.dm
  maps/CEVEris/_CEV_Eris.dmm
  oldcode/shuttles_old/old_departmental.dm
Labels: Minor

#1952 Anesthetic machines
  cev_eris.dme
  code/_onclick/drag_drop.dm
  code/game/machinery/iv_drip.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/medical_stand.dm
  code/modules/cargo/exports/large_objects.dm
  code/modules/cargo/packs.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/organs/blood.dm
  code/modules/reagents/reagent_containers/glass.dm
  icons/PSD files/medical_stand.psd
  icons/obj/medical_stand.dmi
  maps/CEVEris/_CEV_Eris.dmm
  maps/CEVEris/centcomm.dmm
  sound/effects/internals.ogg
Labels: New features

#2043 Vendor and Misc Fixes
  code/game/machinery/vending.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/structures/low_wall.dm
  code/game/objects/structures/morgue.dm
Labels: READY FOR REVIEW

#2030 Earth Below Us
  code/__defines/damage_organs.dm
  code/__defines/turfs.dm
  code/_helpers/turfs.dm
  code/game/atoms.dm
  code/game/objects/items/weapons/tools/crowbars.dm
  code/game/objects/structures/catwalk.dm
  code/game/objects/structures/lattice.dm
  code/game/sound.dm
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/flooring/flooring_premade.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/floor_acts.dm
  code/game/turfs/simulated/floor_attackby.dm
  code/game/turfs/simulated/floor_damage.dm
  code/game/turfs/simulated/floor_icon.dm
  code/game/turfs/simulated/floor_types.dm
  code/game/turfs/simulated/walls.dm
  code/game/turfs/turf.dm
  code/game/turfs/turf_changing.dm
  code/modules/mining/mine_turfs.dm
  code/modules/multiz/turf.dm
  code/modules/multiz/turf_icon.dm
  icons/turf/flooring/grass.dmi
  icons/turf/flooring/plating.dmi
  icons/turf/un.dmi
  sound/effects/footstep/grass1.wav
  sound/effects/footstep/grass2.wav
  sound/effects/footstep/grass3.wav
  sound/effects/footstep/grass4.wav
  sound/effects/footstep/gravel1.wav
  sound/effects/footstep/gravel2.wav
  sound/effects/footstep/gravel3.wav
  sound/effects/footstep/gravel4.wav
  sound/effects/footstep/tile1.wav
  sound/effects/footstep/tile2.wav
  sound/effects/footstep/tile3.wav
  sound/effects/footstep/tile4.wav
Labels: Fix, High Risk, Important, New features, READY FOR REVIEW, Rebalance, Refactoring, Sounds, Sprites, enhancement
