Repository discordia-space/CEV-Eris, pull requests merged in 2018-04, with the labels that each got.

#1477 New sprites for tools and three new tool tiers.
  code/game/objects/items/weapons/tools/crowbars.dm
  code/game/objects/items/weapons/tools/scalpels.dm
  code/game/objects/items/weapons/tools/surgicaldrills.dm
  code/game/objects/random/surgerytools.dm
  code/game/objects/random/tools.dm
  code/modules/research/designs.dm
  icons/obj/tools.dmi
Labels: Sprites

#1476 Removing broken tags from cameras.
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map

#1484 Last of new tool sprites.
  icons/obj/tools.dmi
Labels: Sprites

#1487 New discs vendor.
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  icons/obj/vending.dmi
  maps/CEVEris/_CEV_Eris.dmm
  maps/encounters/spacefortress/spacefortress.dmm
Labels: New features, Sprites

#1488 Small map update, cameras and names on pumps.
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map

#1490 New sprite for 9mm magazine.
  icons/obj/ammo.dmi
Labels: Sprites

#1492 Random salvageable structures.
  cev_eris.dme
  code/game/objects/random/structures.dm
  code/game/objects/structures/salvageable.dm
  icons/misc/landmarks.dmi
  icons/obj/salvageable.dmi
  maps/CEVEris/_CEV_Eris.dmm
  maps/testmap/test_map.dmm
Labels: New features

#1497 4 stacks of plastic to RnD (destructor room)
  maps/CEVEris/_CEV_Eris.dmm
Labels: Fix, Map, Rebalance

#1502 Fixed some sprites and descriptions.
  code/game/objects/items/weapons/mine.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  icons/inventory/back/mob.dmi
  icons/inventory/back/mob_fat.dmi
  icons/inventory/back/mob_slim.dmi
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
  icons/obj/tools.dmi
Labels: Sprites

#1504 You cannot close or open blast door with your bare hands now.
  code/game/machinery/doors/blast_door.dm
Labels: Trivial

#1508 New NT sprites and new holoposter.
  code/game/machinery/holoposter.dm
  icons/obj/decals.dmi
  icons/obj/holoposter.dmi
  icons/obj/neotheology_machinery.dmi
  icons/obj/neotheology_pod.dmi
Labels: Sprites
