Repository discordia-space/CEV-Eris, pull requests merged in 2018-06, with the labels that each got.

#1521 Fix miniUI issue
  code/modules/mob/living/carbon/human/human_hud.dm
Labels: Fix, UI

#1529 New roach sprites.
  icons/mob/animal.dmi
Labels: Sprites

#1533 Fixing buildmode on open space. Close #291
  code/modules/admin/verbs/buildmode.dm
Labels: Fix, Trivial

#1536 Fixing some tools stats.
  code/datums/autolathe/tools.dm
  code/game/objects/items/weapons/tools/crowbars.dm
  code/game/objects/items/weapons/tools/misc.dm
  code/game/objects/items/weapons/tools/wrenches.dm
  code/game/objects/random/tools.dm
Labels: Trivial

#1542 Fixing a problems with access.
  code/game/jobs/job/science.dm
  maps/CEVEris/_CEV_Eris.dmm
Labels: Fix

#1590 Small fixes for map requested by players.
  maps/CEVEris/_CEV_Eris.dmm
  maps/encounters/asteroid/asteroid.dmm
Labels: Map, Trivial

#1591 Fixes some balance problems
  code/game/mecha/mech_fabricator.dm
  code/modules/clothing/glasses/hud.dm
Labels: Trivial

#1600 HUD fixes
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/game/objects/items/weapons/tanks/tanks.dm
  code/modules/mob/living/carbon/breathe.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human_hud.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/stripping.dm
  code/modules/mob/living/living_hud.dm
  code/modules/power/apc.dm
Labels: HUD

#1601 Return of gas roaches and less omnipresent spiderlings.
  code/game/objects/effects/spiders.dm
  code/game/objects/random/mob/roach.dm
Labels: Rebalance

#1606 New cigarettes sprites.
  icons/obj/cigarettes.dmi
Labels: Sprites
