Repository discordia-space/CEV-Eris, pull requests merged in 2018-08, with the labels that each got.

#1625 Some stat fixes.
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Dispenser.dm
Labels: Rebalance

#1626 More critical fails for tools.
  code/game/objects/items.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Dispenser.dm
  code/modules/surgery/surgery.dm
Labels: New features, Rebalance

#1627 Removing white pixel from spider butthole.
  icons/mob/animal.dmi
Labels: Fix, Minor, Sprites

#1628 New guns with sounds and ammo.
  cev_eris.dme
  code/datums/autolathe/ammo.dm
  code/datums/autolathe/guns.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/random/ammo.dm
  code/game/objects/random/guns.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/atreides.dm
  code/modules/projectiles/guns/projectile/automatic/dallas.dm
  code/modules/projectiles/guns/projectile/automatic/idaho.dm
  code/modules/projectiles/projectile/bullettypes.dm
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
  icons/obj/ammo.dmi
  icons/obj/gun.dmi
  sound/weapons/guns/fire/m41_shoot.ogg
  sound/weapons/guns/interact/m41_cocked.ogg
  sound/weapons/guns/interact/m41_reload.ogg
Labels: New features, Sprites

#1629 Fixing black carpet sprite.
  icons/turf/flooring/carpet.dmi
Labels: Fix, Sprites

#1639 Small fixes and improvements on map.
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map

#1646 Toxin healing wine for NeoTheology.
  code/game/machinery/vending.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/reagent_containers/food/drinks/bottle.dm
  code/modules/reagents/reagent_dispenser.dm
  icons/obj/drinks.dmi
  icons/obj/objects.dmi
  maps/CEVEris/_CEV_Eris.dmm
Labels: New features

#1669 New roach sprite.
  icons/mob/animal.dmi
Labels: Sprites

#1679 Cryocell Visual Fix
  code/game/machinery/cryo.dm
Labels: Fix, READY FOR REVIEW

#1678 Window Knocking
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/structures/window.dm
Labels: READY FOR REVIEW, enhancement

#1659 Grammar fixes
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/items/weapons/storage/lunchbox.dm
  code/game/objects/structures/railing.dm
  code/modules/clothing/suits/armor.dm
  code/modules/projectiles/ammunition/bullets.dm
  maps/CEVEris/_CEV_Eris.dmm
Labels: Fix

#1676 Infrastructure: Item slots and dropped proc
  code/__defines/items_clothing.dm
  code/_onclick/item_attack.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/melee/energy.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/objs.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/spacesuits/void/void.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/human/inventory.dm
Labels: READY FOR REVIEW, Refactoring

#1709 PDA GPS
  code/game/objects/items/devices/PDA/PDA.dm
  nano/templates/pda.tmpl
Labels: New features, READY FOR REVIEW, enhancement

#1652 Borers spawning fix
  code/game/antagonist/alien/borer.dm
  code/game/antagonist/antagonist_create.dm
  code/game/objects/landmarks/storyevent.dm
  maps/CEVEris/_CEV_Eris.dmm
Labels: DO NOT MERGE, Fix

#1715 Changed default lawset to old good Asimov
  code/datums/ai_laws.dm
Labels: Fix, READY FOR REVIEW, Trivial

#1718 Force Start Runtime
  code/controllers/voting.dm
Labels: Fix, runtime error

#1716 Floating Blood Fix
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/modules/multiz/turf.dm
Labels: Fix

#1719 Fix antagonist spawning.
  code/game/antagonist/alien/borer.dm
  code/game/antagonist/antagonist_helpers.dm
  code/game/objects/landmarks/storyevent.dm
Labels: Fix, READY FOR REVIEW

#1720 Dispenser Layer fix
  code/modules/reagents/Chemistry-Machinery.dm
Labels: Fix, Minor

#1708 Holders, Communication and Mice
  code/__defines/lighting.dm
  code/__defines/mobs.dm
  code/_helpers/game.dm
  code/_helpers/lists.dm
  code/_macros.dm
  code/game/atoms.dm
  code/game/objects/effects/decals/remains.dm
  code/modules/mob/death.dm
  code/modules/mob/emote.dm
  code/modules/mob/holder.dm
  code/modules/mob/living/carbon/alien/emote.dm
  code/modules/mob/living/carbon/brain/emote.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/metroid/emote.dm
  code/modules/mob/living/silicon/robot/emote.dm
  code/modules/mob/living/simple_animal/borer/borer.dm
  code/modules/mob/living/simple_animal/friendly/corgi.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
  icons/inventory/ears/mob.dmi
  icons/mob/held_mobs.dmi
  icons/mob/items/lefthand_holder.dmi
  icons/mob/items/righthand_holder.dmi
  icons/mob/mouse.dmi
  sound/effects/creatures/mouse_squeak_loud.ogg
  sound/effects/creatures/mouse_squeaks_1.ogg
  sound/effects/creatures/mouse_squeaks_2.ogg
  sound/effects/creatures/mouse_squeaks_3.ogg
  sound/effects/creatures/mouse_squeaks_4.ogg
  sound/effects/creatures/nibble1.ogg
  sound/effects/creatures/nibble2.ogg
Labels: Fix, New features, READY FOR REVIEW, Refactoring

#1728 Reagent container and dispenser fixes
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/Chemistry-Machinery.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_dispenser.dm
Labels: Fix

#1734 Small fixes on map, lobby for technomancers.
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map

#1736 New sprites for floors, mostly maint ones.
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/flooring/flooring_premade.dm
  code/game/turfs/simulated/floor_types.dm
  icons/turf/flooring/circuit.dmi
  icons/turf/floors.dmi
  icons/turf/un.dmi
Labels: New style, Sprites

#1732 Ore Satchel and Processing, Fixes and Improvements
  code/game/objects/items/weapons/storage/storage.dm
  code/modules/mining/machine_stacking.dm
  code/modules/mining/satchel_ore_boxdm.dm
Labels: Fix, enhancement

#1723 Wheelchair Mass
  code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm
Labels: Fix, Minor

#1671 Reducing the amount of material when disassembling the modular console
  code/modules/modular_computers/computers/machinery/modular_console.dm
Labels: Rebalance

#1737 Stats for jobs are now more higher.
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
Labels: Rebalance

#1738 New salvageable structures.
  code/game/objects/random/structures.dm
  code/game/objects/structures/salvageable.dm
  icons/obj/salvageable.dmi
Labels: Map, New features

#1739 Fixing letter "Я".
  code/controllers/voting.dm
  code/datums/ai_laws.dm
  code/datums/mind.dm
  code/game/machinery/computer/medical.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/nano/modules/law_manager.dm
  code/modules/paperwork/handlabeler.dm
Labels: Fix

#1756 Remove local guap files that he committed due to being too butterfingers to properly use git.
  .directory
  .vscode/tasks.json
Labels: DELET THIS, Shitcode

#1755 Fix bluespace harpoon accidentally fires when putting it on table/backpack, close #1697
  code/game/objects/items/weapons/space_harpoon.dm
Labels: Fix

#1778 Fixing some map problems, such as missing wires and shuttles.
  maps/CEVEris/_CEV_Eris.dmm
  maps/CEVEris/centcomm.dmm
Labels: Map

#1782 Maintshroom now have better name and independent spawner.
  cev_eris.dme
  code/game/objects/random/flora.dm
  code/game/objects/random/mob/roach.dm
  code/game/objects/random/mob/spider.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/seed_packets.dm
  icons/misc/landmarks.dmi
  icons/obj/hydroponics_growing.dmi
  icons/obj/hydroponics_vines.dmi
  maps/CEVEris/_CEV_Eris.dmm
Labels: Minor

#1781 Autolathe Fixes and Tweaks
  code/datums/autolathe/autolathe_datums.dm
  code/game/atoms.dm
  code/game/machinery/autolathe.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/modules/power/cell.dm
  code/modules/research/protolathe.dm
Labels: Fix, Minor

#1783 Ventcrawling 2.0
  cev_eris.dme
  code/ATMOSPHERICS/atmospherics.dm
  code/ATMOSPHERICS/components/binary_devices/binary_atmos_base.dm
  code/ATMOSPHERICS/components/binary_devices/pipeturbine.dm
  code/ATMOSPHERICS/components/trinary_devices/trinary_base.dm
  code/ATMOSPHERICS/components/tvalve.dm
  code/ATMOSPHERICS/components/unary/cold_sink.dm
  code/ATMOSPHERICS/components/unary/generator_input.dm
  code/ATMOSPHERICS/components/unary/heat_exchanger.dm
  code/ATMOSPHERICS/components/unary/heat_source.dm
  code/ATMOSPHERICS/components/unary/outlet_injector.dm
  code/ATMOSPHERICS/components/unary/oxygen_generator.dm
  code/ATMOSPHERICS/components/unary/unary_base.dm
  code/ATMOSPHERICS/components/unary/vent_pump.dm
  code/ATMOSPHERICS/components/unary/vent_scrubber.dm
  code/ATMOSPHERICS/components/valve.dm
  code/ATMOSPHERICS/pipes.dm
  code/game/machinery/cryo.dm
  code/game/machinery/pipe/construction.dm
  code/game/modules/ventcrawl/ventcrawl.dm
  code/game/modules/ventcrawl/ventcrawl_atmospherics.dm
  code/game/modules/ventcrawl/ventcrawl_multiz.dm
  code/game/modules/ventcrawl/ventcrawl_verb.dm
  code/game/objects/items/weapons/circuitboards/machinery/unary_atmos.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_powers.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/multiz/movement.dm
  code/modules/multiz/pipes.dm
  code/modules/multiz/structures.dm
  icons/atmos/vent_scrubber.dmi
  sound/machines/ventcrawl.ogg
Labels: New features, Refactoring, enhancement

#1785 Changeling Fixes
  code/game/modules/ventcrawl/ventcrawl.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species/station/monkey.dm
  code/modules/mob/transform_procs.dm
  icons/mob/mob.dmi
Labels: DO NOT MERGE, Fix, Important

#1780 Bluespace Technicians
  cev_eris.dme
  code/_macros.dm
  code/game/turfs/simulated/floor_types.dm
  code/modules/admin/bluespacetech.dm
  code/modules/multiz/movement.dm
Labels: Admin, Important, debug

#1789 Small fix for damage system
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Fix

#1790 New sprites for asteroid.
  code/modules/mining/mine_turfs.dm
  icons/obj/mining.dmi
  icons/obj/xenoarchaeology.dmi
  icons/turf/flooring/asteroid.dmi
  icons/turf/flooring/decals.dmi
  icons/turf/walls.dmi
Labels: Sprites

#1801 Archive old shuttle code
  oldcode/computer/old_shuttle.dm
  oldcode/old_emergency_shuttle_controller.dm
  oldcode/old_shuttle_controller.dm
  oldcode/shuttles_old/old_antagonist.dm
  oldcode/shuttles_old/old_departmental.dm
  oldcode/shuttles_old/old_escape_pods.dm
  oldcode/shuttles_old/old_shuttle.dm
  oldcode/shuttles_old/old_shuttle_console.dm
  oldcode/shuttles_old/old_shuttle_ferry.dm
  oldcode/shuttles_old/old_shuttle_supply.dm
  oldcode/shuttles_old/old_shuttles_multi.dm
Labels: Minor

#1807 New mining scanner sprite.
  code/modules/mining/drilling/scanner.dm
  icons/obj/device.dmi
Labels: Sprites
