Repository discordia-space/CEV-Eris, pull requests merged in 2018-07, with the labels that each got.

#1609 Fixing bug with tool operation that does not require stats.
  code/game/objects/items.dm
Labels: Сritical!

#1612 Smes units now can store and output more.
  code/modules/power/smes_construction.dm
Labels: Rebalance, Trivial

#1614 Borgs' instantcuffs fix (closes #1582)
  code/game/objects/items/weapons/handcuffs.dm
Labels: Fix, READY FOR REVIEW

#1608 advanced trauma and burn kits fix
  code/game/objects/items/stacks/medical.dm
Labels: Fix, READY FOR REVIEW, Trivial

#1621 Sprite update initial
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/flooring/flooring_premade.dm
  code/modules/holodeck/HolodeckObjects.dm
  icons/turf/catwalks.dmi
  icons/turf/flooring/carpet.dmi
  icons/turf/flooring/dirt.dmi
  icons/turf/flooring/grass.dmi
  icons/turf/flooring/hull.dmi
  icons/turf/flooring/linoleum.dmi
  icons/turf/flooring/wood.dmi
  maps/CEVEris/_CEV_Eris.dmm
  maps/CEVEris/centcomm.dmm
Labels: New style, Sprites
