Repository discordia-space/CEV-Eris, pull requests merged in 2018-10, with the labels that each got.

#1819 Select Equipment Fix
  code/modules/admin/verbs/debug.dm
Labels: Fix, Minor, READY FOR REVIEW

#2121 Ports baystation12 multi z alarm fixes
  code/_helpers/game.dm
  code/_macros.dm
  code/game/machinery/alarm.dm
  code/game/machinery/computer/atmos_alert.dm
  code/game/machinery/computer/station_alert.dm
  code/modules/alarm/alarm.dm
  code/modules/alarm/alarm_handler.dm
  code/modules/alarm/atmosphere_alarm.dm
  code/modules/nano/modules/alarm_monitor.dm
  code/modules/nano/modules/nano_module.dm
Labels: READY FOR REVIEW

#2097 Drying Rack rework
  code/game/machinery/kitchen/smartfridge.dm
  code/modules/hydroponics/grown.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/obj/vending.dmi
Labels: Refactoring, Sprites

#2146 Pickweight for Obj/Randoms
  code/_helpers/lists.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/random/ammo.dm
  code/game/objects/random/booze.dm
  code/game/objects/random/boxes.dm
  code/game/objects/random/circuitboards.dm
  code/game/objects/random/closet.dm
  code/game/objects/random/contraband.dm
  code/game/objects/random/food.dm
  code/game/objects/random/guns.dm
  code/game/objects/random/junk.dm
  code/game/objects/random/materials.dm
  code/game/objects/random/medicine.dm
  code/game/objects/random/mob/roach.dm
  code/game/objects/random/mob/spider.dm
  code/game/objects/random/powercells.dm
  code/game/objects/random/purerandom.dm
  code/game/objects/random/random.dm
  code/game/objects/random/structures.dm
  code/game/objects/random/tanks.dm
  code/game/objects/random/techparts.dm
  code/game/objects/random/tools.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/materials/material_sheets.dm
Labels: READY FOR REVIEW

#2192 Random Runtime Fix
  code/_helpers/lists.dm
Labels: READY FOR REVIEW

#2176 Inventory equip
  cev_eris.dme
  code/__defines/items_clothing.dm
  code/datums/uplink/uplink_items.dm
  code/game/jobs/job/job.dm
  code/game/objects/items.dm
  code/game/objects/items/_inventory.dm
  code/game/objects/items/weapons/handcuffs.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/game/objects/items/weapons/storage/internal.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/structures/medical_stand.dm
  code/game/sound.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/suits/storage.dm
  code/modules/mob/holder.dm
  code/modules/mob/inventory.dm
  code/modules/mob/inventory/_docs.dm
  code/modules/mob/inventory/equip.dm
  code/modules/mob/inventory/helpers.dm
  code/modules/mob/inventory/slots.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/species/xenomorphs/alien_facehugger.dm
  code/modules/mob/living/carbon/human/stripping.dm
Labels: High Risk

#2172 Rig Cutting
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/spacesuits/rig/rig_attackby.dm
  nano/templates/hardsuit.tmpl
Labels: READY FOR REVIEW

#2191 An Ardent Orison
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/tools/weldingtools.dm
  code/game/objects/random/tools.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/tools.dmi
Labels: READY FOR REVIEW

#2124 Crafting v1.1
  code/__defines/craft.dm
  code/datums/craft/item.dm
  code/datums/craft/recipe.dm
  code/datums/craft/recipes/airlocks.dm
  code/datums/craft/recipes/clothing.dm
  code/datums/craft/recipes/floor.dm
  code/datums/craft/recipes/furniture.dm
  code/datums/craft/recipes/machinery.dm
  code/datums/craft/recipes/misc.dm
  code/datums/craft/recipes/weapon.dm
  code/datums/craft/step.dm
  code/game/objects/items.dm
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/simulated/floor_attackby.dm
  code/modules/materials/materials.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/multiz/turf.dm
Labels: READY FOR REVIEW

#2187 Removing datum pooling.
  cev_eris.dme
  code/_helpers/datum_pool.dm
  code/_onclick/telekinesis.dm
  code/datums/extensions/extensions.dm
  code/datums/mob_stats.dm
  code/game/gamemodes/events/wormholes.dm
  code/game/machinery/bots/bots.dm
  code/game/machinery/bots/mulebot.dm
  code/game/machinery/constructable_frame.dm
  code/game/machinery/deployable.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/machinery.dm
  code/game/machinery/portable_turret.dm
  code/game/machinery/vending.dm
  code/game/mecha/equipment/tools/ai_holder.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/objects/effects/chem/chemsmoke.dm
  code/game/objects/effects/chem/foam.dm
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/effects/effect_system.dm
  code/game/objects/effects/gibs.dm
  code/game/objects/effects/mines.dm
  code/game/objects/effects/spiders.dm
  code/game/objects/empulse.dm
  code/game/objects/items/devices/chameleonproj.dm
  code/game/objects/items/weapons/extinguisher.dm
  code/game/objects/items/weapons/grenades/smokebomb.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/lattice.dm
  code/game/objects/structures/watercloset.dm
  code/game/objects/structures/windoor_assembly.dm
  code/game/objects/structures/window.dm
  code/game/objects/structures/window_spawner.dm
  code/game/turfs/initialization/maintenance.dm
  code/game/turfs/turf_flick_animations.dm
  code/modules/core_implant/group_ritual.dm
  code/modules/economy/ATM.dm
  code/modules/economy/Accounts.dm
  code/modules/economy/Accounts_DB.dm
  code/modules/economy/EFTPOS.dm
  code/modules/economy/economy_misc.dm
  code/modules/events/money_hacker.dm
  code/modules/events/money_lotto.dm
  code/modules/events/payday.dm
  code/modules/lighting/lighting_system.dm
  code/modules/lighting/lighting_turf.dm
  code/modules/mob/living/bot/floorbot.dm
  code/modules/mob/living/silicon/robot/drone/drone_manufacturer.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/drone.dm
  code/modules/mob/living/superior_animal/giant_spider/giant_spider.dm
  code/modules/mob/mob.dm
  code/modules/mob/observer/freelook/ai/eye.dm
  code/modules/multiz/shadow.dm
  code/modules/paperwork/papershredder.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
  code/modules/tables/flipping.dm
  code/modules/vehicles/vehicle.dm
Labels: High Risk, READY FOR REVIEW

#2227 Drinking it all up mechanic.
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/reagents/reagent_containers/food/drinks/bottle.dm
Labels: Minor, New features

#2230 Loadout Tweaks
  code/modules/client/preference_setup/loadout/loadout_general.dm
  code/modules/client/preference_setup/loadout/loadout_mask.dm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/client/preference_setup/loadout/loadout_utility.dm
Labels: Rebalance

#2229 Ten Feet Higher
  cev_eris.dme
  code/__defines/misc.dm
  code/__defines/weapons.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/showcase.dm
  code/game/machinery/doors/simple.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/extinguisher.dm
  code/game/objects/items/weapons/material/bats.dm
  code/game/objects/items/weapons/material/kitchen.dm
  code/game/objects/items/weapons/material/knives.dm
  code/game/objects/items/weapons/material/swords.dm
  code/game/objects/items/weapons/material/twohanded.dm
  code/game/objects/items/weapons/melee/energy.dm
  code/game/objects/items/weapons/melee/misc.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/items/weapons/swords_axes_etc.dm
  code/game/objects/items/weapons/tools/pickaxe.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/window.dm
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/simulated/floor_attackby.dm
  code/game/turfs/simulated/wall_attacks.dm
Labels: High Risk, READY FOR REVIEW, Rebalance, Refactoring

#2257 Spider/roach refactoring part 1
  cev_eris.dme
  code/_helpers/lists.dm
  code/game/objects/effects/spiders.dm
  code/modules/mob/living/superior_animal/ai.dm
  code/modules/mob/living/superior_animal/giant_spider/ai.dm
  code/modules/mob/living/superior_animal/giant_spider/giant_spider.dm
  code/modules/mob/living/superior_animal/giant_spider/life.dm
  code/modules/mob/living/superior_animal/giant_spider/types/hunter.dm
  code/modules/mob/living/superior_animal/giant_spider/types/nurse.dm
  code/modules/mob/living/superior_animal/roach/ai.dm
  code/modules/mob/living/superior_animal/roach/blattedin.dm
  code/modules/mob/living/superior_animal/roach/life.dm
  code/modules/mob/living/superior_animal/roach/roach.dm
  code/modules/mob/living/superior_animal/roach/types/support.dm
  code/modules/mob/living/superior_animal/superior_animal.dm
Labels: Bug fixes, READY FOR REVIEW, Rebalance, Refactoring

#2236 Altered Carbon
  code/modules/core_implant/cruciform/rituals/priest.dm
Labels: Rebalance

#2261 Fixes splashes calling touch procs incorrectly
  code/modules/reagents/Chemistry-Holder.dm
Labels: Bug fixes, READY FOR REVIEW, baymed

#2249 Repeating Tool Sounds
  code/_helpers/maths.dm
  code/game/objects/items.dm
  code/game/sound.dm
Labels: READY FOR REVIEW, enhancement

#2262 Adds a new proc to objects - is_hot()
  code/__defines/mobs.dm
  code/_onclick/item_attack.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/lighting/flare.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/melee/energy.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/tools/weldingtools.dm
  code/game/objects/objs.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/overmap/ships/computers/sensors.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/energy.dm
Labels: New features, READY FOR REVIEW, Refactoring
