Repository discordia-space/CEV-Eris, pull requests merged in 2018-03, with the labels that each got.

#1456 New fuel canister.
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/weldbackpack.dm
  code/game/objects/random/tools.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/modules/mining/mine_items.dm
  icons/obj/storage.dmi
Labels: New features

#1461 Attackby and tool fixes.
  code/__defines/tools_and_qualities.dm
  code/datums/wires/wires.dm
  code/game/machinery/atmoalter/canister.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/material/kitchen.dm
  code/game/objects/items/weapons/material/knives.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/items/weapons/tools/multitool.dm
  code/game/objects/items/weapons/tools/saws.dm
  code/game/turfs/simulated/wall_attacks.dm
  code/modules/client/preference_setup/loadout/loadout_general.dm
  code/modules/materials/material_recipes.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/power/apc.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
  icons/obj/tools.dmi
  maps/CEVEris/centcomm.dmm
Labels: Fix

#1462 New shuttle landmarks sprites
  code/modules/shuttles/landmarks.dm
  icons/misc/landmarks.dmi
  maps/CEVEris/shuttles-eris.dm
  maps/encounters/asteroid/asteroid.dm
  maps/encounters/spacefortress/spacefortress.dm
Labels: Sprites

#1464 Fix space icon resetting (overmap movement)
  code/modules/overmap/_defines.dm
Labels: Fix

#1469 Fix self-charging gun reload message, close #1410
  code/modules/projectiles/guns/energy.dm
Labels: Fix, Trivial

#1471 Removing old and useless maps.
  maps/exodus/backup/test_map.dmm
  maps/exodus/exodus-1.dmm
  maps/exodus/exodus-2.dmm
  maps/exodus/exodus-3.dmm
  maps/exodus/exodus-4.dmm
  maps/exodus/exodus-5.dmm
  maps/exodus/exodus-6.dmm
  maps/overmap/bearcat/bearcat.dm
  maps/overmap/bearcat/bearcat.dmi
  maps/overmap/bearcat/bearcat.dmm
  maps/overmap/example_sector1.dmm
  maps/overmap/example_sector2.dmm
  maps/overmap/examples.dm
  maps/testmap/test_map.dmm
Labels: DELET THIS, Map
