Repository discordia-space/CEV-Eris, pull requests merged in 2018-11, with the labels that each got.

#2283 Fixes overmap generating events inside occupied tiles
  code/controllers/subsystems/mapping.dm
Labels: Bug fixes, READY FOR REVIEW

#2284 Removes movement cooldown on click actions
  code/_onclick/click.dm
  code/_onclick/telekinesis.dm
  code/modules/projectiles/gun.dm
Labels: READY FOR REVIEW, Rebalance

#2287 Another Brick in the Wall
  code/game/turfs/simulated/wall_icon.dm
  code/game/turfs/simulated/wall_types.dm
  code/game/turfs/simulated/walls.dm
Labels: READY FOR REVIEW

#2280 Maintshroom Runtime Fix
  code/modules/hydroponics/spreading/spreading_growth.dm
Labels: READY FOR REVIEW

#2272 Multi z drawing rework
  code/_onclick/hud/plane_master.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/multiz/shadow.dm
  code/modules/multiz/turf_icon.dm
  code/modules/overmap/_defines.dm
Labels: Bug fixes, READY FOR REVIEW, Refactoring

#2278 Chem smoke now calls touch_mob on mobs
  code/game/objects/effects/chem/chemsmoke.dm
Labels: READY FOR REVIEW, Rebalance

#2285 Fixes overmap events not initializing
  code/modules/overmap/events/event.dm
Labels: Bug fixes, READY FOR REVIEW

#2288 Fixes engineering jumpsuit description
  code/modules/clothing/under/jobs/engineering.dm
Labels: Bug fixes, READY FOR REVIEW

#2289 Fixes occupation preferences buttons
  code/modules/client/preference_setup/occupation/occupation.dm
Labels: Bug fixes, READY FOR REVIEW

#2286 Fixes stacking machine producing 0 stacks
  code/modules/mining/machine_stacking.dm
Labels: Bug fixes, READY FOR REVIEW, Refactoring

#2299 Fixes redundancy during QDELETED checks
  code/_helpers/text.dm
  code/game/gamemodes/events/blob.dm
  code/game/machinery/cryopod.dm
  code/game/objects/structures/crates_lockers/closets/coffin.dm
  code/game/objects/structures/cyberplants.dm
  code/modules/mob/animations.dm
  code/modules/surgery/implant.dm
Labels: Bug fixes, READY FOR REVIEW

#2295 Fixes firedoors closing when unpowered
  code/game/machinery/doors/firedoor.dm
Labels: READY FOR REVIEW

#2297 Puts an upper cap on fire_stacks burn temperature
  code/modules/mob/living/living_defense.dm
Labels: READY FOR REVIEW, Rebalance

#2277 Storage HUD rework
  cev_eris.dme
  code/_onclick/hud/HUD_element/HUD_element.dm
  code/_onclick/hud/HUD_element/client.dm
  code/_onclick/hud/HUD_element/external_procs.dm
  code/_onclick/hud/HUD_element/internal_procs.dm
  code/_onclick/hud/HUD_element/types/threePartBox.dm
  code/datums/datum_hud.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/storage/internal.dm
  code/game/objects/items/weapons/storage/secure.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/modules/mob/living/bot/floorbot.dm
  icons/HUD/block.png
  icons/HUD/storage_end.png
  icons/HUD/storage_middle.png
  icons/HUD/storage_start.png
  icons/HUD/stored_end.png
  icons/HUD/stored_middle.png
  icons/HUD/stored_start.png
  icons/HUD/x.png
Labels: Bug fixes, HUD, READY FOR REVIEW, Refactoring

#2304 Fixed silicons unable to use emails
  code/__defines/jobs.dm
  code/controllers/subsystems/jobs.dm
  code/datums/mind.dm
  code/game/antagonist/station/changeling.dm
  code/game/antagonist/station/secdocs_stealers.dm
  code/game/gamemodes/storyteller_helpers.dm
  code/game/jobs/job/silicon.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/landmarks/join.dm
  code/modules/admin/player_panel.dm
  code/modules/ghosttrap/trap.dm
  code/modules/mob/hear_say.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/pai/software_modules.dm
  code/modules/mob/living/silicon/robot/drone/drone.dm
  code/modules/mob/living/silicon/robot/drone/drone_manufacturer.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_parts.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/silicon/subsystems.dm
  code/modules/mob/living/simple_animal/friendly/spiderbot.dm
  code/modules/mob/mob.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/mob/transform_procs.dm
  code/modules/modular_computers/NTNet/NTNet.dm
  code/modules/modular_computers/file_system/programs/generic/email_client.dm
  nano/templates/email_client.tmpl
Labels: Critical, READY FOR REVIEW

#2300 Minimal interface for tax program
  code/game/antagonist/antagonist_equip.dm
  code/game/objects/items/devices/uplink.dm
  code/modules/modular_computers/file_system/programs/antagonist/uplink.dm
  nano/templates/taxquickly.tmpl
Labels: READY FOR REVIEW

#2268 Space Suit and pouch Tweaks
  cev_eris.dme
  code/_helpers/global_lists.dm
  code/game/objects/items/_inventory.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/items/weapons/tools/crowbars.dm
  code/game/objects/random/junk.dm
  code/game/objects/random/pouches.dm
  code/game/objects/random/rare.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/captain.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/spacesuits/rig/modules/computer.dm
  code/modules/clothing/spacesuits/rig/modules/modules.dm
  code/modules/clothing/spacesuits/rig/modules/utility.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/spacesuits/rig/rig_attackby.dm
  code/modules/clothing/spacesuits/rig/rig_modules.dm
  code/modules/clothing/spacesuits/rig/rig_pieces.dm
  code/modules/clothing/spacesuits/rig/suits/combat.dm
  code/modules/clothing/spacesuits/rig/suits/light.dm
  code/modules/clothing/spacesuits/rig/suits/merc.dm
  code/modules/clothing/spacesuits/rig/suits/station.dm
  code/modules/clothing/spacesuits/spacesuits.dm
  code/modules/clothing/spacesuits/syndi.dm
  code/modules/clothing/spacesuits/void/merc.dm
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/clothing/spacesuits/void/void.dm
  icons/inventory/pockets/icon.dmi
  nano/templates/hardsuit.tmpl
Labels: New features, READY FOR REVIEW, Rebalance, Refactoring

#2296 Tiger Tiger, Burning Bright
  code/ZAS/Fire.dm
  code/game/objects/effects/decals/Cleanable/fuel.dm
  code/game/objects/items/weapons/flamethrower.dm
Labels: READY FOR REVIEW

#2306 Fixes some anomalies with multi z drawing
  code/game/turfs/turf_changing.dm
  code/modules/multiz/turf_icon.dm
Labels: Bug fixes, READY FOR REVIEW

#2334 Plant Nerfing
  code/game/gamemodes/events/spacevine.dm
  code/modules/hydroponics/spreading/spreading.dm
  code/modules/hydroponics/spreading/spreading_growth.dm
  code/modules/hydroponics/spreading/spreading_response.dm
Labels: READY FOR REVIEW

#2223 Job Slots Expansion
  code/game/jobs/job/cargo.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
Labels: Discussion needed, READY FOR REVIEW, Rebalance

#2354 Fixes numerous mapping errors
  maps/CEVEris/_CEV_Eris.dmm
Labels: Bug fixes, Map, READY FOR REVIEW

#2358 Fixes catwalks not updating "fallability"
  code/game/objects/structures/catwalk.dm
Labels: Bug fixes, READY FOR REVIEW

#2359 Fixes missing close button for slot storage
  code/game/objects/items/weapons/storage/storage.dm
Labels: Bug fixes, READY FOR REVIEW

#2356 Prevents plants from blocking clicks
  code/modules/hydroponics/spreading/spreading.dm
Labels: READY FOR REVIEW

#2322 Computers light
  code/_global_vars/misc.dm
  code/_helpers/icons.dm
  code/modules/modular_computers/computers/modular_computer/core.dm
  code/modules/modular_computers/computers/modular_computer/variables.dm
  code/modules/modular_computers/computers/subtypes/dev_console.dm
  code/modules/modular_computers/computers/subtypes/dev_laptop.dm
  code/modules/modular_computers/computers/subtypes/dev_pda.dm
  code/modules/modular_computers/computers/subtypes/dev_tablet.dm
  code/modules/modular_computers/computers/subtypes/dev_telescreen.dm
  code/modules/modular_computers/hardware/led.dm
Labels: READY FOR REVIEW

#2365 Fixes runtime in nurse.dm
  code/modules/mob/living/carbon/superior_animal/defense.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Labels: Bug fixes, READY FOR REVIEW

#2364 Fixes faulty projectile penetration
  code/game/gamemodes/events/blob.dm
  code/modules/projectiles/projectile.dm
Labels: Bug fixes, READY FOR REVIEW

#2378 Fixes storage numbered display
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/items/weapons/storage/storage.dm
Labels: Bug fixes, READY FOR REVIEW

#2379 Floor Icons 2: The Return
  code/__defines/turfs.dm
  code/_helpers/turfs.dm
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/simulated/floor_icon.dm
  code/modules/mining/mine_turfs.dm
  icons/turf/flooring/grass.dmi
  icons/turf/flooring/plating.dmi
Labels: READY FOR REVIEW

#2374 Marshal Fixes and Storyteller Reporting
  cev_eris.dme
  code/datums/objective/assassinate_marshal.dm
  code/game/antagonist/antagonist_helpers.dm
  code/game/antagonist/station/changeling.dm
  code/game/antagonist/station/inquisitor.dm
  code/game/antagonist/station/marshal.dm
  code/game/antagonist/station/traitor.dm
  code/game/gamemodes/roleset/roleset.dm
  code/game/gamemodes/roleset/simple.dm
  code/game/gamemodes/storyevent.dm
  code/game/gamemodes/storyteller.dm
  code/game/gamemodes/storyteller_print.dm
Labels: READY FOR REVIEW

#2382 Serbian language for future antag use and some language tweaks.
  code/__defines/species_languages.dm
  code/game/jobs/job/assistant.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/cargo.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/civilian_chaplain.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/modules/mob/language/outsider.dm
  code/modules/mob/language/station.dm
  code/stylesheet.dm
Labels: Antags

#2381 Sand from the Beach
  cev_eris.dme
  code/datums/autolathe/parts.dm
  code/datums/craft/recipe.dm
  code/datums/craft/recipes/tools.dm
  code/datums/uplink/stealth and camouflage items.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/tools/crowbars.dm
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/game/objects/items/weapons/tools/pickaxe.dm
  code/game/objects/items/weapons/tools/saws.dm
  code/game/objects/items/weapons/tools/scalpels.dm
  code/game/objects/items/weapons/tools/screwdrivers.dm
  code/game/objects/items/weapons/tools/shovel.dm
  code/game/objects/items/weapons/tools/tape.dm
  code/game/objects/items/weapons/tools/weldingtools.dm
  code/game/objects/items/weapons/tools/wirecutters.dm
  code/game/objects/items/weapons/tools/wrenches.dm
  code/game/objects/random/purerandom.dm
  code/game/objects/random/rare.dm
  code/game/objects/random/tools.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/modules/mining/mine_items.dm
  icons/obj/tool_upgrades.dmi
  nano/css/shared.css
  nano/templates/craft.tmpl
Labels: READY FOR REVIEW
