Repository discordia-space/CEV-Eris, pull requests merged in 2019-09, with the labels that each got.

#3754 Fixes for sprite shadows.
  icons/obj/monitors.dmi
  icons/obj/radio.dmi
  icons/obj/terminals.dmi
Labels: Fix, Sprites

#3792 fixes nutrition and some other stuff
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/modular_computers/file_system/programs/medical/chem_catalog.dm
  code/modules/nano/modules/catalog_all_entries.dm
  code/modules/reagents/reagents.dm
  code/modules/reagents/reagents/core.dm
  code/modules/reagents/reagents/dispenser.dm
  code/modules/reagents/reagents/food-Drinks.dm
Labels: Critical

#3783 NT Bioprinter and biomatter designs for this
  cev_eris.dme
  code/datums/autolathe/biomatter.dm
  code/game/machinery/autolathe.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/items/weapons/circuitboards/machinery/neotheology.dm
  code/modules/biomatter_manipulation/biogenerator.dm
  code/modules/biomatter_manipulation/bioreactor/biotank.dm
  code/modules/biomatter_manipulation/bioreactor/console.dm
  code/modules/biomatter_manipulation/bioreactor/loader.dm
  code/modules/biomatter_manipulation/bioreactor/platform.dm
  code/modules/biomatter_manipulation/bioreactor/port.dm
  code/modules/biomatter_manipulation/bioreactor/unloader.dm
Labels: READY FOR REVIEW

#3784 Making PR template more fancy
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Discussion needed

#3793 [FIX] Closets will check ID then cruciform now
  code/game/machinery/walllockers.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/personal/_personal.dm
Labels: Bug fixes, Fix

#3797 [Balance] Possible fix for damage reduction when wearing anything
  code/modules/biomatter_manipulation/bioreactor/biotank.dm
  code/modules/biomatter_manipulation/toxic_biomass.dm
Labels: Fix, Rebalance

#3816 Oddities
  cev_eris.dme
  code/game/objects/items/oddities.dm
  code/game/objects/random/oddities.dm
  code/game/objects/random/packs.dm
  code/modules/scrap/scrap.dm
  icons/misc/landmarks.dmi
  icons/obj/oddities.dmi
Labels: READY FOR REVIEW

#3820 [FIX] Bear trap should prevent the Harpoon from working while armed.
  code/game/objects/items/weapons/traps.dm
Labels: READY FOR REVIEW

#3819 Assorted map fixes.
  maps/CEVEris/_CEV_Eris.dmm
Labels: Fix, Map
