Repository discordia-space/CEV-Eris, pull requests merged in 2019-06, with the labels that each got.

#3582 NanoUI airlock electronics
  code/game/machinery/doors/airlock_electronics.dm
  code/game/objects/objs.dm
  code/modules/nano/interaction/hands.dm
  nano/templates/airlock_electronics.tmpl
Labels: NanoUI, Porting, Porting/Bay12

#3609 [FIX] Embed items will eject now from gibbed roaches
  code/modules/mob/living/carbon/superior_animal/defense.dm
  html/changelogs/TorinoFermic-gibfixitems.yml
Labels: Bug fixes, Mobs, READY FOR REVIEW

#3590 Crew sensors improve and some organ refactor
  code/__defines/damage_organs.dm
  code/datums/repositories/crew/crew.dm
  code/datums/repositories/crew/general.dm
  code/datums/repositories/crew/vital.dm
  code/game/machinery/adv_med.dm
  code/game/machinery/bioprinter.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/stacks/nanopaste.dm
  code/game/objects/items/weapons/material/shards.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/mob/living/carbon/brain/brain_item.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
  code/modules/mob/living/silicon/robot/analyzer.dm
  code/modules/mob/mob_helpers.dm
  code/modules/modular_computers/file_system/programs/medical/suit_sensors.dm
  code/modules/organs/blood.dm
  code/modules/organs/body_modifications.dm
  code/modules/organs/external/_external.dm
  code/modules/organs/external/damage.dm
  code/modules/organs/external/stump.dm
  code/modules/organs/external/subtypes/robotic.dm
  code/modules/organs/internal/eyes.dm
  code/modules/organs/internal/heart.dm
  code/modules/organs/internal/machine.dm
  code/modules/organs/internal/xenos/eggsac.dm
  code/modules/organs/organ.dm
  code/modules/organs/organ_icon.dm
  code/modules/organs/pain.dm
  code/modules/power/cable.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/scrap/scrap.dm
  code/modules/surgery/bones.dm
  code/modules/surgery/encased.dm
  code/modules/surgery/face.dm
  code/modules/surgery/generic.dm
  code/modules/surgery/implant.dm
  code/modules/surgery/organs_internal.dm
  code/modules/surgery/robotics.dm
  nano/templates/crew_monitor.tmpl
Labels: NanoUI, QOL, READY FOR REVIEW, Refactoring, Testing required

#3585 Fixes and Improvements for Email client/Crew records
  code/controllers/subsystems/jobs.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/modules/modular_computers/NTNet/NTNet.dm
  code/modules/modular_computers/NTNet/emails/email_account.dm
  code/modules/modular_computers/file_system/programs/generic/bounty_board.dm
  code/modules/modular_computers/file_system/programs/generic/email_client.dm
  code/modules/modular_computers/file_system/programs/research/email_administration.dm
  code/modules/modular_computers/file_system/reports/crew_record.dm
  code/modules/modular_computers/file_system/reports/people.dm
  code/modules/modular_computers/terminal/terminal_skill_fail.dm
  nano/templates/email_client.tmpl
Labels: QOL, READY FOR REVIEW

#3616 Adds rod effect to reinforced glass stacks
  icons/obj/stack/material.dmi
Labels: READY FOR REVIEW, Sprites

#3618 Obelisk new sprites
  icons/obj/neotheology_machinery.dmi
Labels: Sprites

#3619 Adds new retro gun sprite, adjusts laser cannon.
  code/game/objects/items/weapons/storage/pouches.dm
  code/modules/projectiles/guns/energy/laser.dm
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
  icons/obj/guns/energy.dmi
Labels: Guns, READY FOR REVIEW, Rebalance, Sprites

#3623 Grey Railings, railings improvement and crafting fixes
  code/datums/craft/recipe.dm
  code/game/atoms.dm
  code/game/objects/structures/railing.dm
  code/modules/materials/materials.dm
  icons/obj/railing.dmi
Labels: Priority, READY FOR REVIEW

#3611 [FIX] Serb double spawning fix
  code/game/gamemodes/roleset/faction/roleset_faction.dm
  code/game/gamemodes/roleset/roleset.dm
  code/game/gamemodes/storyevent.dm
Labels: Antags, Bug fixes, DO NOT MERGE, Storytellers

#3627 [DRAFT] China mods
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  icons/obj/tool_upgrades.dmi
Labels: DO NOT MERGE, Discussion needed, New features, New items, QOL, Rebalance, Refactoring, Rework, Tools and stat systems, WIP

#3615 Makes vigilance suck less
  code/datums/datum_click_handlers.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/automatic/IH_heavy.dm
  code/modules/projectiles/guns/projectile/automatic/IH_machinepistol.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/atreides.dm
  code/modules/projectiles/guns/projectile/automatic/c20r.dm
  code/modules/projectiles/guns/projectile/automatic/dallas.dm
  code/modules/projectiles/guns/projectile/automatic/idaho.dm
  code/modules/projectiles/guns/projectile/automatic/maxim.dm
  code/modules/projectiles/guns/projectile/automatic/sol.dm
  code/modules/projectiles/guns/projectile/automatic/sts35.dm
  code/modules/projectiles/guns/projectile/automatic/z8.dm
  code/modules/projectiles/guns/projectile/pistol/olivaw.dm
Labels: Guns, READY FOR REVIEW, Rebalance, Testing required

#3624 Crafting improvements, stat checks reworks
  code/__defines/mob_stats.dm
  code/datums/craft/recipe.dm
  code/datums/craft/recipes/airlocks.dm
  code/datums/craft/recipes/clothing.dm
  code/datums/craft/recipes/floor.dm
  code/datums/craft/recipes/furniture.dm
  code/datums/craft/recipes/machinery.dm
  code/datums/craft/recipes/misc.dm
  code/datums/craft/recipes/tools.dm
  code/datums/craft/recipes/weapon.dm
  code/datums/craft/step.dm
  code/datums/mob_stats.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/traps.dm
  code/game/objects/structures/burrows.dm
Labels: Crafting, enhancement
