Repository discordia-space/CEV-Eris, pull requests merged in 2019-05, with the labels that each got.

#3526 Onestar items
  cev_eris.dme
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/game/objects/items/weapons/emp_mine.dm
  code/game/objects/items/weapons/tanks/onestar_regenerator.dm
  code/modules/clothing/glasses/thermal.dm
  icons/inventory/belt/mob.dmi
  icons/inventory/belt/mob_fat.dmi
  icons/inventory/belt/mob_slim.dmi
  icons/inventory/eyes/icon.dmi
  icons/inventory/eyes/mob.dmi
  icons/inventory/eyes/mob_fat.dmi
  icons/inventory/eyes/mob_slim.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/tank.dmi
  icons/obj/weapons.dmi
Labels: New items

#3528 Fixes broken sprites of AK and STS
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  icons/mob/items/lefthand_guns.dmi
Labels: Sprites

#3525 Fixes lighting_turf.dm,63
  code/modules/lighting/lighting_setup.dm
Labels: Bug fixes

#3532 [FIX] Excelsior implants's role removal works now.
  code/game/objects/items/weapons/implant/implants/excelsior.dm
  code/modules/surgery/implant.dm
Labels: Antags, Bug fixes, Fix, READY FOR REVIEW, Surgery

#3531 IB rebalance
  code/modules/organs/external/_external.dm
Labels: Rebalance

#3523 Manual Redux
  code/game/objects/items/weapons/manuals.dm
  code/modules/library/lib_items.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  html/changelogs/Kurgis-PR-ManualRedux.yml
  icons/obj/library.dmi
Labels: NanoUI, READY FOR REVIEW, UI

#3535 Voting UI
  code/controllers/subsystems/vote.dm
  code/controllers/subsystems/voting/poll_types.dm
Labels: NanoUI, UI, enhancement

#3536 Cryopod antirobbery system
  code/game/machinery/cryopod.dm
Labels: Discussion needed, Fix

#3500 Unnerfing stungloves.
  code/game/objects/items/weapons/stunbaton.dm
  code/modules/clothing/gloves/stungloves.dm
Labels: Rebalance

#3534 Re-adjusts One Star stats, toggleable pickaxes, and nerfs spades.
  code/datums/autolathe/tools.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/tools/crowbars.dm
  code/game/objects/items/weapons/tools/misc.dm
  code/game/objects/items/weapons/tools/pickaxe.dm
  code/game/objects/items/weapons/tools/screwdrivers.dm
  code/game/objects/items/weapons/tools/shovel.dm
  code/game/objects/items/weapons/tools/surgicaldrills.dm
  code/game/objects/items/weapons/tools/weldingtools.dm
  html/changelogs/Kurgis-PR-ToolChange.yml
  icons/obj/discs.dmi
  icons/obj/tools.dmi
Labels: READY FOR REVIEW, Rebalance, Tools and stat systems

#3545 Fixes startup runtimes, adds map shims
  cev_eris.dme
  code/_onclick/hud/hud.dm
  code/controllers/subsystems/ticker.dm
  code/datums/uplink/devices and tools.dm
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/game/objects/random/purerandom.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/modules/admin/verbs/debug.dm
  code/modules/cargo/exports/gear.dm
  code/modules/client/preference_setup/loadout/lists/eyegear.dm
  code/modules/clothing/glasses/meson.dm
  code/modules/clothing/glasses/night.dm
  code/modules/clothing/glasses/powered.dm
  code/modules/clothing/glasses/science.dm
  code/modules/clothing/glasses/thermal.dm
  code/modules/clothing/spacesuits/rig/modules/vision.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/mining/mine_items.dm
  code/modules/power/singularity/singularity.dm
  code/modules/research/designs.dm
  code/modules/research/xenoarchaeology/artifact/effect.dm
  code/modules/research/xenoarchaeology/misc.dm
  code/modules/supermatter/supermatter.dm
  code/unit_tests/equipment_tests.dm
  maps/_map_shims.dm
Labels: Fix, Map, Refactoring

#3544 [TWEAK] Pinpointer will now find the nuclear bomb when the disk is loaded into it.
  code/game/gamemodes/nuclear/pinpointer.dm
  html/changelogs/TorinoFermic_Nuclearpinpointer.yml
  icons/obj/device.dmi
Labels: New features, READY FOR REVIEW, enhancement

#3552 Fixes welder tanks exploding when they shouldn't
  code/game/objects/items/weapons/tools/_tools.dm
Labels: Bug fixes, Fix, Minor, READY FOR REVIEW, Tools and stat systems

#3553 Fixes #3390
  code/game/machinery/autolathe.dm
Labels: Fix

#3556 [FIX] Missing maint hatch sprite restored
  icons/obj/doors/door_assembly.dmi
Labels: Fix, READY FOR REVIEW, Sprites

#3540 Various items that can be recycled by autolathe
  cev_eris.dme
  code/game/objects/items/weapons/material_trash.dm
  code/game/objects/random/junk.dm
  icons/obj/material_trash.dmi
Labels: New items, READY FOR REVIEW

#3555 Ports hallucinations refactor from bay
  cev_eris.dme
  code/__defines/chemistry.dm
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/game/gamemodes/changeling/changeling_powers.dm
  code/game/machinery/computer/arcade_orion.dm
  code/game/machinery/doors/airlock.dm
  code/game/sound.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/hivemind/machines.dm
  code/modules/hivemind/mobs.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/hallucinations.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/living_defines.dm
  code/modules/reagents/reagents/dispenser.dm
  code/modules/reagents/reagents/drugs.dm
  code/modules/reagents/reagents/food-Drinks.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/reagents/reagents/other.dm
  code/modules/supermatter/supermatter.dm
  code/modules/virus2/effect.dm
Labels: New features, Porting, Porting/Bay12

#3520 Chemistry Sprites
  icons/obj/chemical.dmi
  icons/obj/reagentfillings.dmi
Labels: New style, Sprites

#3539 Bounty board app
  cev_eris.dme
  code/_helpers/text.dm
  code/modules/bounty/bounties.dm
  code/modules/modular_computers/NTNet/NTNet.dm
  code/modules/modular_computers/computers/subtypes/preset_laptop.dm
  code/modules/modular_computers/computers/subtypes/preset_pda.dm
  code/modules/modular_computers/file_system/programs/generic/bounty_board.dm
  code/modules/modular_computers/file_system/reports/bounty_entry.dm
  code/modules/modular_computers/file_system/reports/report_field.dm
  nano/templates/bounty_board.tmpl
Labels: NanoUI, New features, READY FOR REVIEW, Testing required, UI

#3547 Ports chemical heater
  cev_eris.dme
  code/__defines/chemistry.dm
  code/__defines/machinery.dm
  code/game/area/areas.dm
  code/game/atoms.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/autolathe_disk_cloner.dm
  code/game/machinery/machinery.dm
  code/game/mecha/mech_fabricator.dm
  code/game/objects/items/weapons/circuitboards/machinery/chemestry.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/turfs/turf.dm
  code/modules/core_implant/cruciform/machinery/cloning.dm
  code/modules/reagents/holder.dm
  code/modules/reagents/machinery.dm
  code/modules/reagents/machinery/chem_dispenser.dm
  code/modules/reagents/machinery/chem_heater.dm
  code/modules/reagents/machinery/chem_master.dm
  code/modules/reagents/machinery/grinder.dm
  code/modules/recycling/disposal.dm
  code/modules/research/circuitprinter.dm
  code/modules/research/designs/circuits.dm
  code/modules/research/protolathe.dm
  nano/js/nano_base_helpers.js
  nano/templates/chem_dispenser.tmpl
  nano/templates/chem_heater.tmpl
Labels: Chemistry, Porting, Porting/TG

#3529 Obelisk
  cev_eris.dme
  code/controllers/subsystems/migration.dm
  code/game/objects/structures/burrows.dm
  code/modules/core_implant/cruciform/machinery/obelisk.dm
  code/modules/core_implant/ritual.dm
  icons/obj/neotheology_machinery.dmi
Labels: New features, New structure

#3577 Fixes MC init
  code/game/atoms.dm
Labels: Critical, Fix

#3546 Biomatter manipulation
  cev_eris.dme
  code/__defines/materials.dm
  code/game/machinery/multistructure.dm
  code/game/machinery/sorter.dm
  code/game/objects/items/weapons/circuitboards/machinery/neotheology.dm
  code/game/objects/items/weapons/circuitboards/machinery/sorter.dm
  code/game/objects/structures/window.dm
  code/modules/biomatter_manipulation/biogenerator.dm
  code/modules/biomatter_manipulation/bioreactor/bioreactor.dm
  code/modules/biomatter_manipulation/bioreactor/biotank.dm
  code/modules/biomatter_manipulation/bioreactor/console.dm
  code/modules/biomatter_manipulation/bioreactor/loader.dm
  code/modules/biomatter_manipulation/bioreactor/platform.dm
  code/modules/biomatter_manipulation/bioreactor/port.dm
  code/modules/biomatter_manipulation/bioreactor/unloader.dm
  code/modules/biomatter_manipulation/toxic_biomass.dm
  code/modules/core_implant/cruciform/machinery/cloning.dm
  code/modules/core_implant/cruciform/modules.dm
  code/modules/core_implant/cruciform/rituals/base.dm
  code/modules/core_implant/cruciform/rituals/machinery.dm
  code/modules/core_implant/cruciform/rituals/priest.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/living_defense.dm
  code/modules/organs/organ.dm
  code/modules/reagents/reagent_containers/food.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
  code/modules/reagents/reagents/other.dm
  icons/obj/bioreactor_misc.dmi
  icons/obj/machines/biogenerator.dmi
  icons/obj/machines/bioreactor.dmi
  icons/obj/machines/sorter.dmi
  nano/templates/bioreactor.tmpl
  nano/templates/nt_biogen.tmpl
  nano/templates/sorter.tmpl
Labels: New features, New items, New structure, Sprites

#3564 NT access and roles update
  cev_eris.dme
  code/__defines/jobs.dm
  code/_helpers/global_lists.dm
  code/_helpers/manifest.dm
  code/_helpers/mobs.dm
  code/controllers/subsystems/jobs.dm
  code/datums/objective/baptize.dm
  code/datums/outfits/jobs/church.dm
  code/datums/uplink/neotheology.dm
  code/datums/uplink/uplink_categories.dm
  code/game/antagonist/station/changeling.dm
  code/game/antagonist/station/inquisitor.dm
  code/game/jobs/_access_defs.dm
  code/game/jobs/access.dm
  code/game/jobs/access_datum.dm
  code/game/jobs/department.dm
  code/game/jobs/job/church.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/silicon.dm
  code/game/machinery/vending.dm
  code/modules/client/preference_setup/general/01_basic.dm
  code/modules/client/preference_setup/loadout/lists/misc.dm
  code/modules/client/preference_setup/occupation/occupation.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/core_implant/core_implant.dm
  code/modules/core_implant/cruciform/cruciform.dm
  code/modules/core_implant/cruciform/modules.dm
  code/modules/core_implant/cruciform/rituals/crusader.dm
  code/modules/core_implant/cruciform/rituals/group.dm
  code/modules/core_implant/cruciform/rituals/priest.dm
  code/modules/core_implant/cruciform/upgrades.dm
  code/modules/core_implant/module.dm
  code/modules/core_implant/ritual.dm
  code/modules/core_implant/ritual_book.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/multiz/map_data.dm
  code/modules/organs/body_modifications.dm
Labels: Fix, New features, READY FOR REVIEW, enhancement

#3560 Autolathe and tech disks can now be used in modular PCs
  cev_eris.dme
  code/controllers/subsystems/research.dm
  code/datums/autolathe/autolathe_datums.dm
  code/datums/wires/autolathe.dm
  code/game/antagonist/station/revolutionary/excel_faction.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/autolathe_disk_cloner.dm
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/random/lathe_disks.dm
  code/game/objects/random/techparts.dm
  code/modules/cargo/exports/research.dm
  code/modules/clothing/spacesuits/rig/modules/computer.dm
  code/modules/modular_computers/computers/modular_computer/ui.dm
  code/modules/modular_computers/file_system/binary/binary.dm
  code/modules/modular_computers/file_system/binary/design.dm
  code/modules/modular_computers/file_system/binary/tech.dm
  code/modules/modular_computers/file_system/computer_file.dm
  code/modules/modular_computers/file_system/data.dm
  code/modules/modular_computers/file_system/programs/generic/configurator.dm
  code/modules/modular_computers/file_system/programs/generic/file_browser.dm
  code/modules/modular_computers/hardware/_hardware.dm
  code/modules/modular_computers/hardware/hard_drive.dm
  code/modules/modular_computers/hardware/portable_hard_drive.dm
  code/modules/research/designs.dm
  code/modules/research/designs/computer_parts.dm
  code/modules/research/designs/stock_parts.dm
  code/modules/research/rdconsole.dm
  code/modules/research/research.dm
  maps/_map_shims.dm
  nano/templates/autolathe.tmpl
  nano/templates/autolathe_disk_cloner.tmpl
  nano/templates/file_manager.tmpl
  nano/templates/mpc_configuration.tmpl
  nano/templates/mpc_file_manager.tmpl
  nano/templates/mpc_mainscreen.tmpl
Labels: New features, READY FOR REVIEW, enhancement

#3575 [BALANCE] Autoaim removal
  cev_eris.dme
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/datums/datum_hud.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/clothing/accessories/holster.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/species/species_hud.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/targeting/targeting_client.dm
  code/modules/projectiles/targeting/targeting_gun.dm
  code/modules/projectiles/targeting/targeting_mob.dm
  code/modules/projectiles/targeting/targeting_overlay.dm
  code/modules/projectiles/targeting/targeting_triggers.dm
Labels: Fix, READY FOR REVIEW, Rebalance, UI

#3588 Assembly fix
  code/modules/integrated/integrated_electronics/core/assemblies.dm
Labels: Bug fixes, Fix

#3586 Fixes vis related runtimes
  code/modules/admin/view_variables/view_variables.dm
  code/modules/multiz/turf_icon.dm
Labels: READY FOR REVIEW, runtime error

#3591 Automatically restarts server after sometime if no players
  code/controllers/configuration.dm
  code/controllers/subsystems/ticker.dm
  config/example/config.txt
Labels: READY FOR REVIEW

#3599 [FIX] Various fixes for lost in space
  code/game/mecha/mecha.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/coffin.dm
  code/modules/overmap/spacetravel.dm
  html/changelogs/TorinoFermic_lostinspace.yml
Labels: Bug fixes, Fix, Porting, Porting/Bay12, READY FOR REVIEW

#3597 Folder Sprite Change
  html/changelogs/Kurgs-PR-Folder-Sprite-Change.yml
  icons/obj/bureaucracy.dmi
Labels: Sprites

#3602 Quick fix for coffins
  code/game/objects/structures/crates_lockers/closets/coffin.dm
Labels: Bug fixes, Fix, Important

#3603 Carpet floor fix.
  code/game/turfs/flooring/flooring.dm
Labels: Fix, Minor

#3550 Players get additional stats when they become an antag.
  code/game/antagonist/antagonist.dm
  code/game/antagonist/station/changeling.dm
  code/game/antagonist/station/inquisitor.dm
  code/game/antagonist/station/marshal.dm
  code/game/antagonist/station/revolutionary/excelsior.dm
  code/game/antagonist/station/traitor.dm
  code/modules/core_implant/cruciform/rituals/base.dm
Labels: Antags, Discussion needed, READY FOR REVIEW

#3601 New Ian sprites.
  html/changelogs/Kurgis-PR-IanSpritechange.yml
  icons/mob/animal.dmi
  icons/mob/corgi_back.dmi
Labels: Sprites

#3596 New material stack icons.
  code/modules/materials/material_sheets.dm
  html/changelogs/Kurgis-PR-Material-Icons.yml
  icons/obj/items.dmi
  icons/obj/stack/material.dmi
Labels: Sprites

#3600 Wipe Core now gives cryo-sleep respawn bonus.
  code/__defines/mobs.dm
  code/game/machinery/cryopod.dm
  code/modules/mob/living/silicon/ai/latejoin.dm
  code/modules/mob/observer/ghost/ghost.dm
  html/changelogs/Kurgis-PR-Wipe-Core-Fix.yml
Labels: AI, READY FOR REVIEW, Silicons

#3610 Fix slim captain suit sprite
  icons/inventory/suit/mob_slim.dmi
Labels: Bug fixes, Fix, READY FOR REVIEW, Sprites
