Repository discordia-space/CEV-Eris, pull requests merged in 2019-03, with the labels that each got.

#2780 Add stats transfering on cloning
  code/datums/mind.dm
  code/datums/mob_stats.dm
  code/modules/core_implant/cruciform/machinery/cloning.dm
  code/modules/core_implant/cruciform/modules.dm
Labels: Next Update, READY FOR REVIEW

#3039 Fail chance on tool actions is now rounded down
  code/game/objects/items/weapons/tools/_tools.dm
Labels: READY FOR REVIEW

#3066 Stashes
  cev_eris.dme
  code/__defines/items_clothing.dm
  code/__defines/misc.dm
  code/_helpers/areas.dm
  code/_helpers/game.dm
  code/_helpers/global_lists.dm
  code/_helpers/icons.dm
  code/_helpers/lists.dm
  code/game/objects/effects/decals/remains.dm
  code/game/objects/items/stacks/telecrystal.dm
  code/game/objects/items/weapons/storage/deferred.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/random/ammo.dm
  code/game/objects/random/credits.dm
  code/game/objects/random/guns.dm
  code/game/objects/random/junk.dm
  code/game/objects/random/melee.dm
  code/game/objects/random/pouches.dm
  code/game/objects/random/purerandom.dm
  code/game/objects/random/rare.dm
  code/game/objects/random/themed/astersguild.dm
  code/game/objects/random/tools.dm
  code/modules/materials/material_sheets.dm
  code/modules/mining/money_bag.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/paper_bundle.dm
  code/modules/paperwork/photography.dm
  code/modules/stashes/stash_datum.dm
  code/modules/stashes/stash_items.dm
  code/modules/stashes/stash_spawner.dm
  code/modules/stashes/stash_types/booze.dm
  code/modules/stashes/stash_types/captain.dm
  code/modules/stashes/stash_types/excelsior.dm
  code/modules/stashes/stash_types/junk.dm
  code/modules/stashes/stash_types/ninja.dm
  code/modules/stashes/stash_types/valueables.dm
  code/modules/stashes/stash_types/weapons.dm
  code/stylesheet.dm
  icons/obj/storage.dmi
Labels: READY FOR REVIEW

#3141 Lowering speed of space drones.
  code/modules/mob/living/simple_animal/hostile/retaliate/drone.dm
Labels: Rebalance

#3165 Rebalancing cooking of grenades.
  code/game/objects/items/weapons/grenades/chem_grenade.dm
  code/game/objects/items/weapons/grenades/grenade.dm
Labels: Rebalance

#3217 Recolouring pipes.
  code/ATMOSPHERICS/_atmos_setup.dm
  code/game/objects/items/weapons/tools/wirecutters.dm
  icons/obj/structures.dmi
Labels: Sprites
