Repository discordia-space/CEV-Eris, pull requests merged in 2019-02, with the labels that each got.

#2758 Restructuring ship areas.
  cev_eris.dme
  code/controllers/evacuation/evacuation.dm
  code/datums/mind.dm
  code/game/antagonist/outer/mercenary/merc_faction.dm
  code/game/area/Space Station 13 areas.dm
  code/game/gamemodes/endgame/supermatter_cascade/universe.dm
  code/game/gamemodes/events/prison_break.dm
  code/game/objects/items/blueprints.dm
  code/game/turfs/simulated.dm
  code/unit_tests/map_tests.dm
  code/unit_tests/zas_tests.dm
  icons/turf/areas.dmi
  maps/CEVEris/_CEV_Eris.dmm
  maps/CEVEris/_Eris_areas.dm
  maps/CEVEris/centcomm.dmm
Labels: Map, READY FOR REVIEW, Refactoring

#2770 Prevent the middle mouse drag exploit
  code/_onclick/click.dm
  code/controllers/configuration.dm
  code/modules/client/client procs.dm
  config/example/config.txt
Labels: DO NOT MERGE

#2741 Fix for round delay
  code/controllers/subsystems/vote.dm
  code/modules/admin/admin.dm
Labels: Fix, High Risk

#2783 Cells for Excelsior.
  cev_eris.dme
  code/datums/autolathe/cells.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/items/weapons/power_cells.dm
  code/game/objects/random/powercells.dm
  code/game/objects/random/techparts.dm
  icons/obj/power.dmi
Labels: Sprites

#2767 Grenade nerfs
  code/game/objects/items/weapons/grenades/explosive.dm
  code/game/objects/items/weapons/grenades/grenade.dm
  code/game/objects/items/weapons/storage/boxes.dm
Labels: Next Update, READY FOR REVIEW

#2797 Jive, and bay speech
  cev_eris.dme
  code/__defines/species_languages.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/guild.dm
  code/modules/client/preference_setup/background/02_language.dm
  code/modules/client/preference_setup/background/03_records.dm
  code/modules/client/preference_setup/preference_setup.dm
  code/modules/mob/hear_say.dm
  code/modules/mob/language/jive.dm
  code/modules/mob/language/language.dm
  code/modules/mob/language/monkey.dm
  code/modules/mob/language/serbian.dm
  code/modules/mob/language/station.dm
  code/modules/mob/living/default_language.dm
  code/modules/mob/living/say.dm
  code/stylesheet.dm
Labels: READY FOR REVIEW

#2790 Full Auto Firing Mode
  code/__defines/weapons.dm
  code/_onclick/click.dm
  code/datums/datum_click_handlers.dm
  code/game/objects/items.dm
  code/game/objects/objs.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/atreides.dm
  code/modules/projectiles/guns/projectile/automatic/dallas.dm
  code/modules/projectiles/guns/projectile/automatic/idaho.dm
  code/modules/projectiles/guns/projectile/automatic/l6_saw.dm
  code/modules/projectiles/guns/projectile/automatic/maxim.dm
  code/modules/projectiles/guns/projectile/automatic/sts35.dm
  code/modules/projectiles/guns/projectile/automatic/z8.dm
  code/modules/projectiles/projectile.dm
Labels: READY FOR REVIEW

#2852 Light color rework
  code/__defines/colors.dm
  code/__defines/lighting.dm
  code/datums/security_state.dm
  code/game/area/Space Station 13 areas.dm
  code/game/machinery/alarm.dm
  code/game/machinery/atmoalter/area_atmos_computer.dm
  code/game/machinery/computer/aifixer.dm
  code/game/machinery/computer/atmos_alert.dm
  code/game/machinery/computer/atmos_control.dm
  code/game/machinery/computer/cloning.dm
  code/game/machinery/computer/guestpass.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/pod.dm
  code/game/machinery/computer/prisoner.dm
  code/game/machinery/computer/prisonshuttle.dm
  code/game/machinery/computer/robot.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/computer/station_alert.dm
  code/game/machinery/computer/supply.dm
  code/game/machinery/computer/syndicate_specops_shuttle.dm
  code/game/machinery/cryopod.dm
  code/game/machinery/floor_light.dm
  code/game/machinery/hologram.dm
  code/game/machinery/holoposter.dm
  code/game/machinery/lightswitch.dm
  code/game/machinery/supplybeacon.dm
  code/game/machinery/turret_control.dm
  code/game/machinery/vending.dm
  code/game/mecha/mecha_control_console.dm
  code/game/objects/items/devices/lighting/flare.dm
  code/game/objects/items/devices/lighting/toggleable/lamp.dm
  code/game/objects/items/weapons/candle.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/structures/cyberplants.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/spacesuits/rig/suits/combat.dm
  code/modules/clothing/spacesuits/rig/suits/merc.dm
  code/modules/mob/living/simple_animal/hostile/hivebot.dm
  code/modules/overmap/ships/computers/helm.dm
  code/modules/overmap/ships/computers/sensors.dm
  code/modules/overmap/ships/engines/thermal.dm
  code/modules/power/apc.dm
  code/modules/power/lighting.dm
  code/modules/power/sensors/sensor_monitoring.dm
  code/modules/research/rdconsole.dm
  code/modules/research/server.dm
  code/modules/shuttles/landmarks.dm
  code/modules/virus2/curer.dm
  code/modules/virus2/diseasesplicer.dm
  maps/CEVEris/_Eris_areas.dm
  oldcode/computer/old_shuttle.dm
Labels: Light system

#2737 Openspace vis_contents 2
  cev_eris.dme
  code/__defines/_planes+layers.dm
  code/_onclick/hud/HUD_element/HUD_element.dm
  code/_onclick/hud/openspace_overlays.dm
  code/_onclick/hud/parallax.dm
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/_onclick/telekinesis.dm
  code/datums/datum_hud.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/machinery/lightswitch.dm
  code/game/objects/items/devices/t_scanner.dm
  code/game/objects/items/weapons/policetape.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/items/weapons/tools/tape.dm
  code/game/objects/structures/catwalk.dm
  code/game/objects/structures/low_wall.dm
  code/game/turfs/flooring/flooring_decals.dm
  code/game/turfs/simulated/floor_icon.dm
  code/game/turfs/space/space.dm
  code/modules/admin/verbs/buildmode.dm
  code/modules/lighting/lighting_overlay.dm
  code/modules/mob/animations.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/robot/gripper.dm
  code/modules/mob/living/silicon/robot/inventory.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/mob.dm
  code/modules/mob/observer/freelook/chunk.dm
  code/modules/multiz/basic.dm
  code/modules/multiz/map_data.dm
  code/modules/multiz/planes.dm
  code/modules/multiz/shadow.dm
  code/modules/multiz/turf.dm
  code/modules/multiz/turf_icon.dm
  code/modules/multiz/ztravel/climb.dm
  code/modules/multiz/ztravel/jetpack.dm
  code/modules/multiz/ztravel/jump.dm
  code/modules/multiz/ztravel/zmethod.dm
  code/modules/overmap/sectors.dm
  code/modules/projectiles/effects.dm
  code/modules/random_map/random_map.dm
  code/modules/ventcrawl/ventcrawl.dm
  icons/480x480.dmi
  icons/turf/space.dmi
  maps/CEVEris/_map_data_Eris.dm
  maps/encounters/spacefortress/spacefortress.dm
  maps/encounters/spacefortress/spacefortress.dmm
Labels: READY FOR REVIEW

#2924 New gun sprites.
  code/modules/projectiles/guns/launcher/grenade_launcher.dm
  code/modules/projectiles/guns/projectile/pistol/mk58.dm
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
  icons/obj/gun.dmi
Labels: Sprites

#2886 Spawning Redesign: Backups and Immersion
  code/_helpers/turfs.dm
  code/controllers/subsystems/jobs.dm
  code/defines/obj.dm
  code/game/machinery/cryopod.dm
  code/game/objects/landmarks/join.dm
  code/game/objects/structures/bedsheet_bin.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/modules/client/preferences_spawnpoints.dm
  code/modules/mob/angel/angel.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/mob/observer/ghost/ghost.dm
  code/modules/mob/transform_procs.dm
  code/unit_tests/mob_tests.dm
  maps/CEVEris/_CEV_Eris.dmm
  maps/CEVEris/_map_data_Eris.dm
Labels: READY FOR REVIEW

#2941 Rollerbed Rack Fix
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
Labels: Fix

#2931 Beartrap Fix and Tweaks
  code/_onclick/cyborg.dm
  code/game/objects/items/weapons/traps.dm
  code/modules/mob/living/carbon/resist.dm
  code/modules/mob/living/living.dm
Labels: READY FOR REVIEW

#2773 Antigrav generator
  cev_eris.dme
  code/game/area/Space Station 13 areas.dm
  code/game/area/areas.dm
  code/game/gamemodes/events/gravity.dm
  code/game/machinery/antigrav.dm
  code/game/objects/items/weapons/circuitboards/machinery/power.dm
  code/global.dm
  code/modules/admin/secrets/random_events/gravity.dm
  code/modules/holodeck/HolodeckControl.dm
  code/modules/power/gravitygenerator.dm
  icons/obj/stationobjs.dmi
Labels: READY FOR REVIEW

#2894 Hivemind
  cev_eris.dme
  code/game/gamemodes/events/hivemind_invasion.dm
  code/game/objects/structures/burrows.dm
  code/modules/hivemind/core.dm
  code/modules/hivemind/machines.dm
  code/modules/hivemind/mobs.dm
  code/modules/hivemind/objects.dm
  code/modules/hivemind/wires.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/spreading/spreading_growth.dm
  icons/mob/hivemind.dmi
  icons/obj/hivemind.dmi
  icons/obj/hivemind_machines.dmi
Labels: DO NOT MERGE

#2936 Ports radials from /tg/, and applies it to borg icon choice
  cev_eris.dme
  code/_helpers/atoms.dm
  code/_helpers/lists.dm
  code/_onclick/hud/radial.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/mob/living/silicon/robot/login.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/projectiles/guns/projectile/sniper.dm
  icons/mob/radial/menu.dmi
Labels: Discussion needed
