Repository discordia-space/CEV-Eris, pull requests merged in 2019-01, with the labels that each got.

#2439 Proper buckling
  code/game/objects/buckling.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
Labels: Fix, QOL, READY FOR REVIEW

#2425 Economy: Phase 1
  cev_eris.dme
  code/controllers/subsystems/supply.dm
  code/datums/datacore.dm
  code/datums/outfits/jobs/guild.dm
  code/game/jobs/job/guild.dm
  code/game/machinery/computer/supply.dm
  code/global.dm
  code/modules/economy/cash_register.dm
  code/modules/economy/economy_misc.dm
  code/modules/mob/living/simple_animal/parrot.dm
Labels: READY FOR REVIEW

#2434 Inquisitor Rework and Uplink Fixes
  cev_eris.dme
  code/datums/outfits/jobs/church.dm
  code/datums/uplink/ammunition.dm
  code/datums/uplink/neotheology.dm
  code/datums/uplink/stealthy and inconspicuous weapons.dm
  code/datums/uplink/uplink_categories.dm
  code/datums/uplink/uplink_sources.dm
  code/game/antagonist/antagonist_create.dm
  code/game/antagonist/station/inquisitor.dm
  code/game/antagonist/station/marshal.dm
  code/game/antagonist/station/traitor.dm
  code/game/gamemodes/roleset/roleset.dm
  code/game/gamemodes/roleset/simple.dm
  code/game/gamemodes/storyteller_print.dm
  code/game/jobs/job/civilian_chaplain.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/devices/uplink.dm
  code/game/objects/items/weapons/implant/implants/uplink.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/modules/admin/verbs/debug.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/core_implant/cruciform/cruciform.dm
  code/modules/core_implant/cruciform/modules.dm
  code/modules/core_implant/cruciform/rituals/inquisitor.dm
  code/modules/core_implant/cruciform/upgrades.dm
  code/modules/core_implant/ritual.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/projectiles/guns/energy/pulse.dm
Labels: READY FOR REVIEW

#2440 Folding sheets
  code/game/objects/items.dm
  code/game/objects/items/devices/lighting/toggleable/flashlight.dm
  code/game/objects/items/weapons/policetape.dm
  code/game/objects/items/weapons/storage/laundry_basket.dm
  code/game/objects/items/weapons/trays.dm
  code/game/objects/structures/bedsheet_bin.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/modules/games/cards.dm
  code/modules/hydroponics/grown.dm
  code/modules/lighting/lighting_atom.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  icons/obj/bedsheets.dmi
  icons/obj/items.dmi
Labels: Minor, READY FOR REVIEW, Sprites

#2438 Fire alarm UI converted to NanoUI and more AI interactions
  code/ATMOSPHERICS/components/unary/cold_sink.dm
  code/__defines/machinery.dm
  code/_onclick/ai.dm
  code/_onclick/cyborg.dm
  code/game/machinery/alarm.dm
  code/game/machinery/telecomms/machine_interactions.dm
  code/modules/power/smes.dm
  nano/templates/fire_alarm.tmpl
Labels: AI, NanoUI, READY FOR REVIEW, Silicons

#2454 New sprites for stairs.
  icons/obj/stairs.dmi
Labels: New style, Sprites

#2453 New cryo sprites.
  icons/obj/Cryogenic2.dmi
Labels: New style, Sprites

#2462 Fixes for new floors.
  code/game/turfs/flooring/flooring.dm
Labels: New style, Sprites

#2459 New toolmod sprites.
  icons/obj/tool_upgrades.dmi
Labels: New style, Sprites

#2429 Hardsuit Storage
  cev_eris.dme
  code/game/objects/items/weapons/storage/internal.dm
  code/game/objects/random/purerandom.dm
  code/game/objects/random/rare.dm
  code/game/objects/random/rig.dm
  code/game/objects/random/tools.dm
  code/modules/clothing/spacesuits/rig/modules/modules.dm
  code/modules/clothing/spacesuits/rig/modules/storage.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/spacesuits/rig/rig_attackby.dm
  code/modules/clothing/spacesuits/rig/rig_modules.dm
  code/modules/clothing/spacesuits/rig/suits/station.dm
  code/modules/clothing/suits/storage.dm
Labels: READY FOR REVIEW

#2458 enable progress bar and backpack attack_hand
  code/datums/progressbar.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/modules/mob/living/carbon/human/stripping.dm
Labels: READY FOR REVIEW

#2481 Small floor fixes.
  icons/turf/flooring/tiles_dark.dmi
  icons/turf/flooring/tiles_steel.dmi
  icons/turf/flooring/tiles_white.dmi
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map, New style, Sprites

#2460 Pref hair cycle buttons
  code/modules/client/preference_setup/general/02_body.dm
  code/modules/client/preference_setup/preview.dm
Labels: READY FOR REVIEW

#2487 Small map related fixes.
  icons/turf/flooring/tiles_steel.dmi
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map

#2492 Fixing flags for reinforced floor.
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/simulated/floor_types.dm
Labels: Fix, Sprites

#2431 Mecha Thrusters and Z mechanics
  cev_eris.dme
  code/_helpers/atoms.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/mecha/equipment/mecha_equipment.dm
  code/game/mecha/equipment/tools/medical_tools.dm
  code/game/mecha/equipment/tools/thruster.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/mecha/equipment/weapons/weapons.dm
  code/game/mecha/mecha.dm
  code/game/mecha/working/ripley.dm
  code/game/objects/effects/trails.dm
  code/game/objects/items/weapons/tanks/jetpack.dm
  code/game/objects/structures/catwalk.dm
  code/modules/admin/verbs/adminjump.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_movement.dm
  code/modules/multiz/movement.dm
  code/modules/multiz/turf.dm
  code/modules/multiz/ztravel/climb.dm
  code/modules/multiz/ztravel/jetpack.dm
  code/modules/multiz/ztravel/phase.dm
  code/modules/multiz/ztravel/zmethod.dm
  code/modules/research/mechfab_designs.dm
Labels: READY FOR REVIEW

#2535 Holster can now contain more types of pistols.
  code/game/objects/items/weapons/storage/pouches.dm
Labels: Fix

#2549 Closets and crates now can be hacked.
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Fix

#2550 Small changes on map.
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map

#2455 Interface rework and new AI interface
  cev_eris.dme
  code/_helpers/icons.dm
  code/_onclick/ai.dm
  code/_onclick/cyborg.dm
  code/_onclick/ghost.dm
  code/_onclick/hud/HUD_element/HUD_element.dm
  code/_onclick/hud/HUD_element/_HUD_defines.dm
  code/_onclick/hud/HUD_element/external_procs.dm
  code/_onclick/hud/HUD_element/internal_procs.dm
  code/_onclick/hud/HUD_element/types/button.dm
  code/_onclick/hud/HUD_element/types/custom_buttons.dm
  code/_onclick/hud/HUD_element/types/layout.dm
  code/_onclick/hud/HUD_element/types/threePartBox.dm
  code/datums/mind.dm
  code/game/machinery/camera/tracking.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/client/client defines.dm
  code/modules/client/client procs.dm
  code/modules/client/preference_setup/global/01_ui.dm
  code/modules/mob/UI.dm
  code/modules/mob/living/login.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/ai_UI.dm
  code/modules/mob/living/silicon/subsystems.dm
  code/modules/mob/login.dm
  code/modules/mob/logout.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/mob/observer/freelook/ai/eye.dm
  code/modules/mob/observer/ghost/ghost.dm
  code/modules/mob/observer/observer_UI.dm
  icons/mob/screen/ErisStyle_32x32.dmi
  icons/mob/screen/misc.dmi
  icons/mob/screen/silicon/AI/HUD_actionButtons.dmi
  icons/mob/screen/silicon/HUD_status.dmi
  icons/mob/screen/silicon/battery.dmi
Labels: READY FOR REVIEW

#2537 Security levels fixes
  cev_eris.dme
  code/__defines/gamemode.dm
  code/datums/security_state.dm
  code/game/gamemodes/malfunction/newmalf_ability_trees/tree_networking.dm
  code/game/machinery/alarm.dm
  code/game/machinery/holoposter.dm
  code/game/machinery/machinery.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/security levels/keycard authentication.dm
  code/modules/security levels/security levels.dm
  icons/obj/monitors.dmi
Labels: Fix

#2589 Merc Fixes
  cev_eris.dme
  code/datums/mind.dm
  code/datums/objective/merc_mission.dm
  code/game/antagonist/antagonist_create.dm
  code/game/antagonist/antagonist_factions.dm
  code/game/gamemodes/roleset/faction/roleset_faction.dm
  code/game/gamemodes/roleset/roleset.dm
Labels: Critical

#2584 Medical vendors and some minor access changes
  code/game/jobs/job/security.dm
  code/game/machinery/vending.dm
  maps/CEVEris/_CEV_Eris.dmm
Labels: Discussion needed, Minor, READY FOR REVIEW, Rebalance

#2601 QOL Door interactions, apc lights, inhand ID door interaction
  code/_onclick/ai.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/door.dm
  code/game/turfs/turf.dm
  code/modules/power/apc.dm
Labels: READY FOR REVIEW

#2639 Embedding Fixes
  code/game/objects/items.dm
  code/game/objects/items/weapons/material/knives.dm
  code/game/objects/items/weapons/material/thrown.dm
  code/game/objects/items/weapons/material/twohanded.dm
  code/game/objects/items/weapons/melee/energy.dm
  code/game/objects/items/weapons/tools/pickaxe.dm
  code/game/objects/items/weapons/tools/saws.dm
  code/game/objects/objs.dm
  code/modules/mob/death.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/superior_animal/defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/mob_helpers.dm
Labels: Critical, READY FOR REVIEW

#2642 Roundstart Fixes
  code/controllers/subsystems/ticker.dm
  code/game/gamemodes/storyteller.dm
Labels: READY FOR REVIEW

#2665 Protolathe Cell Exploit Fix
  cev_eris.dme
  code/game/objects/items/devices/device.dm
Labels: READY FOR REVIEW

#2661 Taser and VTec nerf
  code/modules/clothing/spacesuits/void/merc.dm
  code/modules/mob/living/silicon/robot/robot_upgrades.dm
  code/modules/projectiles/projectile/beams.dm
Labels: READY FOR REVIEW

#2638 Mopping Tweaks III
  cev_eris.dme
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/simulated.dm
  code/game/turfs/simulated/cleaning.dm
  code/game/turfs/turf.dm
  icons/effects/effects.dmi
Labels: READY FOR REVIEW

#2668 Uplink fixes and Rebalance
  code/datums/uplink/announcements.dm
  code/datums/uplink/devices and tools.dm
  code/datums/uplink/grenades.dm
  code/datums/uplink/hardsuit_modules.dm
  code/datums/uplink/highly visible and dangerous weapons.dm
  code/datums/uplink/medical.dm
  code/game/objects/items/weapons/grenades/spawnergrenade.dm
  code/game/objects/items/weapons/storage/boxes.dm
Labels: READY FOR REVIEW, Rebalance

#2666 Various Mapping Tweaks
  maps/CEVEris/_CEV_Eris.dmm
Labels: Important, Map, READY FOR REVIEW

#2653 Economy Phase 2: Payday
  cev_eris.dme
  code/__defines/economy.dm
  code/__defines/jobs.dm
  code/__defines/misc.dm
  code/__marcos/lists.dm
  code/_helpers/global_lists.dm
  code/controllers/subsystems/economy.dm
  code/controllers/subsystems/jobs.dm
  code/controllers/subsystems/supply.dm
  code/datums/datacore.dm
  code/game/gamemodes/events/payday.dm
  code/game/jobs/department.dm
  code/game/jobs/job/assistant.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/civilian_chaplain.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/guild.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/jobs/job/silicon.dm
  code/game/jobs/wages.dm
  code/global.dm
  code/modules/economy/ATM.dm
  code/modules/economy/Accounts.dm
  code/modules/economy/EFTPOS.dm
  code/modules/economy/economy_misc.dm
  code/modules/modular_computers/NTNet/emails/email_account.dm
  code/modules/modular_computers/file_system/reports/crew_record.dm
Labels: READY FOR REVIEW

#2676 New crate sprites
  html/changelogs/clock_chang.yml
  html/templates/footer.html
  html/templates/header.html
  icons/obj/storage.dmi
Labels: New style, Sprites

#2679 Removing debug message.
  code/modules/reagents/reagent_containers/food/drinks/bottle.dm
Labels: Fix

#2715 Fix dramatic lights turning
  code/game/machinery/lightswitch.dm
Labels: Fix

#2596 Make splash occur only on harm intent
  code/modules/reagents/reagent_containers/glass.dm
Labels: DO NOT MERGE

#2607 Openspace vis_contents
  cev_eris.dme
  code/__defines/_planes+layers.dm
  code/_onclick/hud/HUD_element/HUD_element.dm
  code/_onclick/hud/openspace_overlays.dm
  code/_onclick/hud/parallax.dm
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/_onclick/telekinesis.dm
  code/datums/datum_hud.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/machinery/lightswitch.dm
  code/game/objects/items/devices/t_scanner.dm
  code/game/objects/items/weapons/policetape.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/items/weapons/tools/tape.dm
  code/game/objects/structures/catwalk.dm
  code/game/objects/structures/low_wall.dm
  code/game/turfs/flooring/flooring_decals.dm
  code/game/turfs/simulated/floor_icon.dm
  code/game/turfs/space/space.dm
  code/modules/admin/verbs/buildmode.dm
  code/modules/lighting/lighting_overlay.dm
  code/modules/mob/animations.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/silicon/robot/gripper.dm
  code/modules/mob/living/silicon/robot/inventory.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/observer/freelook/chunk.dm
  code/modules/multiz/basic.dm
  code/modules/multiz/map_data.dm
  code/modules/multiz/planes.dm
  code/modules/multiz/shadow.dm
  code/modules/multiz/turf.dm
  code/modules/multiz/turf_icon.dm
  code/modules/multiz/ztravel/climb.dm
  code/modules/multiz/ztravel/jetpack.dm
  code/modules/multiz/ztravel/jump.dm
  code/modules/multiz/ztravel/zmethod.dm
  code/modules/overmap/sectors.dm
  code/modules/random_map/random_map.dm
  code/modules/ventcrawl/ventcrawl.dm
  icons/480x480.dmi
  icons/turf/space.dmi
  maps/CEVEris/_map_data_Eris.dm
  maps/encounters/spacefortress/spacefortress.dm
  maps/encounters/spacefortress/spacefortress.dmm
Labels: DO NOT MERGE, Delayed, High Risk

#2728 Fix gravity generator sound's runtime
  code/game/sound.dm
  code/modules/power/gravitygenerator.dm
Labels: DO NOT MERGE

#2750 Shield Diffuser Fixes and Mapping
  code/game/turfs/turf.dm
  code/modules/shield_generators/floor_diffuser.dm
  code/modules/shield_generators/shield.dm
  code/modules/shield_generators/shield_generator.dm
  maps/CEVEris/_CEV_Eris.dmm
Labels: Fix

#2752 Rig allowed items and fixes
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/spacesuits/rig/rig_pieces.dm
  code/modules/clothing/spacesuits/rig/suits/combat.dm
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Fix

#2760 Fixes wire interaction for borgs
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Fix
