Repository discordia-space/CEV-Eris, pull requests merged in 2019-12, with the labels that each got.

#4347 Removes PTSD
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/sanity/breakdowns.dm
Labels: debug

#4350 Insight
  code/game/objects/items/oddities.dm
  code/game/objects/items/weapons/secdocs.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagents.dm
  code/modules/reagents/reagents/drugs.dm
  code/modules/sanity/sanity_mob.dm
Labels: New features

#4358 HUD and NSA rework
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/datums/datum_hud.dm
  code/game/objects/items/devices/organ_module/active.dm
  code/game/objects/items/devices/organ_module/simple.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/species/species_hud.dm
  code/modules/organs/external/_external.dm
  code/modules/sanity/sanity_mob.dm
  icons/mob/screen/ErisStyleHolo.dmi
Labels: HUD, READY FOR REVIEW, Testing required

#4356 Buckling Click Cooldown Fix
  code/modules/mob/living/carbon/resist.dm
Labels: Bug fixes, Fix, READY FOR REVIEW

#4357 Testing travis fix for map checks [DO NOT MERGE]
  .travis.yml
  maps/CEVEris/_CEV_Eris.dmm
  maps/submaps/dungeon_rooms/rooms/commanderoffice.dmm
Labels: DO NOT MERGE

#4366 Update travis map control (#4357)
  .travis.yml
  maps/CEVEris/_CEV_Eris.dmm
  maps/submaps/dungeon_rooms/rooms/commanderoffice.dmm
Labels: Map

#4353 Serbian Vendor
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/storage/deferred.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/soft_caps.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/mercenary.dm
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
  icons/obj/crate.dmi
  icons/obj/vending.dmi
Labels: Antags, READY FOR REVIEW, Rebalance

#4371 HUD fixes
  cev_eris.dme
  code/_onclick/hud/alien_larva.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/openspace_overlays.dm
  code/_onclick/hud/other_mobs.dm
  code/_onclick/hud/robot.dm
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/datums/datum_hud.dm
  code/modules/mob/living/carbon/human/human_hud.dm
  code/modules/mob/living/carbon/human/species/species_hud.dm
  code/modules/mob/living/silicon/robot/robot_hud.dm
  icons/512x512.dmi
  icons/mob/screen/ErisStyleHolo.dmi
  icons/mob/screen1.dmi
  icons/mob/screen1_full.dmi
  icons/obj/hud_full.dmi
Labels: Fix, HUD, READY FOR REVIEW

#4320 Adds zip ties
  code/datums/autolathe/security.dm
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/items/weapons/handcuffs.dm
  maps/CEVEris/_CEV_Eris.dmm
Labels: Fix, QOL

#4291 Various Multitool Interactions & QoL
  code/datums/outfits/jobs/engineering.dm
  code/game/machinery/atmoalter/canister.dm
  code/game/machinery/portable_turret.dm
  code/game/mecha/mecha.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/modules/modular_computers/file_system/programs/antagonist/dos.dm
  code/modules/modular_computers/file_system/programs/antagonist/hacked_camera.dm
  code/modules/modular_computers/file_system/programs/antagonist/revelation.dm
Labels: QOL, READY FOR REVIEW

#4346 Conservation of mass
  code/datums/craft/recipes/furniture.dm
  code/datums/craft/recipes/misc.dm
  code/game/machinery/computer/buildandrepair.dm
  code/game/machinery/constructable_frame.dm
  code/game/machinery/deployable.dm
  code/game/machinery/doors/simple.dm
  code/game/objects/objs.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/coffin.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/low_wall.dm
  code/game/objects/structures/railing.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/tank_dispenser.dm
  code/game/turfs/simulated/wall_types.dm
  code/game/turfs/simulated/walls.dm
  code/modules/library/lib_items.dm
  code/modules/materials/materials.dm
  code/modules/tables/tables.dm
Labels: Bug fixes, Fix, READY FOR REVIEW

#4375 Cleansing carbine
  cev_eris.dme
  code/modules/projectiles/guns/matter.dm
  code/modules/projectiles/guns/matter/launcher.dm
  code/modules/projectiles/guns/matter/launcher/nt_sprayer.dm
  icons/obj/guns/matter/nt_sprayer.dmi
Labels: Guns, READY FOR REVIEW

#4392 Grinder UI
  code/modules/reagents/machinery/grinder.dm
  nano/templates/grinder.tmpl
Labels: NanoUI, READY FOR REVIEW

#4394 Grinder hotfix
  code/modules/reagents/machinery/grinder.dm
Labels: Bug fixes, READY FOR REVIEW

#4393 Quick fix for this Crusader Call to Arms litany
  code/modules/core_implant/cruciform/rituals/crusader.dm
Labels: Bug fixes, READY FOR REVIEW

#4404 New map for chemestry.
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map

#4409 Industrial grinder
  code/game/objects/random/circuitboards.dm
  code/modules/reagents/holder.dm
  code/modules/reagents/machinery/grinder.dm
  icons/obj/machines/grinder.dmi
  maps/CEVEris/_CEV_Eris.dmm
  nano/templates/industrial_grinder.tmpl
Labels: Chemistry, NanoUI, New features, READY FOR REVIEW

#4419 Grinder on map
  icons/obj/machines/grinder.dmi
  maps/CEVEris/_CEV_Eris.dmm
Labels: Chemistry, QOL

#4398 Secdoc spawn fix
  code/controllers/subsystems/jobs.dm
  code/datums/outfits/jobs/job.dm
Labels: Bug fixes, READY FOR REVIEW

#4426 Sprayer projectile now have a different icon.
  code/modules/projectiles/guns/matter/launcher/nt_sprayer.dm
Labels: Fix

#4429 Fixes regarding game balance
  code/game/objects/items/devices/radio/beacon.dm
  code/game/objects/items/weapons/AI_modules.dm
  code/game/objects/items/weapons/storage/wallets.dm
  code/game/objects/random/packs.dm
  code/game/objects/random/rig.dm
  code/modules/clothing/chameleon.dm
Labels: Rebalance

#4433 Some weapon fixes
  code/datums/autolathe/ammo.dm
  code/game/machinery/vending.dm
  code/game/objects/random/ammo.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/pistol/giskard.dm
  code/modules/projectiles/guns/projectile/pistol/olivaw.dm
  maps/CEVEris/_CEV_Eris.dmm
Labels: Fix

#4455 A lot of melee weapons are now tools, and moddable by that.
  cev_eris.dme
  code/datums/autolathe/tools.dm
  code/datums/craft/recipes/weapon.dm
  code/datums/uplink/neotheology.dm
  code/datums/uplink/stealthy and inconspicuous weapons.dm
  code/game/machinery/vending.dm
  code/game/objects/items/devices/organ_module/active/armblades.dm
  code/game/objects/items/weapons/material/bats.dm
  code/game/objects/items/weapons/material/knives.dm
  code/game/objects/items/weapons/material/misc.dm
  code/game/objects/items/weapons/material/swords.dm
  code/game/objects/items/weapons/material/twohanded.dm
  code/game/objects/items/weapons/melee/misc.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/storage/deferred.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/game/objects/random/melee.dm
  code/game/objects/structures/crates_lockers/closets/secure/chaplain.dm
  code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm
  code/modules/admin/verbs/debug.dm
  code/modules/cargo/exports/weapons.dm
  code/modules/cargo/packs.dm
  code/modules/clothing/clothing.dm
  code/modules/hydroponics/grown.dm
  code/modules/mining/abandonedcrates.dm
  code/modules/mob/living/bot/farmbot.dm
  code/modules/mob/living/silicon/robot/gripper.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/simple_animal/hostile/russian.dm
  code/modules/reagents/reagent_containers/food/drinks/bottle.dm
  code/modules/research/xenoarchaeology/artifact/artifact_replicator.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
  code/modules/stashes/stash_types/valueables.dm
  maps/CEVEris/_CEV_Eris.dmm
  maps/CEVEris/centcomm.dmm
Labels: Rebalance

#4446 Ports contained sprites from Aurora
  code/__DEFINES/items_clothing.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/mob/items/lefthand_backpacks.dmi
  icons/mob/items/righthand_backpacks.dmi
  icons/obj/storage/backpack.dmi
Labels: High Risk, READY FOR REVIEW, Sprites
