Repository discordia-space/CEV-Eris, pull requests merged in 2019-10, with the labels that each got.

#3889 Fix surgery implant runtime
  code/modules/surgery/implant.dm
Labels: READY FOR REVIEW, runtime error

#3832 Simplify radio chanels defination
  code/modules/mob/living/say.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/mob/say.dm
Labels: QOL, READY FOR REVIEW

#3893 New sprites for conveyors and scrap beacon.
  icons/obj/machines/conveyor.dmi
  icons/obj/structures/scrap/scrap_beacon.dmi
Labels: Sprites

#3904 Add webhook support
  cev_eris.dme
  code/controllers/configuration.dm
  code/modules/webhook/webhook.dm
  code/world.dm
  config/example/config.txt
Labels: READY FOR REVIEW

#3902 Fixing assorted map problems.
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map

#3910 NT focused changes.
  code/datums/outfits/jobs/church.dm
  code/game/jobs/job/church.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/modules/clothing/suits/jobs.dm
  icons/inventory/suit/icon.dmi
  icons/obj/radio.dmi
  maps/CEVEris/_CEV_Eris.dmm
Labels: READY FOR REVIEW

#3930 Rebalancing numbers of tech var all across the codebase.
  code/game/mecha/equipment/tools/tools.dm
  code/modules/mob/holder.dm
  code/modules/projectiles/guns/projectile/automatic/IH_machinepistol.dm
  code/modules/projectiles/guns/projectile/automatic/c20r.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  code/modules/projectiles/guns/projectile/automatic/maxim.dm
  code/modules/projectiles/guns/projectile/automatic/sts35.dm
  code/modules/projectiles/guns/projectile/pistol/clarissa.dm
  code/modules/projectiles/guns/projectile/pistol/silenced.dm
  code/modules/projectiles/guns/projectile/shotgun/combatsg.dm
  code/modules/projectiles/guns/projectile/shotgun/gladstone.dm
  code/modules/projectiles/guns/projectile/sniper.dm
  code/modules/scrap/scrap_burner.dm
Labels: Rebalance

#3931 Rebalancing energy guns.
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/pulse.dm
  code/modules/projectiles/projectile/energy.dm
Labels: Rebalance

#3934 Removing map shims and updating junkyard with smleter and QoL things.
  code/datums/autolathe/biomatter.dm
  code/game/machinery/sorter.dm
  maps/CEVEris/_CEV_Eris.dmm
  maps/CEVEris/centcomm.dmm
  maps/_map_shims.dm
  maps/testmap/test_map.dmm
Labels: Map

#3936 Biomatter material now present in more items.
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/weapons/clown_items.dm
  code/game/objects/items/weapons/cosmetics.dm
  code/game/objects/items/weapons/gift_wrappaper.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/storage/briefcase.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/game/objects/items/weapons/storage/wallets.dm
  code/modules/paperwork/folders.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/photography.dm
  code/modules/reagents/reagent_containers/pill.dm
Labels: Rebalance

#3929 Group litany rework
  code/__DEFINES/misc.dm
  code/datums/mob_stats.dm
  code/modules/core_implant/core_implant.dm
  code/modules/core_implant/cruciform/machinery/obelisk.dm
  code/modules/core_implant/cruciform/rituals/group.dm
  code/modules/core_implant/group_ritual.dm
Labels: Refactoring

#3942 Revert "Vagabonds now can change "name" of his "job""
  code/controllers/subsystems/jobs.dm
  code/datums/outfits/outfit.dm
  code/game/jobs/job/assistant_flavors.dm
  code/game/jobs/job/job.dm
  code/game/objects/items/weapons/cards_ids.dm
Labels: Shitcode

#3948 (Fuck wrong name) reduces Surplus crates price to 2000, changes guns in the crate to 4 from 2.
  code/modules/cargo/packs.dm
Labels: Discussion needed

#3985 Adds 1% transparency pixels to railings for easier climbing.
  icons/obj/railing.dmi
Labels: QOL

#3764 Burst fire define, zoom factor fix, aim code removal.
  code/__DEFINES/weapons.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/automatic/IH_heavy.dm
  code/modules/projectiles/guns/projectile/automatic/IH_machinepistol.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/atreides.dm
  code/modules/projectiles/guns/projectile/automatic/c20r.dm
  code/modules/projectiles/guns/projectile/automatic/dallas.dm
  code/modules/projectiles/guns/projectile/automatic/idaho.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  code/modules/projectiles/guns/projectile/automatic/maxim.dm
  code/modules/projectiles/guns/projectile/automatic/sol.dm
  code/modules/projectiles/guns/projectile/automatic/sts35.dm
  code/modules/projectiles/guns/projectile/automatic/z8.dm
Labels: READY FOR REVIEW
