Repository discordia-space/CEV-Eris, pull requests merged in 2019-04, with the labels that each got.

#3275 Shovel can be modded.
  code/game/objects/items/weapons/tools/mods/mod_types.dm
Labels: Rebalance

#3261 Random loot refactor
  cev_eris.dme
  code/game/gamemodes/events/supply_pod.dm
  code/game/objects/random/ammo.dm
  code/game/objects/random/boxes.dm
  code/game/objects/random/circuitboards.dm
  code/game/objects/random/closet.dm
  code/game/objects/random/cloth.dm
  code/game/objects/random/contraband.dm
  code/game/objects/random/credits.dm
  code/game/objects/random/food.dm
  code/game/objects/random/guns.dm
  code/game/objects/random/junk.dm
  code/game/objects/random/lathe_disks.dm
  code/game/objects/random/mecha.dm
  code/game/objects/random/melee.dm
  code/game/objects/random/mob/slime.dm
  code/game/objects/random/packs.dm
  code/game/objects/random/pouches.dm
  code/game/objects/random/purerandom.dm
  code/game/objects/random/rare.dm
  code/game/objects/random/rig.dm
  code/game/objects/random/scrap.dm
  code/game/objects/random/structures.dm
  code/game/objects/random/themed/astersguild.dm
  code/game/objects/random/tool_mods.dm
  code/game/objects/random/tools.dm
  code/game/objects/random/traps/traps.dm
  code/game/objects/random/voidsuit.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/gimmick.dm
  code/game/objects/structures/crates_lockers/closets/maint_loot.dm
  code/modules/clothing/under/color.dm
  code/modules/scrap/scrap.dm
  code/modules/stashes/stash_datum.dm
  code/modules/stashes/stash_spawner.dm
  code/modules/stashes/stash_types/booze.dm
  code/modules/stashes/stash_types/junk.dm
  icons/misc/landmarks.dmi
  maps/CEVEris/_CEV_Eris.dmm
Labels: Fix, Rebalance, Refactoring

#2608 Tips and tricks
  cev_eris.dme
  code/__defines/subsystems-priority.dm
  code/controllers/subsystems/tips_manager.dm
  code/controllers/subsystems/vote.dm
  code/controllers/subsystems/voting/poll_types.dm
  code/datums/outfits/jobs/security.dm
  code/game/antagonist/antagonist_print.dm
  code/game/antagonist/station/inquisitor.dm
  code/game/antagonist/station/rogue_ai.dm
  code/modules/mob/living/login.dm
  code/modules/mob/observer/ghost/login.dm
  code/modules/tips_and_tricks/gameplay.dm
  code/modules/tips_and_tricks/jobs.dm
  code/modules/tips_and_tricks/mobs.dm
  code/modules/tips_and_tricks/roles.dm
  code/modules/tips_and_tricks/tipsandtricks.dm
Labels: READY FOR REVIEW

#3455 Important fixes
  code/game/objects/items/weapons/cards_ids.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
  code/modules/economy/ATM.dm
  code/modules/economy/Accounts.dm
Labels: Critical

#3454 [TWEAK] Rebalance of agony for stun gameplay
  code/game/objects/items/weapons/stunbaton.dm
  code/modules/clothing/gloves/stungloves.dm
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Rebalance

#3499 Aim stat fixes and renaiming.
  code/__defines/mob_stats.dm
  code/datums/mob_stats.dm
  code/game/antagonist/outer/mercenary/mercenary.dm
  code/game/jobs/job/assistant.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/civilian_chaplain.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/guild.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/security.dm
  code/modules/projectiles/gun.dm
Labels: Fix, Rebalance

#3497 Design tweaks and fixes
  cev_eris.dme
  code/datums/autolathe/ammo.dm
  code/datums/autolathe/autolathe_datums.dm
  code/datums/autolathe/circuits.dm
  code/datums/autolathe/computer_parts.dm
  code/datums/autolathe/devices.dm
  code/datums/autolathe/guns.dm
  code/datums/autolathe/parts.dm
  code/datums/autolathe/security.dm
  code/datums/autolathe/tools.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/autolathe_disk_cloner.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/items/weapons/circuitboards/mecha.dm
  code/game/objects/items/weapons/material/shards.dm
  code/modules/power/smes_construction.dm
  code/modules/research/designs.dm
  code/modules/research/designs/ai_boards.dm
  code/modules/research/designs/cell.dm
  code/modules/research/designs/circuits.dm
  code/modules/research/designs/computer_parts.dm
  code/modules/research/designs/custom_circuits.dm
  code/modules/research/designs/mecha_construction.dm
  code/modules/research/designs/mecha_equipment.dm
  code/modules/research/designs/mining.dm
  code/modules/research/designs/prosthesis_implants.dm
  code/modules/research/designs/robot_parts.dm
  code/modules/research/designs/stock_parts.dm
  code/modules/research/designs/weapon.dm
  code/modules/research/mechfab_designs.dm
  icons/obj/stock_parts.dmi
  nano/templates/autolathe.tmpl
Labels: Fix, NanoUI, Sprites, UI

#3502 Vigilance checks on psy related stuns.
  code/modules/core_implant/cruciform/rituals/crusader.dm
  code/modules/hivemind/machines.dm
Labels: Rebalance
