Repository discordia-space/CEV-Eris, pull requests merged in 2019-11, with the labels that each got.

#4089 Relocate stats output from status to verb
  code/modules/mob/mob.dm
Labels: Bug fixes, Critical, Fix, Important, Priority

#4182 Dungeons, Space Ruins and optimizations.
  cev_eris.dme
  code/__defines/map.dm
  code/controllers/configuration.dm
  code/controllers/subsystems/atoms.dm
  code/controllers/subsystems/machines.dm
  code/game/area/Space Station 13 areas.dm
  code/game/atoms_movable.dm
  code/game/objects/random/packs.dm
  code/game/objects/random/tools.dm
  code/game/objects/structures/burrows.dm
  code/game/objects/structures/crates_lockers/closets/onestar.dm
  code/game/objects/structures/window_spawner.dm
  code/modules/dungeons/crawler/dungeon_gen.dm
  code/modules/dungeons/teleporter.dm
  code/modules/maps/tg/map_template.dm
  code/modules/mob/living/carbon/superior_animal/life.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/support.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_powers.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/mob/living/simple_animal/hostile/doomba.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/onestarboss.dm
  code/modules/mob/living/simple_animal/hostile/onestar_drone.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/multiz/map_data.dm
  code/modules/projectiles/projectile/special.dm
  config/example/config.txt
  icons/mob/build_a_drone.dmi
  maps/dungeons/crawler/crawler.dm
  maps/encounters/spaceruins/spaceruins.dm
  maps/encounters/spaceruins/spaceruins.dmm
Labels: Bug fixes, Fix, Map, Mobs, Multi-z, Rebalance

#4215 Small backstory fix.
  code/datums/setup_option/backgrounds/origin.dm
Labels: Backstory&Lore

#4218 Sanity balance fixes
  code/modules/sanity/breakdowns.dm
Labels: Rebalance

#4222 Sanity sounds
  code/modules/sanity/breakdown.dm
  code/modules/sanity/breakdowns.dm
  sound/sanity/insane.ogg
  sound/sanity/sane.ogg
Labels: Sounds

#4225 Multiple message combining
  code/modules/goonchat/browserassets/js/browserOutput.js
Labels: QOL, Testing required

#4256 Gun refactor
  cev_eris.dme
  code/game/objects/objs.dm
  code/modules/projectiles/_defines.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/dynamic_cursor.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/pulse.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/automatic/IH_heavy.dm
  code/modules/projectiles/guns/projectile/automatic/IH_machinepistol.dm
  code/modules/projectiles/guns/projectile/automatic/IH_smg.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/atreides.dm
  code/modules/projectiles/guns/projectile/automatic/c20r.dm
  code/modules/projectiles/guns/projectile/automatic/dallas.dm
  code/modules/projectiles/guns/projectile/automatic/drozd.dm
  code/modules/projectiles/guns/projectile/automatic/idaho.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  code/modules/projectiles/guns/projectile/automatic/maxim.dm
  code/modules/projectiles/guns/projectile/automatic/sol.dm
  code/modules/projectiles/guns/projectile/automatic/sts35.dm
  code/modules/projectiles/guns/projectile/automatic/vintorez.dm
  code/modules/projectiles/guns/projectile/automatic/z8.dm
  code/modules/projectiles/guns/projectile/boltgun.dm
  code/modules/projectiles/guns/projectile/pistol/IH_sidearm.dm
  code/modules/projectiles/guns/projectile/pistol/clarissa.dm
  code/modules/projectiles/guns/projectile/pistol/colt.dm
  code/modules/projectiles/guns/projectile/pistol/deagle.dm
  code/modules/projectiles/guns/projectile/pistol/giskard.dm
  code/modules/projectiles/guns/projectile/pistol/handmade.dm
  code/modules/projectiles/guns/projectile/pistol/lamia.dm
  code/modules/projectiles/guns/projectile/pistol/mk58.dm
  code/modules/projectiles/guns/projectile/pistol/olivaw.dm
  code/modules/projectiles/guns/projectile/pistol/silenced.dm
  code/modules/projectiles/guns/projectile/revolver/consul.dm
  code/modules/projectiles/guns/projectile/revolver/deckard.dm
  code/modules/projectiles/guns/projectile/revolver/detective.dm
  code/modules/projectiles/guns/projectile/revolver/mateba.dm
  code/modules/projectiles/guns/projectile/revolver/revolver.dm
  code/modules/projectiles/guns/projectile/shotgun/bull.dm
  code/modules/projectiles/guns/projectile/shotgun/combatsg.dm
  code/modules/projectiles/guns/projectile/shotgun/gladstone.dm
  code/modules/projectiles/guns/projectile/shotgun/pump.dm
  code/modules/projectiles/guns/projectile/sniper.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullettypes.dm
Labels: Guns, Refactoring

#4236 Add chat subsystem to prevent client crash on high loads
  cev_eris.dme
  code/__DEFINES/misc.dm
  code/__DEFINES/subsystems-priority.dm
  code/__DEFINES/subsystems.dm
  code/controllers/subsystems/chat.dm
  code/modules/goonchat/browserOutput.dm
Labels: Bug fixes, READY FOR REVIEW

#4249 Dartgun new sprite + minor fix
  code/modules/projectiles/guns/projectile/dartgun.dm
  icons/obj/ammo_mags.dmi
  icons/obj/guns/projectile/dartgun.dmi
Labels: Bug fixes, Guns

#4266 Fixes primary issue with clothing matter initialization.
  code/modules/clothing/clothing.dm
Labels: Bug fixes, Fix, READY FOR REVIEW

#4267 Quick R&D fixes
  code/modules/research/destructive_analyzer.dm
  code/modules/research/rdconsole.dm
  nano/templates/rdconsole.tmpl
Labels: Bug fixes, Fix, NanoUI, READY FOR REVIEW, UI

#4270 Fixes EVERYTHING wrong about Bulldog aka Foxhound aka Pug
  cev_eris.dme
  code/datums/uplink/ammunition.dm
  code/datums/uplink/highly visible and dangerous weapons.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/automatic/bulldog.dm
  code/modules/projectiles/guns/projectile/automatic/pug.dm
  code/modules/projectiles/guns/projectile/automatic/z8.dm
  icons/obj/ammo_mags.dmi
  icons/obj/guns/projectile/bulldog.dmi
  icons/obj/guns/projectile/pug.dmi
Labels: Bug fixes, Fix, Guns, READY FOR REVIEW

#4264 Adds FS Revolver Pack to cargo
  code/modules/cargo/packs.dm
Labels: Discussion needed, Guns, Rebalance

#4272 New PR template.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: QOL, READY FOR REVIEW, enhancement

#4271 Materials in tool mods.
  code/game/objects/items/weapons/tools/crowbars.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/game/objects/items/weapons/tools/pickaxe.dm
  code/game/objects/items/weapons/tools/saws.dm
  code/game/objects/items/weapons/tools/scalpels.dm
  code/game/objects/items/weapons/tools/screwdrivers.dm
  code/game/objects/items/weapons/tools/wirecutters.dm
  code/game/objects/items/weapons/tools/wrenches.dm
Labels: Rebalance

#4269 fixes dual wielding rifles and whatnot
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/crossbow.dm
  code/modules/projectiles/guns/energy/decloner.dm
  code/modules/projectiles/guns/energy/egun.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/guns/energy/toxgun.dm
  code/modules/projectiles/guns/projectile/automatic/IH_machinepistol.dm
  code/modules/projectiles/guns/projectile/automatic/atreides.dm
  code/modules/projectiles/guns/projectile/automatic/drozd.dm
  code/modules/projectiles/guns/projectile/automatic/idaho.dm
  code/modules/projectiles/guns/projectile/pistol/IH_sidearm.dm
  code/modules/projectiles/guns/projectile/pistol/clarissa.dm
  code/modules/projectiles/guns/projectile/pistol/colt.dm
  code/modules/projectiles/guns/projectile/pistol/deagle.dm
  code/modules/projectiles/guns/projectile/pistol/giskard.dm
  code/modules/projectiles/guns/projectile/pistol/gyropistol.dm
  code/modules/projectiles/guns/projectile/pistol/handmade.dm
  code/modules/projectiles/guns/projectile/pistol/lamia.dm
  code/modules/projectiles/guns/projectile/pistol/mk58.dm
  code/modules/projectiles/guns/projectile/pistol/olivaw.dm
  code/modules/projectiles/guns/projectile/pistol/silenced.dm
  code/modules/projectiles/guns/projectile/revolver/revolver.dm
  code/modules/projectiles/guns/projectile/shotgun/sawnoff.dm
Labels: Discussion needed, Guns, READY FOR REVIEW, Rebalance

#4262 Ghost Drag & Drop exploit fix
  code/modules/tables/interactions.dm
Labels: Bug fixes, Priority, READY FOR REVIEW

#4310 Expanded range mode on air scrubbers and vents
  code/ATMOSPHERICS/_atmospherics_helpers.dm
  code/ATMOSPHERICS/components/unary/vent_pump.dm
  code/ATMOSPHERICS/components/unary/vent_scrubber.dm
  code/game/machinery/alarm.dm
  code/game/machinery/embedded_controller/airlock_controllers.dm
  code/game/machinery/embedded_controller/airlock_docking_controller.dm
  code/game/machinery/embedded_controller/airlock_docking_controller_multi.dm
  code/game/machinery/embedded_controller/airlock_program.dm
  code/game/machinery/embedded_controller/simple_docking_controller.dm
  icons/atmos/vent_pump.dmi
  icons/atmos/vent_scrubber.dmi
  nano/templates/air_alarm.tmpl
Labels: ZAS

#4342 Map fixes
  maps/CEVEris/_CEV_Eris.dmm
Labels: Fix, Map
