Repository discordia-space/CEV-Eris, pull requests merged in 2019-07, with the labels that each got.

#3634 nanopaste material cost reduction
  code/game/objects/items/stacks/nanopaste.dm
Labels: READY FOR REVIEW, Rebalance

#3633 [TWEAK] Climbing into delay is now affected by your stat Vigilance
  code/_onclick/other_mobs.dm
  code/datums/mob_stats.dm
  code/game/objects/structures.dm
  code/game/objects/structures/railing.dm
  code/modules/multiz/structures.dm
  code/modules/recycling/disposal.dm
Labels: Minor, READY FOR REVIEW

#3636 burrow rework
  cev_eris.dme
  code/ATMOSPHERICS/atmospherics.dm
  code/ATMOSPHERICS/components/binary_devices/dp_vent_pump.dm
  code/ATMOSPHERICS/components/binary_devices/passive_gate.dm
  code/ATMOSPHERICS/components/binary_devices/pump.dm
  code/ATMOSPHERICS/components/binary_devices/volume_pump.dm
  code/ATMOSPHERICS/components/omni_devices/omni_base.dm
  code/ATMOSPHERICS/components/portables_connector.dm
  code/ATMOSPHERICS/components/trinary_devices/filter.dm
  code/ATMOSPHERICS/components/trinary_devices/mixer.dm
  code/ATMOSPHERICS/components/tvalve.dm
  code/ATMOSPHERICS/components/unary/outlet_injector.dm
  code/ATMOSPHERICS/components/unary/vent_pump.dm
  code/ATMOSPHERICS/components/unary/vent_scrubber.dm
  code/ATMOSPHERICS/components/valve.dm
  code/ATMOSPHERICS/he_pipes.dm
  code/ATMOSPHERICS/mainspipe.dm
  code/ATMOSPHERICS/pipes.dm
  code/__defines/_planes+layers.dm
  code/controllers/subsystems/migration.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/machinery/Beacon.dm
  code/game/machinery/magnet.dm
  code/game/machinery/navbeacon.dm
  code/game/machinery/pipe/construction.dm
  code/game/objects/effects/decals/weldable.dm
  code/game/objects/effects/effect_system.dm
  code/game/objects/items/devices/t_scanner.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/game/objects/items/weapons/grenades/chem_grenade.dm
  code/game/objects/objs.dm
  code/game/objects/structures/burrows.dm
  code/game/turfs/simulated/floor_attackby.dm
  code/game/turfs/simulated/floor_types.dm
  code/game/turfs/turf.dm
  code/modules/multiz/pipes.dm
  code/modules/power/sensors/powernet_sensor.dm
  code/modules/power/terminal.dm
  code/modules/recycling/disposal-construction.dm
  code/modules/recycling/disposal.dm
  code/modules/shield_generators/floor_diffuser.dm
  code/modules/stashes/stash_datum.dm
  icons/obj/burrows.dmi
Labels: Sprites, enhancement

#3642 Bugfix Bonanza
  code/datums/objective/steal.dm
  code/game/objects/items/toys.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/pill.dm
Labels: Backstory&Lore, Bug fixes, Minor, READY FOR REVIEW, enhancement
