Repository discordia-space/CEV-Eris, pull requests merged in 2020-01, with the labels that each got.

#4495 Some map changes
  code/modules/mining/mine_items.dm
  maps/CEVEris/_CEV_Eris.dmm
Labels: Fix, Map

#4407 Wielding Update
  cev_eris.dme
  code/__DEFINES/items_clothing.dm
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/_onclick/item_attack.dm
  code/datums/datum_hud.dm
  code/game/objects/items.dm
  code/game/objects/items/_inventory.dm
  code/game/objects/items/weapons/material/twohanded.dm
  code/game/objects/items/wielding.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/species/species_hud.dm
  code/modules/mob/living/recoil.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/ionrifle.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/pulse.dm
  code/modules/projectiles/guns/projectile/automatic/IH_heavy.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/dallas.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  code/modules/projectiles/guns/projectile/automatic/maxim.dm
  code/modules/projectiles/guns/projectile/automatic/sol.dm
  code/modules/projectiles/guns/projectile/automatic/sts35.dm
  code/modules/projectiles/guns/projectile/automatic/vintorez.dm
  code/modules/projectiles/guns/projectile/boltgun.dm
  code/modules/projectiles/guns/projectile/shotgun/bull.dm
  code/modules/projectiles/guns/projectile/shotgun/combatsg.dm
  code/modules/projectiles/guns/projectile/shotgun/doublebarrel.dm
  code/modules/projectiles/guns/projectile/shotgun/gladstone.dm
  code/modules/projectiles/guns/projectile/shotgun/pug.dm
  code/modules/projectiles/guns/projectile/shotgun/pump.dm
  code/modules/projectiles/guns/projectile/sniper.dm
  icons/mob/screen/ErisStyleHolo.dmi
  icons/obj/guns/energy/cassad.dmi
  icons/obj/guns/energy/iongun.dmi
  icons/obj/guns/energy/lascannon.dmi
  icons/obj/guns/energy/pulse.dmi
  icons/obj/guns/energy/xray.dmi
  icons/obj/guns/projectile/IH_heavyrifle.dmi
  icons/obj/guns/projectile/PeaceWalker.dmi
  icons/obj/guns/projectile/ak.dmi
  icons/obj/guns/projectile/boltgun.dmi
  icons/obj/guns/projectile/cr20.dmi
  icons/obj/guns/projectile/cshotgun.dmi
  icons/obj/guns/projectile/dallas.dmi
  icons/obj/guns/projectile/dartgun.dmi
  icons/obj/guns/projectile/dshotgun.dmi
  icons/obj/guns/projectile/gladstone.dmi
  icons/obj/guns/projectile/heavysniper.dmi
  icons/obj/guns/projectile/l6.dmi
  icons/obj/guns/projectile/maxim.dmi
  icons/obj/guns/projectile/pk.dmi
  icons/obj/guns/projectile/pug.dmi
  icons/obj/guns/projectile/sawnshotgun.dmi
  icons/obj/guns/projectile/shotgun.dmi
  icons/obj/guns/projectile/sol.dmi
  icons/obj/guns/projectile/sts.dmi
  icons/obj/guns/projectile/vintorez.dmi
  interface/skin.dmf
Labels: READY FOR REVIEW

#4512 Serbomat animations fix
  icons/obj/vending.dmi
Labels: READY FOR REVIEW

#4514 Abstract Items Can No Longer Be Given
  code/modules/mob/living/carbon/give.dm
Labels: Fix

#4502 NSA Rewrite (COMPLETE)
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/reagents/metabolism.dm
  code/modules/reagents/reagents.dm
  code/modules/reagents/reagents/medicine.dm
Labels: READY FOR REVIEW

#4511 New Drone Sprites by Shazbot
  code/modules/mob/living/silicon/robot/drone/drone.dm
  code/modules/mob/living/silicon/robot/drone/drone_abilities.dm
  code/modules/mob/living/silicon/robot/robot_items.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  icons/mob/robots.dmi
Labels: READY FOR REVIEW

#4496 More use for Cognition.
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Rebalance

#4513 Performance tweaks 1
  cev_eris.dme
  code/__HELPERS/game.dm
  code/__HELPERS/names.dm
  code/__HELPERS/unsorted.dm
  code/_global_vars/mapping.dm
  code/_global_vars/misc.dm
  code/controllers/evacuation/evacuation.dm
  code/controllers/subsystems/mapping.dm
  code/datums/topic/world.dm
  code/game/area/Space Station 13 areas.dm
  code/game/gamemodes/events/prison_break.dm
  code/game/machinery/bluespaceartillery.dm
  code/game/machinery/computer/prisoner.dm
  code/game/machinery/turret_control.dm
  code/game/objects/items/weapons/implant/implants/death_alarm.dm
  code/modules/mob/observer/ghost/ghost.dm
Labels: Testing required

#4531 fixes wrong name in allowed roles
  code/modules/client/preference_setup/loadout/lists/headwear.dm
Labels: READY FOR REVIEW

#4542 Hopefully fixes #4538
  code/__DEFINES/subsystems.dm
  code/controllers/subsystems.dm
  code/controllers/subsystems/machines.dm
Labels: READY FOR REVIEW

#4539 Adds a limit to the max amount of nanite swarms a kraftwerk roach can create
  code/modules/mob/living/carbon/superior_animal/roach/types/nanites.dm
Labels: Merge only on Monday, READY FOR REVIEW

#4528 Hypersaw
  code/datums/autolathe/tools.dm
  code/game/objects/items/weapons/tools/saws.dm
  code/game/objects/random/tools.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/tools.dmi
Labels: READY FOR REVIEW

#4523 Gun disks
  code/datums/autolathe/ammo.dm
  code/datums/autolathe/guns.dm
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/random/lathe_disks.dm
  code/game/objects/random/techparts.dm
  code/modules/projectiles/ammunition/magazines.dm
  icons/obj/discs.dmi
Labels: Merge only on Monday, READY FOR REVIEW

#4544 Krammerer now has a onsuit sprite
  icons/obj/guns/projectile/shotgun.dmi
Labels: READY FOR REVIEW

#4521 New sprites for hydro, salvageables and laptops
  code/game/machinery/vending.dm
  code/game/objects/random/structures.dm
  code/game/objects/structures/salvageable.dm
  code/modules/client/preference_setup/loadout/lists/utility.dm
  code/modules/hydroponics/seed_machines.dm
  code/modules/hydroponics/trays/tray.dm
  code/modules/modular_computers/computers/subtypes/dev_laptop.dm
  code/modules/modular_computers/computers/subtypes/preset_laptop.dm
  code/modules/modular_computers/file_system/programs/antagonist/revelation.dm
  code/modules/modular_computers/hardware/portable_hard_drive.dm
  code/modules/research/experiment.dm
  icons/obj/hydroponics_machines.dmi
  icons/obj/modular_laptop.dmi
  icons/obj/salvageable.dmi
  sound/machines/shutdown.ogg
Labels: READY FOR REVIEW

#4510 Removes old 2handed item wielding code
  cev_eris.dme
  code/datums/craft/recipes/weapon.dm
  code/game/objects/items/weapons/improvised_components.dm
  code/game/objects/items/weapons/material/bats.dm
  code/game/objects/items/weapons/material/misc.dm
  code/game/objects/items/weapons/material/twohanded.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/game/objects/items/wielding.dm
  code/game/objects/random/tools.dm
  code/game/objects/structures/fireaxe_cabinet.dm
  code/modules/admin/verbs/debug.dm
  code/modules/stashes/stash_types/weapons.dm
Labels: Merge only on Monday, READY FOR REVIEW

#4529 Cortical borer update
  code/modules/ghosttrap/trap.dm
  code/modules/mob/living/simple_animal/borer/borer.dm
  code/modules/mob/living/simple_animal/borer/borer_powers.dm
Labels: Merge only on Monday

#4566 New name and description for AI toolmod.
  code/game/objects/items/weapons/tools/mods/mod_types.dm
Labels: Backstory&Lore, Fix

#4524 update_icon for atoms
  code/game/atoms.dm
  code/game/objects/objs.dm
  code/game/turfs/turf.dm
  code/modules/hivemind/mobs.dm
  code/modules/mob/living/simple_animal/friendly/spiderbot.dm
  code/modules/mob/living/simple_animal/hostile/onestar_drone.dm
  code/modules/mob/living/simple_animal/worm.dm
Labels: Merge only on Monday, READY FOR REVIEW
