Repository discordia-space/CEV-Eris, pull requests merged in 2020-02, with the labels that each got.

#4590 Fixes and tweaks
  cev_eris.dme
  code/game/gamemodes/storyteller_print.dm
  code/game/machinery/autolathe/autolathe.dm
  code/game/objects/items/_inventory.dm
  code/game/objects/items/devices/chameleonproj.dm
  code/game/objects/items/trash.dm
  code/game/objects/items/trash_material.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/material/ashtray.dm
  code/game/objects/random/junk.dm
  code/game/objects/random/purerandom.dm
  code/game/objects/structures/salvageable.dm
  code/game/turfs/initialization/maintenance.dm
  code/game/turfs/simulated/walls.dm
  code/modules/mob/living/silicon/robot/component.dm
  code/modules/mob/living/silicon/robot/drone/drone_items.dm
  code/modules/mob/living/silicon/robot/gripper.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/syndicate.dm
  code/modules/modular_computers/file_system/programs/antagonist/revelation.dm
  maps/CEVEris/_CEV_Eris.dmm
  maps/CEVEris/centcomm.dmm
Labels: READY FOR REVIEW

#4589 Surgery tweaks and fixes
  cev_eris.dme
  code/game/machinery/excelsior/implantmaker.dm
  code/game/objects/structures/salvageable.dm
  code/modules/core_implant/cruciform/cruciform.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/organs/body_modifications.dm
  code/modules/organs/external/_external.dm
  code/modules/organs/external/dismemberment.dm
  code/modules/organs/external/organ_icon.dm
  code/modules/organs/external/stump.dm
  code/modules/organs/external/subtypes/prosthesis.dm
  code/modules/organs/external/subtypes/robotic.dm
  code/modules/organs/external/subtypes/standard.dm
  code/modules/organs/organ_description.dm
  code/modules/research/designs/prosthesis_implants.dm
  code/modules/surgery/internal.dm
  code/modules/surgery/surgery_ui.dm
  icons/mob/human_races/cyberlimbs/bishop.dmi
  icons/mob/human_races/cyberlimbs/generic.dmi
  icons/mob/human_races/cyberlimbs/hesphaistos.dmi
  icons/mob/human_races/cyberlimbs/neotheology.dmi
  icons/mob/human_races/cyberlimbs/xion.dmi
  icons/mob/human_races/cyberlimbs/zenghu.dmi
  icons/mob/human_races/masks/dam_mask_human.dmi
  icons/mob/human_races/masks/dam_mask_monkey.dmi
  icons/mob/human_races/r_human.dmi
  icons/mob/human_races/robotic.dmi
  icons/obj/prosthesis.dmi
Labels: READY FOR REVIEW

#4585 Adds a clothing UI for the user to see held clothing's stats
  code/modules/clothing/clothing.dm
  nano/templates/clothing_stats.tmpl
Labels: READY FOR REVIEW

#4593 Cargo lootbox fix
  code/modules/cargo/packs.dm
Labels: READY FOR REVIEW

#4594 Voidsuit fix
  code/modules/clothing/clothing.dm
  code/modules/clothing/gloves/stungloves.dm
  code/modules/clothing/head/armor.dm
  code/modules/clothing/spacesuits/void/void.dm
Labels: READY FOR REVIEW

#4604 Chat Subsystem
  cev_eris.dme
  code/__DEFINES/misc.dm
  code/__DEFINES/subsystems-priority.dm
  code/__DEFINES/subsystems.dm
  code/__HELPERS/logging.dm
  code/controllers/subsystems/chat.dm
  code/modules/goonchat/browserOutput.dm
Labels: Controllers, READY FOR REVIEW, god forgive us

#4611 Updated Extool DLL
  byond-extools.dll
Labels: READY FOR REVIEW

#4605 sedatives nerf
  code/modules/reagents/reagents/toxins.dm
Labels: READY FOR REVIEW

#4610 [FIX] Stops the infinite admin log while the mech is walking with a riggered cell
  code/modules/power/cell.dm
Labels: READY FOR REVIEW

#4584 Refactors boxes to use a /tg/-like overlay system, changes deferred containers icons for mercenaries.
  code/game/objects/items/bodybag.dm
  code/game/objects/items/trash.dm
  code/game/objects/items/weapons/material/kitchen.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/storage/deferred.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/game/objects/items/weapons/storage/misc.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/modules/detectivework/tools/storage.dm
  code/modules/organs/organ.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/obj/crate.dmi
  icons/obj/food.dmi
  icons/obj/kitchen.dmi
  icons/obj/storage.dmi
  icons/obj/storage/boxes.dmi
  icons/obj/storage/deferred.dmi
  icons/obj/trash.dmi
Labels: READY FOR REVIEW

#4663 Tools Tweaks
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/items/weapons/tools/bonesetters.dm
  code/game/objects/items/weapons/tools/crowbars.dm
  code/game/objects/items/weapons/tools/misc.dm
  code/game/objects/items/weapons/tools/multitool.dm
  code/game/objects/items/weapons/tools/pickaxe.dm
  code/game/objects/items/weapons/tools/saws.dm
  code/game/objects/items/weapons/tools/scalpels.dm
  code/game/objects/items/weapons/tools/screwdrivers.dm
  code/game/objects/items/weapons/tools/shovel.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/game/objects/items/weapons/tools/tape.dm
  code/game/objects/items/weapons/tools/weldingtools.dm
  code/game/objects/items/weapons/tools/wirecutters.dm
  code/game/objects/items/weapons/tools/wrenches.dm
  icons/inventory/back/mob.dmi
  icons/inventory/belt/mob.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/mob/radial/tools.dmi
  icons/obj/weapons.dmi
Labels: READY FOR REVIEW, Rebalance, Tools and stat systems

#4666 Uniform Holsters and NT Belts
  code/datums/autolathe/biomatter.dm
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/random/cloth.dm
  code/game/objects/random/packs.dm
  code/modules/cargo/packs.dm
  code/modules/clothing/accessories/holster.dm
Labels: READY FOR REVIEW
