Repository discordia-space/CEV-Eris, pull requests merged in 2020-04, with the labels that each got.

#4779 Sprite fix for thermoelectric
  icons/obj/machines/thermoelectric.dmi
Labels: Fix, READY FOR REVIEW, Sprites

#4765 Increases robot limb malfunction threshold
  code/modules/organs/external/_external.dm
  code/modules/organs/external/subtypes/robotic.dm
Labels: READY FOR REVIEW

#4754 [FIX] Grab slowdown
  code/modules/mob/mob_grab.dm
Labels: READY FOR REVIEW

#4706 adds wheelchair to utility loadout
  code/modules/client/preference_setup/loadout/lists/utility.dm
Labels: READY FOR REVIEW

#4775 Cryopod fix
  code/datums/contract.dm
  code/game/machinery/cryopod.dm
Labels: READY FOR REVIEW

#4748 Nanite duping fix
  code/game/mecha/equipment/tools/medical_tools.dm
  code/modules/reagents/reagents/nanites.dm
Labels: READY FOR REVIEW, Testing required

#4781 Fixes the broken NSA indicator UI
  code/modules/reagents/metabolism.dm
Labels: READY FOR REVIEW

#4712 New Melee Weapons
  cev_eris.dme
  code/datums/craft/recipes/weapon.dm
  code/datums/outfits/jobs/command.dm
  code/datums/uplink/stealthy and inconspicuous weapons.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/tools/hammer.dm
  code/game/objects/items/weapons/tools/knives.dm
  code/game/objects/items/weapons/tools/pickaxe.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/game/objects/items/weapons/tools/weldingtools.dm
  code/game/objects/random/melee.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_helpers.dm
  code/modules/organs/external/_external.dm
  code/modules/research/designs/weapon.dm
  code/modules/research/nodes/bluespace.dm
  code/modules/research/nodes/combat.dm
  code/modules/surgery/internal.dm
  icons/inventory/back/mob.dmi
  icons/inventory/belt/mob.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/weapons.dmi
Labels: READY FOR REVIEW

#4671 Duffelbags
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/random/cloth.dm
  icons/obj/storage/backpack.dmi
Labels: READY FOR REVIEW

#4794 Adding NT radio encryption key to their disk
  code/datums/autolathe/devices.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/structures/crates_lockers/closets/secure/chaplain.dm
Labels: DO NOT MERGE

#4803 [FIX] Cryopod : Fixed the cause of runtime that breaks the MC ?
  code/game/machinery/cryopod.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
Labels: READY FOR REVIEW

#4766 New disk license point system
  code/game/machinery/autolathe/autolathe.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/modules/modular_computers/file_system/binary/design.dm
  nano/templates/autolathe.tmpl
  nano/templates/autolathe_designs.tmpl
Labels: READY FOR REVIEW

#4802 Adds military satchels to Serbian base
  maps/CEVEris/centcomm.dmm
Labels: READY FOR REVIEW

#4708 Makes changelings real good at self-surgery
  code/modules/surgery/surgery.dm
Labels: READY FOR REVIEW

#4786 Paperwork rework
  code/__HELPERS/text.dm
  code/modules/modular_computers/file_system/programs/generic/wordprocessor.dm
  maps/CEVEris/datums/reports.dm
  nano/images/guild.png
  nano/images/ironhammer.png
Labels: READY FOR REVIEW

#4685 Some map tweaks
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map, READY FOR REVIEW

#4735 Gun disk rebalance (Feedback wellcome)
  code/game/objects/random/guns.dm
  code/game/objects/random/lathe_disks.dm
  code/game/objects/random/packs.dm
  code/game/objects/random/techparts.dm
  code/game/objects/structures/crates_lockers/closets/maint_loot.dm
  code/game/objects/structures/salvageable.dm
Labels: Discussion needed, READY FOR REVIEW

#4753 Hammers Adjustments
  code/datums/craft/recipes/weapon.dm
  code/game/objects/items/weapons/tools/hammer.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/game/objects/items/weapons/tools/wrenches.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/tools.dmi
  icons/obj/weapons.dmi
Labels: READY FOR REVIEW

#4812 Moebius Weapons and Attachments
  code/game/objects/items/weapons/storage/pouches.dm
  code/modules/projectiles/guns/energy/plasma.dm
  code/modules/research/designs/weapon.dm
  code/modules/research/nodes/combat.dm
  icons/obj/guns/energy/brigador.dmi
Labels: READY FOR REVIEW

#4804 Fixes the lack of UI for BST teleport or ghosts leaving corpses.
  code/modules/admin/bluespacetech.dm
  code/modules/mob/observer/ghost/ghost.dm
Labels: Discussion needed, READY FOR REVIEW

#4767 China lake implementation
  cev_eris.dme
  code/game/objects/explosion.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/modules/projectiles/_defines.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/guns/launcher/projectile_grenade_launcher.dm
  code/modules/projectiles/projectile/projectilegrenades.dm
  icons/obj/ammo.dmi
  icons/obj/guns/projectile/chinalake.dmi
  icons/obj/projectiles.dmi
  sound/weapons/guns/fire/grenadelauncher_fire.ogg
Labels: READY FOR REVIEW

#4764 At least 5 players need to be online for serbs to spawn
  code/game/gamemodes/roleset/faction/mercenary.dm
Labels: READY FOR REVIEW, WIP

#4774 Adds the roach-summoning loudmouth grenade
  cev_eris.dme
  code/datums/craft/recipes/weapon.dm
  code/game/objects/items/weapons/grenades/sonic.dm
  icons/obj/grenade.dmi
Labels: READY FOR REVIEW

#4717 Adds RPD (READY FOR REVIEW)
  cev_eris.dme
  code/__DEFINES/construction.dm
  code/datums/autolathe/tools.dm
  code/game/machinery/pipe/construction.dm
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/RPD.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/tools.dmi
Labels: READY FOR REVIEW, Testing required

#4819 Blitzshell fixes
  code/_onclick/cyborg.dm
  code/datums/mind.dm
  code/datums/uplink/devices and tools.dm
  code/modules/mob/living/silicon/robot/drone/blitzshell.dm
  code/modules/mob/living/silicon/robot/robot.dm
Labels: READY FOR REVIEW

#4820 [FIX] Fixes the lack of logging for autopsy
  code/game/objects/effects/spiders.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/structures/medical_stand.dm
  code/modules/biomatter_manipulation/bioreactor/platform.dm
  code/modules/core_implant/cruciform/cruciform.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/living_defense.dm
  code/modules/vehicles/cargo_train.dm
Labels: READY FOR REVIEW
