Repository discordia-space/CEV-Eris, pull requests merged in 2020-12, with the labels that each got.

#5491 General superior animal mob optimization
  code/__DEFINES/components.dm
  code/__HELPERS/global_lists.dm
  code/controllers/subsystems/mapping.dm
  code/controllers/subsystems/processing/mobs.dm
  code/game/atoms_movable.dm
  code/modules/maps/reader.dm
  code/modules/maps/swapmaps.dm
  code/modules/maps/tg/reader.dm
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
  code/modules/mob/living/carbon/superior_animal/roach/life.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/support.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_powers.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/multiz/map_data.dm
  code/world.dm
Labels: READY FOR REVIEW, Testing required

#5460 Re:Cargo fixes
  code/__HELPERS/_lists.dm
  code/controllers/subsystems/trade.dm
  code/game/objects/items/devices/biosyphon.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/turfs/turf.dm
  code/modules/cargo/exports/sheets.dm
  code/modules/cargo/packs.dm
  code/modules/economy/Accounts.dm
  code/modules/economy/price_list.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/roachling.dm
  code/modules/modular_computers/file_system/programs/generic/trade.dm
  code/modules/trade/datums/_trade_station.dm
  code/modules/trade/datums/trade_stations_presets/McRonalds.dm
  code/modules/trade/datums/trade_stations_presets/bluespace_tech.dm
  code/modules/trade/datums/trade_stations_presets/fs_weapon_factory.dm
  code/modules/trade/datums/trade_stations_presets/hellcat.dm
  code/modules/trade/datums/trade_stations_presets/suit_up.dm
  code/modules/trade/machinery/trade_beacon.dm
  icons/obj/storage/boxes.dmi
  maps/CEVEris/_CEV_Eris.dmm
  nano/templates/trade.tmpl
Labels: Map, READY FOR REVIEW

#5446 Gun changes
  code/__DEFINES/weapons.dm
  code/datums/datum_click_handlers.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/recoil.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/gun_firemode.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/crossbow.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/plasma.dm
  code/modules/projectiles/guns/energy/shrapnel.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/atreides.dm
  code/modules/projectiles/guns/projectile/automatic/c20r.dm
  code/modules/projectiles/guns/projectile/automatic/dallas.dm
  code/modules/projectiles/guns/projectile/automatic/drozd.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  code/modules/projectiles/guns/projectile/automatic/molly.dm
  code/modules/projectiles/guns/projectile/automatic/sol.dm
  code/modules/projectiles/guns/projectile/automatic/straylight.dm
  code/modules/projectiles/guns/projectile/automatic/sts35.dm
  code/modules/projectiles/guns/projectile/automatic/vintorez.dm
  code/modules/projectiles/guns/projectile/automatic/wintermute.dm
  code/modules/projectiles/guns/projectile/automatic/z8.dm
  code/modules/projectiles/guns/projectile/automatic/zoric.dm
  code/modules/projectiles/guns/projectile/boltgun.dm
  code/modules/projectiles/guns/projectile/pistol/avasarala.dm
  code/modules/projectiles/guns/projectile/pistol/clarissa.dm
  code/modules/projectiles/guns/projectile/pistol/lamia.dm
  code/modules/projectiles/guns/projectile/pistol/olivaw.dm
  code/modules/projectiles/guns/projectile/pistol/paco.dm
  code/modules/projectiles/guns/projectile/revolver/consul.dm
  code/modules/projectiles/guns/projectile/revolver/deckard.dm
  code/modules/projectiles/guns/projectile/revolver/sky_driver.dm
  code/modules/projectiles/guns/projectile/shotgun/bojevic.dm
  code/modules/projectiles/guns/projectile/shotgun/bull.dm
  code/modules/projectiles/guns/projectile/shotgun/doublebarrel.dm
  code/modules/projectiles/guns/projectile/shotgun/gladstone.dm
  code/modules/projectiles/guns/projectile/shotgun/pump.dm
  code/modules/projectiles/guns/projectile/shotgun/regulator.dm
  code/modules/projectiles/guns/projectile/shotgun/sawnoff.dm
  code/modules/projectiles/guns/projectile/sniper.dm
  code/modules/projectiles/projectile/beams.dm
Labels: READY FOR REVIEW

#5801 Damage reduction
  code/modules/projectiles/guns/energy/crossbow.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/plasma.dm
  code/modules/projectiles/guns/energy/shrapnel.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/atreides.dm
  code/modules/projectiles/guns/projectile/automatic/c20r.dm
  code/modules/projectiles/guns/projectile/automatic/dallas.dm
  code/modules/projectiles/guns/projectile/automatic/sol.dm
  code/modules/projectiles/guns/projectile/automatic/straylight.dm
  code/modules/projectiles/guns/projectile/automatic/vintorez.dm
  code/modules/projectiles/guns/projectile/automatic/wintermute.dm
  code/modules/projectiles/guns/projectile/automatic/z8.dm
  code/modules/projectiles/guns/projectile/automatic/zoric.dm
  code/modules/projectiles/guns/projectile/boltgun.dm
  code/modules/projectiles/guns/projectile/pistol/avasarala.dm
  code/modules/projectiles/guns/projectile/pistol/clarissa.dm
  code/modules/projectiles/guns/projectile/pistol/lamia.dm
  code/modules/projectiles/guns/projectile/pistol/olivaw.dm
  code/modules/projectiles/guns/projectile/pistol/paco.dm
  code/modules/projectiles/guns/projectile/revolver/consul.dm
  code/modules/projectiles/guns/projectile/revolver/deckard.dm
  code/modules/projectiles/guns/projectile/revolver/sky_driver.dm
  code/modules/projectiles/guns/projectile/shotgun/bojevic.dm
  code/modules/projectiles/guns/projectile/shotgun/gladstone.dm
  code/modules/projectiles/guns/projectile/shotgun/regulator.dm
  code/modules/projectiles/guns/projectile/sniper.dm
  code/modules/projectiles/projectile/beams.dm
Labels: READY FOR REVIEW
