Repository discordia-space/CEV-Eris, pull requests merged in 2020-10, with the labels that each got.

#5479 plumbing update: multilayer
  code/__DEFINES/plumbing.dm
  code/datums/craft/recipes/machinery.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/modules/plumbing/ducts.dm
  code/modules/research/nodes/engineering.dm
Labels: READY FOR REVIEW

#5478 Excelsior draft
  code/game/machinery/excelsior/ex_teleporter.dm
  nano/templates/excelsior_teleporter.tmpl
Labels: READY FOR REVIEW

#5535 [BOUNTY] revive proc no longer causes the target to lose their cruciform.
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix, READY FOR REVIEW

#5534 [BOUNTY] Exploit: Fixes people entering mechs while buckled.
  code/modules/mechs/mech_interaction.dm
Labels: Fix, READY FOR REVIEW

#5319 New slotmachine to waste your money
  cev_eris.dme
  code/game/machinery/slotmachine.dm
  code/game/objects/items/weapons/circuitboards/machinery/bar.dm
  icons/obj/machines/slotmachine.dmi
Labels: Map, New features, READY FOR REVIEW, Sprites

#5482 large syringe price change. and typo in tastes, amd Emt plus medical belt changes
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/syringes.dm
Labels: READY FOR REVIEW

#5519 Fixed tables in onestar ruins being labled "onestar" not "onestar table"
  code/modules/tables/presets.dm
Labels: READY FOR REVIEW

#5518 spawn values fix V5
  code/__DEFINES/spawner.dm
  code/game/machinery/newscaster.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/effects/decals/contraband.dm
  code/game/objects/effects/decals/wanted_poster.dm
  code/game/objects/items/devices/powersink.dm
  code/game/objects/items/robot/robot_items.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/weapons/RCD.dm
  code/game/objects/items/weapons/RPD.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/items/weapons/caution.dm
  code/game/objects/items/weapons/handcuffs.dm
  code/game/objects/items/weapons/implant/implanter.dm
  code/game/objects/items/weapons/material/shards.dm
  code/game/objects/items/weapons/power_cells.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/tanks/onestar_regenerator.dm
  code/game/objects/items/weapons/tanks/tank_types.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/game/objects/random/packs.dm
  code/game/objects/random/purerandom.dm
  code/modules/clothing/glasses/powered.dm
  code/modules/clothing/glasses/thermal.dm
  code/modules/clothing/spacesuits/rig/modules/storage.dm
  code/modules/materials/material_sheets.dm
  code/modules/materials/material_synth.dm
  code/modules/mob/living/silicon/robot/robot_items.dm
  code/modules/mob/living/silicon/robot/robot_upgrades.dm
  code/modules/paperwork/folders.dm
  code/modules/paperwork/pen.dm
  code/modules/projectiles/guns/energy/lasertag.dm
  code/modules/projectiles/guns/mods/mods.dm
  code/modules/reagents/reagent_containers/pill.dm
Labels: READY FOR REVIEW

#5523 fixes smoking pipe craft
  code/datums/craft/recipes/misc.dm
Labels: READY FOR REVIEW

#5530 [BOUNTY] Exploit: Fixes some crafting exploits
  code/datums/craft/step.dm
Labels: Fix, READY FOR REVIEW

#5525 Removes poorly-implemented bay animals from the infestation event.
  code/game/gamemodes/events/infestation.dm
Labels: READY FOR REVIEW

#5528 [BOUNTY] QoL: Press E to put in backpack . Press shift + e to put things in your belt
  code/modules/mob/inventory/equip.dm
  code/modules/mob/living/carbon/human/inventory.dm
  interface/interface.dm
  interface/skin.dmf
Labels: QOL, READY FOR REVIEW

#5536 [BOUNTY] Posibrains now give more feedback regarding player eligibility to aspiring ghosts
  code/modules/ghosttrap/trap.dm
  code/modules/mob/living/carbon/brain/posibrain.dm
Labels: Fix, QOL, READY FOR REVIEW

#5529 Fix firemode change that was erasing effects of gunmods
  code/modules/projectiles/gun_firemode.dm
  code/modules/projectiles/guns/energy/plasma.dm
Labels: Fix, READY FOR REVIEW

#5533 [BOUNTY] Bug: fix drag beakers to chem master
  code/modules/reagents/machinery/chem_dispenser.dm
Labels: Fix, READY FOR REVIEW

#5532 [BOUNTY] Bug: Armor message spam
  code/modules/mob/living/living_defense.dm
Labels: Fix, READY FOR REVIEW

#5527 [BOUNTY] Bug: Some items can't be removed from bags
  code/game/objects/items/weapons/trays.dm
  code/game/objects/structures/bedsheet_bin.dm
Labels: Bug fixes, READY FOR REVIEW

#5531 [BOUNTY] Bug: Fix for robotic limbs in biogenerator
  code/modules/biomatter_manipulation/bioreactor/platform.dm
Labels: Fix, READY FOR REVIEW

#5513 Doesn't update the bluespace relay icon when not needed.
  code/game/machinery/bluespacerelay.dm
Labels: READY FOR REVIEW

#5543 [BOUNTY] QoL: Press E to put in backpack . Press shift + e to put things in your belt PART 2
  code/modules/mob/living/carbon/human/inventory.dm
Labels: Fix, god forgive us

#5497 Shields fix
  code/modules/shield_generators/hull.dm
  code/modules/shield_generators/shield_generator.dm
Labels: READY FOR REVIEW

#5505 [ORDERS] Implements random starting areas for the CEV Eris. One of 3 default l…
  code/controllers/configuration.dm
  code/global.dm
  code/modules/overmap/sectors.dm
  config/example/config.txt
  maps/CEVEris/overmap-eris.dm
  maps/encounters/asteroid/asteroid.dm
Labels: READY FOR REVIEW

#5563 You can now replace broken lights by clicking them with a new light
  code/modules/power/lighting.dm
Labels: QOL

#5524 Ladder peeking and grenade throwing
  code/game/objects/items/weapons/grenades/grenade.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/multiz/structures.dm
Labels: READY FOR REVIEW

#5558 [BOUNTY] BUG: Prescription glasses don't work
  code/modules/clothing/glasses/misc.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
Labels: Fix

#5574 biomes and trash rework.
  cev_eris.dme
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/spawner.dm
  code/datums/loot_spawner.dm
  code/game/atoms_movable.dm
  code/game/gamemodes/events/hidden_events/kaiser.dm
  code/game/machinery/computer/message.dm
  code/game/objects/effects/decals/Cleanable/misc.dm
  code/game/objects/items/devices/mental_imprinter.dm
  code/game/objects/items/devices/traitordevices.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/trash_material.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/power_cells.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/items/weapons/storage/internal.dm
  code/game/objects/landmarks/landmark.dm
  code/game/objects/random/biomes/biome.dm
  code/game/objects/random/biomes/biomes.dm
  code/game/objects/random/mob/mobs.dm
  code/game/objects/random/mob/slime.dm
  code/game/objects/random/packs.dm
  code/game/objects/random/purerandom.dm
  code/game/objects/random/spawner.dm
  code/game/objects/random/traps/traps.dm
  code/game/objects/random/voidsuit.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/soft_caps.dm
  code/modules/clothing/spacesuits/rig/modules/computer.dm
  code/modules/clothing/spacesuits/rig/modules/utility.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/core_implant/cruciform/machinery/obelisk.dm
  code/modules/dungeons/teleporter.dm
  code/modules/economy/cash.dm
  code/modules/integrated/integrated_electronics/core/assemblies.dm
  code/modules/mechs/equipment/utility.dm
  code/modules/mining/ore.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/tank.dm
  code/modules/mob/living/simple_animal/hostile/doomba.dm
  code/modules/mob/living/simple_animal/spider_core.dm
  code/modules/multiz/turf.dm
  code/modules/paperwork/paper.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/scrap/scrap.dm
  code/modules/scrap/scrap_beacon.dm
  code/modules/scrap/scrap_pileripper.dm
  icons/misc/landmarks.dmi
  maps/submaps/deepmaint_rooms/core/ai_core.dmm
  maps/submaps/deepmaint_rooms/core/archive.dmm
  maps/submaps/deepmaint_rooms/core/maint_asteroid.dmm
  maps/submaps/deepmaint_rooms/core/podbay.dmm
  maps/submaps/deepmaint_rooms/core/vault.dmm
  maps/submaps/deepmaint_rooms/normal/mechbay.dmm
  maps/submaps/deepmaint_rooms/normal/roach.dmm
  maps/submaps/deepmaint_rooms/normal/toilet.dmm
Labels: READY FOR REVIEW, Testing required

#5257 [READY] Bluespace entropy
  cev_eris.dme
  code/__HELPERS/bluespace_entropy.dm
  code/__HELPERS/turfs.dm
  code/datums/helper_datums/teleport.dm
  code/datums/objective/individual_objective/technomancers.dm
  code/datums/uplink/uplink_items.dm
  code/game/machinery/excelsior/ex_teleporter.dm
  code/game/machinery/teleporter.dm
  code/game/objects/effects/portals.dm
  code/game/objects/items/oddities.dm
  code/game/objects/items/weapons/space_harpoon.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/game/objects/items/weapons/teleportation.dm
  code/game/objects/items/weapons/tools/knives.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/game/objects/structures/beacon.dm
  code/game/objects/structures/bluespace_crystal_structure.dm
  code/game/objects/structures/omnius.dm
  code/modules/bs_snare/machinery.dm
  code/modules/clothing/spacesuits/rig/modules/ninja.dm
  code/modules/clothing/suits/armor.dm
  code/modules/dungeons/teleporter.dm
  code/modules/hivemind/self_defense.dm
  code/modules/hydroponics/seed.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/bluespace.dm
  code/modules/mob/living/simple_animal/hostile/stranger.dm
  code/modules/telesci/bcrystal.dm
  code/modules/telesci/telepads.dm
  code/modules/telesci/telesci_computer.dm
  icons/mob/animal.dmi
  icons/mob/mob.dmi
  icons/mob/screen/gun_actions.dmi
  icons/obj/guns/energy/lancer.dmi
  icons/obj/oddities.dmi
Labels: DO NOT MERGE, New features, New sprites needed
