Repository discordia-space/CEV-Eris, pull requests merged in 2020-09, with the labels that each got.

#5299 disposable NT sidearm
  code/datums/autolathe/biomatter.dm
  code/datums/autolathe/guns.dm
  code/game/machinery/recharger.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/items/weapons/power_cells.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/plasma.dm
  code/modules/projectiles/projectile/plasma.dm
  icons/obj/guns/energy/martyr.dmi
  icons/obj/power_cells.dmi
Labels: New features, Sprites

#5391 New Litany: Cruciform sense
  code/modules/core_implant/cruciform/rituals/base.dm
Labels: READY FOR REVIEW

#5415 Admin Chem Dispenser update and touchup
  code/modules/reagents/machinery/chem_dispenser.dm
Labels: Admin, READY FOR REVIEW

#5407 Adds and re-arranges NT clothes and product disk designs into two separate disks
  code/datums/autolathe/biomatter.dm
  code/datums/autolathe/devices.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/items/weapons/grenades/chem_grenade.dm
  code/modules/clothing/spacesuits/void/neotheology.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/under/jobs/civilian.dm
Labels: READY FOR REVIEW

#5426 [Porting] Initial TG Garbage porting
  code/__DEFINES/components.dm
  code/__DEFINES/qdel.dm
  code/__DEFINES/subsystems.dm
  code/__HELPERS/logging.dm
  code/controllers/subsystems/garbage.dm
Labels: Controllers, Critical, Fix, High Risk, Optimization, Porting, READY FOR REVIEW

#5435 Neotheo QOL Tweaks
  code/modules/core_implant/cruciform/rituals/base.dm
  code/modules/core_implant/cruciform/rituals/inquisitor.dm
Labels: READY FOR REVIEW, Rebalance

#5400 Traitor Items Update
  cev_eris.dme
  code/__DEFINES/items.dm
  code/datums/autolathe/security.dm
  code/datums/uplink/announcements.dm
  code/datums/uplink/badassery.dm
  code/datums/uplink/devices and tools.dm
  code/datums/uplink/hardsuit_modules.dm
  code/datums/uplink/highly visible and dangerous weapons.dm
  code/datums/uplink/implants.dm
  code/datums/uplink/medical.dm
  code/datums/uplink/stealth and camouflage items.dm
  code/game/objects/items/devices/organ_module/active/armblades.dm
  code/game/objects/items/devices/techno_tribalism.dm
  code/game/objects/items/devices/uplink_random_lists.dm
  code/game/objects/items/weapons/melee/energy.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/storage/case.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
  code/game/objects/random/gun_upgrade.dm
  code/game/turfs/flooring/flooring_premade.dmgases.dm
  code/modules/clothing/head/mindreader.dm
  code/modules/projectiles/effects.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/mods/mods.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/sanity/breakdown.dm
  icons/effects/projectiles.dmi
  icons/inventory/feet/icon.dmi
  icons/inventory/feet/mob.dmi
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/mob/rig_back.dmi
  icons/obj/food.dmi
  icons/obj/guns/energy/psychiccannon.dmi
  icons/obj/guns/mods.dmi
  icons/obj/light_overlays.dmi
  icons/obj/projectiles.dmi
  icons/obj/rig_modules.dmi
  icons/obj/storage.dmi
  icons/obj/surgery.dmi
  nano/templates/autodoc.tmpl
Labels: Antags, New features, READY FOR REVIEW

#5293 flavors added to foods and drinks DM, and taste for reagents organics. and ethanol
  code/__DEFINES/sanity.dm
  code/game/machinery/vending.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagents.dm
  code/modules/reagents/reagents/dispenser.dm
  code/modules/reagents/reagents/food-Drinks.dm
  code/modules/sanity/sanity_mob.dm
Labels: QOL, READY FOR REVIEW, Rebalance

#5428 [Porting] Updating GC with one new debug verb from tg and minor change to file logging
  code/__HELPERS/logging.dm
  code/controllers/master.dm
  code/controllers/subsystems.dm
  code/controllers/subsystems/garbage.dm
  code/modules/admin/verbs/debug.dm
Labels: Controllers, Porting, READY FOR REVIEW

#5457 You can now compile and run the codebase through VS code or extools without errors on start.
  code/modules/mechs/mech.dm
  code/modules/xgm/xgm_gas_mixture.dm
Labels: READY FOR REVIEW

#5470 [BALANCE] Increases the custodial module speed from 0.85 to 1.0
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Mobs, READY FOR REVIEW, Rebalance

#5454 Introduce Moebius voidsuit
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/research/designs.dm
  code/modules/research/nodes/combat.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  nano/css/shared.css
  nano/images/science.png
Labels: READY FOR REVIEW, Sprites

#5483 maps drying rack to NT garden, and public garden
  code/datums/craft/recipes/misc.dm
  code/game/machinery/kitchen/smartfridge.dm
  maps/CEVEris/_CEV_Eris.dmm
Labels: READY FOR REVIEW
