Repository discordia-space/CEV-Eris, pull requests merged in 2020-08, with the labels that each got.

#5041 New cigs cartons
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/game/objects/random/purerandom.dm
  code/modules/cargo/packs.dm
  icons/obj/cigarettes.dmi
Labels: READY FOR REVIEW, Sprites

#5098 Sanity rework vol2
  code/__DEFINES/components.dm
  code/__DEFINES/sanity.dm
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/game/machinery/kitchen/smartfridge.dm
  code/game/objects/random/cloth.dm
  code/modules/client/preference_setup/loadout/lists/headwear.dm
  code/modules/client/preference_setup/loadout/lists/uniforms.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/glasses/misc.dm
  code/modules/clothing/head/armor.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/masks/breath.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/clothing/spacesuits/breaches.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/bio.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/color.dm
  code/modules/clothing/under/jobs/medsci.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/living_defense.dm
  code/modules/modular_computers/file_system/catalog.dm
  code/modules/modular_computers/file_system/programs/medical/chem_catalog.dm
  code/modules/organs/organ.dm
  code/modules/reagents/reagent_containers/food.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
  code/modules/reagents/reagents/dispenser.dm
  code/modules/reagents/reagents/food-Drinks.dm
  code/modules/sanity/breakdown.dm
  code/modules/sanity/breakdowns.dm
  code/modules/sanity/sanity_mob.dm
  nano/images/desire.png
  nano/images/gangnam_style.png
  nano/images/insight.png
  nano/images/sanity.png
  nano/templates/catalog_entry_drink.tmpl
  nano/templates/sanity.tmpl
  sound/sanity/psychochimes.ogg
  sound/sanity/rest.ogg
Labels: READY FOR REVIEW, Testing required

#5286 Farmbot fixes
  code/modules/mob/living/bot/farmbot.dm
  icons/obj/aibots.dmi
Labels: READY FOR REVIEW

#5328 Datum armor and prosthetic protection
  cev_eris.dme
  code/datums/armor.dm
  code/datums/autolathe/prostheses.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/items/weapons/storage/deferred.dm
  code/game/objects/random/cloth.dm
  code/game/objects/random/packs.dm
  code/game/objects/random/prosthesis.dm
  code/game/objects/structures/salvageable.dm
  code/modules/biomatter_manipulation/toxic_biomass.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/gloves/boxing.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/shoes/jobs.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/mechs/components/armour.dm
  code/modules/mechs/mech_damage.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/organs/body_modifications.dm
  code/modules/organs/external/subtypes/robotic.dm
  code/modules/organs/external/subtypes/robotic_types.dm
  code/modules/research/designs/prosthesis_implants.dm
  code/modules/research/nodes/biotech.dm
  code/modules/scrap/oldificator.dm
  code/modules/virus2/helpers.dm
  icons/mob/human_races/cyberlimbs/asters.dmi
  icons/mob/human_races/cyberlimbs/bishop.dmi
  icons/mob/human_races/cyberlimbs/excelsior.dmi
  icons/mob/human_races/cyberlimbs/frozen_star.dmi
  icons/mob/human_races/cyberlimbs/hesphaistos.dmi
  icons/mob/human_races/cyberlimbs/moebius.dmi
  icons/mob/human_races/cyberlimbs/one_star.dmi
  icons/mob/human_races/cyberlimbs/serbian.dmi
  icons/mob/human_races/cyberlimbs/technomancer.dmi
  icons/mob/human_races/cyberlimbs/xion.dmi
  icons/mob/human_races/cyberlimbs/zenghu.dmi
Labels: READY FOR REVIEW

#5382 Fix trashbag matter since without that you can construct it for free
  code/game/objects/items/weapons/storage/bags.dm
Labels: READY FOR REVIEW

#5394 Fix booster and injector toolmods
  code/game/objects/items/weapons/tools/mods/mod_types.dm
Labels: Fix, READY FOR REVIEW

#5383 Dead cat fix
  code/modules/mob/living/simple_animal/friendly/cat.dm
  icons/mob/items/lefthand_holder.dmi
  icons/mob/items/righthand_holder.dmi
Labels: READY FOR REVIEW

#5342 Fixes the holodeck
  code/modules/holodeck/HolodeckControl.dm
Labels: Fix, READY FOR REVIEW

#5341 Climbing down onto the tables from another z-level.
  code/modules/multiz/turf.dm
Labels: New features, QOL, READY FOR REVIEW

#5367 [Order] Fix large grenades not exploding
  code/game/objects/items/weapons/grenades/chem_grenade.dm
Labels: READY FOR REVIEW

#5406 Fixes a mistake I did when datumizing admin topic
  code/modules/admin/topic.dm
Labels: READY FOR REVIEW

#5317 Fixed typos for Damp Rag smothering actions
  code/modules/detectivework/tools/rag.dm
Labels: Fix

#5412 Breeding spider bugfix
  code/game/objects/items/weapons/implant/implants/carrion/breeding_spider.dm
Labels: Bug fixes

#5366 Teleporter changes
  code/game/machinery/teleporter.dm
  code/game/objects/items/weapons/circuitboards/machinery/research.dm
  code/modules/research/designs/circuits.dm
  code/modules/research/nodes/bluespace.dm
  code/modules/telesci/bcrystal.dm
Labels: READY FOR REVIEW

#5409 Lowers slowdown on Captain Armor to default voidsuit value
  code/modules/clothing/spacesuits/captain.dm
Labels: Discussion needed, READY FOR REVIEW
