Repository discordia-space/CEV-Eris, pull requests merged in 2020-07, with the labels that each got.

#5064 fix random job preference.
  code/controllers/subsystems/jobs.dm
Labels: Bug fixes

#5062 fix lowborn and absolute grab perks
  code/_onclick/click.dm
  code/_onclick/other_mobs.dm
  code/datums/setup_option/backgrounds/fate.dm
Labels: Bug fixes

#5060 fix(gulp_whole): validate ghost before gulp
  code/modules/reagents/reagent_containers/food/drinks.dm
Labels: Bug fixes

#5061 fix(frozen_star | designs & disk_name)
  code/game/objects/items/weapons/autolathe_disks.dm
Labels: Bug fixes

#5029 search players in DB
  cev_eris.dme
  code/datums/topic/admin.dm
  code/global.dm
  code/modules/admin/DB_search/search.dm
  code/modules/admin/verbs/antiraid.dm
  code/modules/client/asset_cache.dm
  code/modules/client/client procs.dm
  schema.sql
Labels: Admin, DB, READY FOR REVIEW

#5074 utf-8 two-byte russian chars hotfix
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/modules/mob/living/say.dm
  code/modules/mob/say.dm
Labels: Optimization

#5084 Gun rebalance
  cev_eris.dme
  code/datums/autolathe/guns.dm
  code/game/machinery/vending.dm
  code/game/objects/items/devices/flash.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/random/gun_upgrade.dm
  code/game/objects/random/guns.dm
  code/game/objects/random/packs.dm
  code/modules/projectiles/guns/energy/shrapnel.dm
  code/modules/projectiles/guns/projectile/automatic/dallas.dm
  code/modules/projectiles/guns/projectile/automatic/sol.dm
  code/modules/projectiles/guns/projectile/automatic/sts35.dm
  code/modules/projectiles/guns/projectile/boltgun.dm
  code/modules/projectiles/guns/projectile/pistol/giskard.dm
  code/modules/projectiles/guns/projectile/pistol/lamia.dm
  code/modules/projectiles/guns/projectile/pistol/mandella.dm
  code/modules/projectiles/guns/projectile/pistol/mk58.dm
  code/modules/projectiles/guns/projectile/pistol/olivaw.dm
  code/modules/projectiles/guns/projectile/pistol/paco.dm
  code/modules/projectiles/guns/projectile/revolver/consul.dm
  code/modules/projectiles/guns/projectile/revolver/deckard.dm
  code/modules/projectiles/guns/projectile/revolver/havelock.dm
  code/modules/projectiles/guns/projectile/shotgun/bojevic.dm
  code/modules/projectiles/guns/projectile/shotgun/bull.dm
  code/modules/projectiles/guns/projectile/shotgun/doublebarrel.dm
  code/modules/projectiles/guns/projectile/shotgun/gladstone.dm
  code/modules/projectiles/guns/projectile/shotgun/pump.dm
  code/modules/projectiles/guns/projectile/shotgun/regulator.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullettypes.dm
  code/modules/reagents/reagent_containers/spray.dm
Labels: READY FOR REVIEW, Rebalance

#5065 Faction items update
  cev_eris.dme
  code/datums/objective/steal.dm
  code/datums/perks/job.dm
  code/game/jobs/job/captain.dm
  code/game/objects/items/complicator.dm
  code/game/objects/items/devices/last_shelter.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/devices/techno_tribalism.dm
  code/game/objects/items/oddities.dm
  code/game/objects/items/weapons/maneki_neko.dm
  code/game/objects/items/weapons/sword_of_truth.dm
  code/game/objects/structures/crates_lockers/closets/secure/chaplain.dm
  code/modules/core_implant/cruciform/machinery/cloning.dm
  code/modules/core_implant/cruciform/modules.dm
  code/modules/reagents/atomic_distillery.dm
  code/modules/reagents/reagents/dispenser.dm
  code/modules/reagents/reagents/food-Drinks.dm
  icons/inventory/belt/mob.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/faction_item.dmi
  icons/obj/oddities.dmi
  maps/CEVEris/_CEV_Eris.dmm
Labels: New features, READY FOR REVIEW
