Repository discordia-space/CEV-Eris, pull requests merged in 2020-05, with the labels that each got.

#4854 More compact crafting menu by grouping variations of the same item
  code/__DEFINES/craft.dm
  code/datums/craft/menu.dm
  code/datums/craft/recipe.dm
  code/datums/craft/recipes/airlocks.dm
  code/datums/craft/recipes/floor.dm
  code/datums/craft/recipes/furniture.dm
  code/datums/craft/recipes/misc.dm
Labels: READY FOR REVIEW

#4838 Adding more Oberthian flavor with german language
  cev_eris.dme
  code/__DEFINES/species_languages.dm
  code/datums/setup_option/backgrounds/origin.dm
  code/modules/goonchat/browserassets/css/browserOutput_override.css
  code/modules/mob/language/german.dm
  code/stylesheet.dm
  config/names/first_female_german.txt
  config/names/first_male_german.txt
  config/names/last_german.txt
Labels: READY FOR REVIEW

#4853 rework hydro to less frustrating
  cev_eris.dme
  code/modules/hydroponics/hydrochems/medicinalplants.dm
  code/modules/hydroponics/seed_controller.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/trays/tray.dm
  code/modules/hydroponics/trays/tray_process.dm
  code/modules/mob/living/carbon/superior_animal/roach/attack.dm
  code/modules/mob/living/carbon/superior_animal/roach/riding.dm
  maps/CEVEris/_CEV_Eris.dmm
Labels: DO NOT MERGE

#4850 Fix cyborgs not being able to pick up stuff (ores, sheets, ...)
  code/_onclick/cyborg.dm
Labels: READY FOR REVIEW

#4852 New way to define in which direction a craft should be spawned
  code/__DEFINES/craft.dm
  code/datums/craft/recipe.dm
  code/datums/craft/recipes/machinery.dm
Labels: READY FOR REVIEW

#4855 Changed how the radio prefix is read irregardless of capitlization used
  code/modules/mob/say.dm
Labels: Discussion needed, READY FOR REVIEW

#4924 Slime grenades
  code/game/objects/items/weapons/grenades/anti_photon_grenade.dm
  code/game/objects/items/weapons/grenades/chem_grenade.dm
  code/game/objects/items/weapons/grenades/flashbang.dm
  code/game/objects/items/weapons/grenades/smokebomb.dm
  code/game/objects/items/weapons/grenades/sonic.dm
Labels: Chemistry, Merge only on Monday, READY FOR REVIEW

#4923 Fixes the blitzshell showing up on manifest
  code/modules/mob/living/silicon/robot/drone/blitzshell.dm
Labels: Bug fixes, Merge only on Monday, READY FOR REVIEW

#4919 less .charge, more .give
  code/game/machinery/floodlight.dm
  code/game/machinery/rechargestation.dm
  code/game/objects/items/devices/lighting/toggleable/flashlight.dm
  code/game/objects/items/devices/megaphone.dm
  code/game/objects/items/devices/scanners/scanners.dm
  code/game/objects/items/devices/suit_cooling.dm
  code/game/objects/items/devices/t_scanner.dm
  code/game/objects/items/weapons/RPD.dm
  code/game/objects/items/weapons/RSF.dm
  code/game/objects/items/weapons/space_harpoon.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/items/weapons/teleportation.dm
  code/game/objects/structures/watercloset.dm
  code/modules/clothing/glasses/powered.dm
  code/modules/clothing/gloves/stungloves.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/integrated/integrated_electronics/subtypes/power.dm
  code/modules/mechs/interface/screen_objects.dm
  code/modules/mining/drilling/drill.dm
  code/modules/mob/living/silicon/ai/life.dm
  code/modules/mob/living/silicon/ai/login.dm
  code/modules/mob/living/silicon/ai/logout.dm
  code/modules/mob/living/silicon/robot/analyzer.dm
  code/modules/mob/living/silicon/robot/photos.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_damage.dm
  code/modules/mob/living/silicon/robot/robot_parts.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/friendly/spiderbot.dm
  code/modules/modular_computers/computers/modular_computer/power.dm
  code/modules/nano/interaction/base.dm
  code/modules/power/apc.dm
  code/modules/power/cell.dm
  code/modules/power/power.dm
  code/modules/power/smes.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/launcher/crossbow.dm
  code/modules/reagents/machinery/electrolyzer.dm
  code/modules/reagents/reagent_containers/borghydro.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_cellcharge.dm
  code/modules/vehicles/cargo_train.dm
Labels: Bug fixes, Merge only on Monday, READY FOR REVIEW

#4909 Port various antiraid/antigrief measures
  cev_eris.dme
  code/controllers/configuration.dm
  code/modules/admin/admin_ranks.dm
  code/modules/admin/verbs/antiraid.dm
  code/modules/client/client procs.dm
  code/modules/client/client_defines.dm
  config/example/config.txt
Labels: Admin, Merge only on Monday, READY FOR REVIEW

#4908 [MAP] New destinations for merc shuttle
  maps/CEVEris/_CEV_Eris.dmm
  maps/CEVEris/shuttles-eris.dm
Labels: Merge only on Monday, READY FOR REVIEW

#4926 Homewrecker fits on back and belt. Does 26 damage when wielded.
  code/game/objects/items/weapons/tools/hammer.dm
Labels: Merge only on Monday, READY FOR REVIEW, Rebalance, Tools and stat systems

#4925 Adjusts burrow migrations
  code/controllers/subsystems/migration.dm
Labels: READY FOR REVIEW, Rebalance

#4886 Toriate's portable freezers
  code/datums/autolathe/containers.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/game/objects/random/food.dm
  code/game/objects/random/purerandom.dm
  maps/CEVEris/_CEV_Eris.dmm
Labels: READY FOR REVIEW

#4933 Tweak roach and spider behavior with windows
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Labels: READY FOR REVIEW

#4928 option "send back to lobby"
  code/datums/topic/admin.dm
  code/datums/topic/topic_handlers.dm
  code/modules/admin/admin.dm
Labels: Admin, READY FOR REVIEW

#4882 Fixes the runtime with floor sound
  code/game/turfs/turf.dm
Labels: READY FOR REVIEW
