Repository discordia-space/CEV-Eris, pull requests merged in 2020-03, with the labels that each got.

#4673 Adds a chemial recipe for nicotine.
  code/modules/reagents/recipes.dm
Labels: READY FOR REVIEW

#4684 Autolathes on the map are now preloaded with materials
  code/game/machinery/autolathe/autolathe.dm
  code/game/machinery/autolathe/mechfab.dm
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map, READY FOR REVIEW

#4679 Hammer mods
  code/__DEFINES/weapons.dm
  code/datums/craft/recipes/tools.dm
  code/game/objects/items/weapons/tools/hammer.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/game/objects/random/tool_mods.dm
  icons/obj/tool_upgrades.dmi
  icons/obj/tools.dmi
Labels: Tools and stat systems

#4674 Cig fix, now every 10 seconds
  code/game/objects/items/weapons/cigs_lighters.dm
Labels: READY FOR REVIEW

#4689 Laser Sabre
  code/datums/craft/recipes/weapon.dm
  code/game/objects/items/weapons/melee/energy.dm
Labels: Crafting, READY FOR REVIEW

#4680 MPC features, fixes, improvements
  cev_eris.dme
  code/controllers/subsystems/jobs.dm
  code/datums/outfits/jobs/science.dm
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/items/weapons/power_cells.dm
  code/game/objects/structures/salvageable.dm
  code/modules/assembly/signaler.dm
  code/modules/integrated/integrated_electronics/subtypes/input_output.dm
  code/modules/mob/living/silicon/pai/software_modules.dm
  code/modules/modular_computers/NTNet/NTNet.dm
  code/modules/modular_computers/NTNet/emails/email_account.dm
  code/modules/modular_computers/NTNet/emails/email_message.dm
  code/modules/modular_computers/computers/modular_computer/core.dm
  code/modules/modular_computers/computers/modular_computer/hardware.dm
  code/modules/modular_computers/computers/modular_computer/interaction.dm
  code/modules/modular_computers/computers/modular_computer/power.dm
  code/modules/modular_computers/computers/modular_computer/ui.dm
  code/modules/modular_computers/computers/modular_computer/variables.dm
  code/modules/modular_computers/computers/subtypes/dev_laptop.dm
  code/modules/modular_computers/computers/subtypes/dev_pda.dm
  code/modules/modular_computers/computers/subtypes/preset_laptop.dm
  code/modules/modular_computers/computers/subtypes/preset_pda.dm
  code/modules/modular_computers/file_system/computer_file.dm
  code/modules/modular_computers/file_system/program.dm
  code/modules/modular_computers/file_system/program_events.dm
  code/modules/modular_computers/file_system/programs/antagonist/access_decrypter.dm
  code/modules/modular_computers/file_system/programs/antagonist/dos.dm
  code/modules/modular_computers/file_system/programs/antagonist/revelation.dm
  code/modules/modular_computers/file_system/programs/generic/audio_player.dm
  code/modules/modular_computers/file_system/programs/generic/bounty_board.dm
  code/modules/modular_computers/file_system/programs/generic/email_client.dm
  code/modules/modular_computers/file_system/programs/generic/news_browser.dm
  code/modules/modular_computers/file_system/programs/generic/ntdownloader.dm
  code/modules/modular_computers/file_system/programs/generic/ntnrc_client.dm
  code/modules/modular_computers/file_system/programs/generic/nttransfer.dm
  code/modules/modular_computers/file_system/programs/generic/signaller.dm
  code/modules/modular_computers/file_system/reports/bounty_entry.dm
  code/modules/modular_computers/hardware/hard_drive.dm
  code/modules/modular_computers/hardware/led.dm
  code/modules/modular_computers/hardware/network_card.dm
  code/modules/modular_computers/hardware/processor_unit.dm
  code/modules/nano/interaction/base.dm
  code/modules/nano/modules/nano_module.dm
  code/modules/nano/nanoui.dm
  code/modules/research/designs/computer_parts.dm
  icons/obj/modular_components.dmi
  icons/obj/modular_laptop.dmi
  nano/css/shared.css
  nano/templates/mpc_mainscreen.tmpl
  nano/templates/mpc_signaller.tmpl
Labels: Bug fixes, Modular computers, QOL, READY FOR REVIEW, Refactoring, Testing required

#4675 You can now clean the internal components of rigs
  code/game/machinery/washing_machine.dm
  code/game/objects/items.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/scrap/oldificator.dm
Labels: READY FOR REVIEW, Testing required

#4687 The RPG wielding fix
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile/other/RPG.dm
Labels: Fix, READY FOR REVIEW, Rebalance

#4690 Minor grammar, spelling, and localization fixes.
  code/game/objects/items/oddities.dm
Labels: READY FOR REVIEW

#4696 [FIX] Uplink and Shield program
  code/modules/modular_computers/file_system/programs/antagonist/uplink.dm
  code/modules/modular_computers/file_system/programs/engineering/shield_control.dm
Labels: Fix, High priority issue, READY FOR REVIEW

#4693 Explosive damage changes
  cev_eris.dme
  code/game/objects/explosion.dm
  code/game/objects/items/weapons/grenades/explosive.dm
  code/game/objects/items/weapons/grenades/frag.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/storage/deferred.dm
  code/modules/mob/living/carbon/human/human.dm
  maps/testmap/test_map.dmm
Labels: Fix, READY FOR REVIEW, Rebalance, Refactoring, enhancement

#4683 Plasma guns fix and rebalance
  code/modules/projectiles/guns/energy/plasma.dm
  code/modules/projectiles/projectile/plasma.dm
Labels: Guns, READY FOR REVIEW, Rebalance

#4722 Gun Two-Handed Stuff
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/atreides.dm
  code/modules/projectiles/guns/projectile/automatic/c20r.dm
  code/modules/projectiles/guns/projectile/automatic/dallas.dm
  code/modules/projectiles/guns/projectile/automatic/drozd.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  code/modules/projectiles/guns/projectile/automatic/maxim.dm
  code/modules/projectiles/guns/projectile/automatic/molly.dm
  code/modules/projectiles/guns/projectile/automatic/sol.dm
  code/modules/projectiles/guns/projectile/automatic/straylight.dm
  code/modules/projectiles/guns/projectile/automatic/sts35.dm
  code/modules/projectiles/guns/projectile/automatic/vintorez.dm
  code/modules/projectiles/guns/projectile/automatic/wintermute.dm
  code/modules/projectiles/guns/projectile/automatic/z8.dm
  code/modules/projectiles/guns/projectile/automatic/zoric.dm
  code/modules/projectiles/guns/projectile/boltgun.dm
  code/modules/projectiles/guns/projectile/shotgun/bojevic.dm
  code/modules/projectiles/guns/projectile/shotgun/bull.dm
  code/modules/projectiles/guns/projectile/shotgun/doublebarrel.dm
  code/modules/projectiles/guns/projectile/shotgun/gladstone.dm
  code/modules/projectiles/guns/projectile/shotgun/pump.dm
  code/modules/projectiles/guns/projectile/shotgun/regulator.dm
  code/modules/projectiles/guns/projectile/shotgun/sawnoff.dm
Labels: READY FOR REVIEW

#4729 Rig-mounted Autodoc fixes and tweaks
  code/modules/clothing/spacesuits/rig/modules/utility.dm
  code/modules/surgery/autodoc.dm
  nano/templates/autodoc.tmpl
  nano/templates/autodoc_capitalism.tmpl
Labels: Bug fixes, READY FOR REVIEW, Testing required

#4718 Should fix rig back slots not showing properly
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: READY FOR REVIEW, Testing required

#4739 Adds a paid public vendomat to medbay
  code/game/machinery/vending.dm
  code/game/objects/random/contraband.dm
  code/game/objects/random/medicine.dm
  code/modules/reagents/reagent_containers/dropper.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_containers/glass/beaker.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/stashes/stash_types/booze.dm
  icons/obj/reagentfillings.dmi
  icons/obj/syringe.dmi
  maps/CEVEris/_CEV_Eris.dmm
  maps/CEVEris/centcomm.dmm
Labels: READY FOR REVIEW

#4756 Reduces mouse damage to 0 and disables them buckling larger mobs
  code/game/objects/buckling.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
Labels: READY FOR REVIEW

#4762 [URGENT FIX] Ports the XSS exploit fix from tgstation
  code/modules/goonchat/browserassets/js/browserOutput.js
Labels: Bug fixes, Critical, Fix, High priority issue, Important, Porting, READY FOR REVIEW

#4749 Redoes Multiz Sound
  code/game/sound.dm
Labels: READY FOR REVIEW
