Repository discordia-space/CEV-Eris, pull requests merged in 2021-05, with the labels that each got.

#5915 Erismed Part 3 : Pain
  code/__DEFINES/damage_organs.dm
  code/__DEFINES/mobs.dm
  code/game/objects/items/weapons/implant/implants/carrion/infection_spider.dm
  code/modules/assembly/mousetrap.dm
  code/modules/core_implant/cruciform/rituals/inquisitor.dm
  code/modules/core_implant/cruciform/rituals/priest.dm
  code/modules/hydroponics/hydrochems/medicinalplants.dm
  code/modules/mechs/mech_damage.dm
  code/modules/mob/living/carbon/breathe.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/human_organs.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/unarmed_attack.dm
  code/modules/mob/living/carbon/shock.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/living_defense.dm
  code/modules/organs/external/damage.dm
  code/modules/organs/external/dismemberment.dm
  code/modules/organs/internal/_internal.dm
  code/modules/organs/internal/blood_vessels.dm
  code/modules/organs/internal/carrion.dm
  code/modules/organs/internal/internal_organ_processes.dm
  code/modules/organs/internal/muscles.dm
  code/modules/organs/internal/nerves.dm
  code/modules/organs/pain.dm
  code/modules/organs/surgery_helpers.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/projectile.dm
  code/modules/reagents/reagents/dispenser.dm
  code/modules/reagents/reagents/food-Drinks.dm
  code/modules/reagents/reagents/medicine.dm
Labels: READY FOR REVIEW

#6046 Adds the ability to shoot people near ladders from below/above
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/multiz/structures.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/projectile.dm
Labels: New features

#6130 Lets people break apart guns for gun parts
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/dallas.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  code/modules/projectiles/guns/projectile/automatic/slaught_o_matic.dm
  code/modules/projectiles/guns/projectile/automatic/sol.dm
  code/modules/projectiles/guns/projectile/boltgun.dm
  code/modules/projectiles/guns/projectile/revolver/sky_driver.dm
  code/modules/tips_and_tricks/gameplay.dm
Labels: New features

#6097 Refactors intercom code to not process , adds signals for area power changes and area apc deletion , removes .src from fire alarm code
  code/__DEFINES/components.dm
  code/game/area/areas.dm
  code/game/machinery/alarm.dm
  code/game/objects/items/devices/radio/intercom.dm
  code/modules/power/apc.dm
Labels: Refactoring

#6167 Erismed 3 slowdown nerf and bugfix
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/shock.dm
Labels: Balance

#6089 Junk Tractor Beam
  cev_eris.dme
  code/ATMOSPHERICS/atmospherics.dm
  code/controllers/subsystems/misc.dm
  code/datums/autolathe/circuits.dm
  code/game/objects/effects/portals.dm
  code/game/objects/items/weapons/circuitboards/computer/computer.dm
  code/modules/dungeons/junk_tractor_beam.dm
  code/modules/maps/tg/reader.dm
  icons/obj/structures/junk_tractor_beam.dmi
  maps/CEVEris/_CEV_Eris.dmm
  maps/encounters/junk_tractor_beam/junk_tractor_beam.dm
  maps/encounters/junk_tractor_beam/junk_tractor_beam.dmm
  maps/submaps/junk_field/j25_25/neutral/neutral.dm
  maps/submaps/junk_field/j25_25/neutral/neutral1.dmm
  maps/submaps/junk_field/j25_25/neutral/neutral2.dmm
  maps/submaps/junk_field/j25_25/neutral/neutral3.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral.dm
  maps/submaps/junk_field/j5_5/neutral/neutral1.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral10.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral11.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral2.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral3.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral4.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral5.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral6.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral7.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral8.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral9.dmm
  maps/submaps/junk_field/junk_field.dm
  nano/templates/jtb_console.tmpl
Labels: Map, New features

#6168 Fixes map related thingies and adds railings to engineering
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map

#6169 Re-enable autoresponse in ticket system
  code/controllers/subsystems/tickets/tickets.dm
Labels: Admin

#6165 Bill Trustworthy's Discount Firearms and Enterprising Detritus
  code/game/machinery/vending.dm
  icons/obj/vending.dmi
  maps/CEVEris/_CEV_Eris.dmm
Labels: New features

#6200 changes food sprites
  icons/obj/food.dmi
Labels: Sprites

#6207 Shield handling with signals
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/shields.dm
Labels: Refactoring

#6211 Junk Tractor Beam now increases bluespace entropy.
  code/game/objects/effects/portals.dm
Labels: Balance

#6213 removes health_deficiency
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: Balance

#6214 Arachnophobia
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
Labels: Fix

#6199 Typo Fixes, for the seen, and unseen.
  code/__DEFINES/misc.dm
  code/defines/procs/announce.dm
  code/game/gamemodes/events/ion_storm.dm
  code/game/gamemodes/malfunction/newmalf_ability_trees/tree_networking.dm
  code/game/machinery/teleporter.dm
  code/game/objects/items/blueprints.dm
Labels: Fix

#6205 resprited slimes
  icons/mob/slimes.dmi
Labels: Sprites

#6197 Erismed 3 faster knockout
  code/modules/mob/living/carbon/shock.dm
Labels: Balance

#6198 RnD Shutters aren't bugged roundstart
  maps/CEVEris/_CEV_Eris.dmm
Labels: Fix

#6201 Nanoforge Refactor
  code/game/machinery/autolathe/autolathe.dm
  code/game/machinery/autolathe/nanoforge.dm
Labels: Fix

#6204 Fuck parapen
  code/datums/uplink/stealthy and inconspicuous weapons.dm
  code/game/objects/items/devices/uplink_random_lists.dm
Labels: Balance

#6209 Kovacs tweaks
  code/game/machinery/vending.dm
Labels: Balance

#6210 nt tweaks
  code/modules/core_implant/cruciform/cruciform.dm
  code/modules/core_implant/cruciform/rituals/base.dm
Labels: Balance

#6208 kitchen storage again
  code/game/jobs/job/civilian.dm
  maps/CEVEris/_CEV_Eris.dmm
  maps/CEVEris/_Eris_areas.dm
Labels: Map

#6151 Multiz throwing
  code/modules/mob/living/carbon/carbon.dm
Labels: New features

#6203 Rebalance Part 1, the doc
  code/datums/uplink/ammunition.dm
  code/datums/uplink/announcements.dm
  code/datums/uplink/badassery.dm
  code/datums/uplink/devices and tools.dm
  code/datums/uplink/grenades.dm
  code/datums/uplink/hardsuit_modules.dm
  code/datums/uplink/highly visible and dangerous weapons.dm
  code/datums/uplink/implants.dm
  code/datums/uplink/medical.dm
  code/datums/uplink/stealth and camouflage items.dm
  code/datums/uplink/stealthy and inconspicuous weapons.dm
  code/game/antagonist/outer/blitzshell/blitzshell.dm
  code/game/objects/items/devices/uplink_random_lists.dm
  code/game/objects/items/gene_vial.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/modules/clothing/spacesuits/rig/modules/combat.dm
  code/modules/clothing/suits/armor.dm
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/pill.dm
Labels: Balance
