Repository discordia-space/CEV-Eris, pull requests merged in 2021-02, with the labels that each got.

#5912 Various Nt QOL changes
  code/datums/autolathe/biomatter.dm
  code/datums/outfits/jobs/church.dm
  code/datums/uplink/neotheology.dm
  code/game/objects/items/weapons/grenades/flashbang.dm
  code/game/objects/items/weapons/grenades/smokebomb.dm
  code/game/objects/items/weapons/storage/sheath.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/chaplain.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/neotheology.dm
  code/modules/stashes/stash_types/valueables.dm
  icons/obj/sheath.dmi
Labels: QOL

#5913 NT scourge bug fix
  code/game/objects/items/weapons/nt_melee.dm
Labels: Fix

#5917 Updates bomber
  code/modules/hivemind/mobs.dm
Labels: Balance

#5916 adds smoke grenades to the Sectech and gun vendor
  code/game/machinery/vending.dm
Labels: New features

#5885 Lascannon nerf
  code/modules/projectiles/guns/energy/laser.dm
Labels: Balance

#5905 Two new perks and one new littany for NT
  cev_eris.dme
  code/__DEFINES/_hydro_setup.dm
  code/__DEFINES/misc.dm
  code/datums/perks/job.dm
  code/game/atoms.dm
  code/game/jobs/job/church.dm
  code/game/objects/items/devices/scanners/scanners.dm
  code/game/turfs/simulated/cleaning.dm
  code/modules/core_implant/cruciform/modules.dm
  code/modules/core_implant/cruciform/rituals/agrolyte.dm
  code/modules/core_implant/cruciform/rituals/priest.dm
  code/modules/hydroponics/seed.dm
  code/modules/hydroponics/trays/tray_process.dm
  icons/effects/perks.dmi
Labels: New features

#5922 Spiderling sprite replace
  icons/effects/effects.dmi
Labels: Sprites

#5921 New priest perk + New littanies for agrolyte and custodian
  cev_eris.dme
  code/__DEFINES/misc.dm
  code/datums/perks/job.dm
  code/game/jobs/job/church.dm
  code/modules/core_implant/cruciform/cruciform.dm
  code/modules/core_implant/cruciform/machinery/obelisk.dm
  code/modules/core_implant/cruciform/modules.dm
  code/modules/core_implant/cruciform/rituals/agrolyte.dm
  code/modules/core_implant/cruciform/rituals/custodian.dm
  code/modules/reagents/reagents/medicine.dm
  icons/effects/perks.dmi
Labels: New features

#5938 EOTP FIX
  code/modules/core_implant/cruciform/machinery/eotp.dm
Labels: Fix

#5936 Nobles inheritance now has a perk.
  code/datums/perks/fate.dm
Labels: New features

#5926 Cruciform upgrades
  code/__DEFINES/misc.dm
  code/_onclick/item_attack.dm
  code/datums/autolathe/biomatter.dm
  code/game/objects/items/weapons/design_disks/NeoTheology.dm
  code/game/turfs/simulated.dm
  code/game/turfs/simulated/cleaning.dm
  code/modules/core_implant/cruciform/cruciform.dm
  code/modules/core_implant/cruciform/machinery/altar.dm
  code/modules/core_implant/cruciform/rituals/base.dm
  code/modules/core_implant/cruciform/rituals/construction.dm
  code/modules/core_implant/cruciform/upgrades.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  icons/obj/module.dmi
Labels: New features

#5934 Neohongo and latin (redone)
  cev_eris.dme
  code/__DEFINES/species_languages.dm
  code/datums/perks/job.dm
  code/datums/setup_option/backgrounds/origin.dm
  code/game/jobs/job/church.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/modules/goonchat/browserassets/css/browserOutput_override.css
  code/modules/mob/language/latin.dm
  code/modules/mob/language/neohongo.dm
  code/stylesheet.dm
Labels: New features

#5937 fire slug buff
  code/modules/projectiles/projectile/bullettypes.dm
Labels: Balance

#5935 Enables stock profiler for devs
  code/controllers/configuration.dm
  code/modules/admin/admin_verbs.dm
  code/modules/client/client_defines.dm
Labels: New features
