Repository discordia-space/CEV-Eris, pull requests merged in 2021-12, with the labels that each got.

#6803 Add working status check for crafting station
  code/game/machinery/crafting_station.dm
Labels: Fix

#6747 [RTM] Cover combat update 1
  code/__DEFINES/mobs.dm
  code/_onclick/click.dm
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/datums/datum_click_handlers.dm
  code/datums/movement/mob.dm
  code/game/machinery/deployable.dm
  code/game/machinery/machinery.dm
  code/game/objects/items.dm
  code/game/objects/structures/low_wall.dm
  code/modules/mob/inventory/slots.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/plasma.dm
  code/modules/tables/interactions.dm
Labels: Merge Conflict

#6807 INFECTION carrion spiders don't work in prosthetic limbs
  code/game/objects/items/weapons/implant/implants/carrion/infection_spider.dm
Labels: Skill issue

#6779 Paramedic update
  code/datums/outfits/jobs/medical.dm
  code/datums/repositories/crew/binary.dm
  code/datums/repositories/crew/vital.dm
  code/modules/clothing/head/armor.dm
  code/modules/clothing/suits/armor.dm
  code/modules/modular_computers/computers/subtypes/dev_tablet.dm
  code/modules/modular_computers/computers/subtypes/preset_tablet.dm
  code/modules/modular_computers/file_system/programs/medical/suit_sensors.dm
  code/modules/projectiles/guns/projectile/pistol/selfload.dm
  code/modules/research/designs.dm
  code/modules/research/designs/devices.dm
  code/modules/research/designs/weapon.dm
  code/modules/research/nodes/biotech.dm
  code/modules/research/nodes/combat.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/obj/guns/projectile/clarissa_white.dmi
  icons/obj/modular_tablet.dmi
  icons/obj/modular_tablet_moebius.dmi
  nano/css/shared.css
  nano/images/science.png
  nano/templates/crew_monitor.tmpl
Labels: Merge Conflict

#6793 Autopsy scanner error formula change
  code/game/objects/items/weapons/autopsy.dm
Labels: Skill issue

#6855 Firedoors and Scrubbers no longer process, attempt 2
  code/ATMOSPHERICS/components/unary/vent_scrubber.dm
  code/ZAS/Zone.dm
  code/__DEFINES/components.dm
  code/controllers/subsystems/machines.dm
  code/game/machinery/doors/firedoor.dm
Labels: Testing required

#6857 Remove RNG from disarming
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/recoil.dm
Labels: god forgive us
