Repository discordia-space/CEV-Eris, pull requests merged in 2021-08, with the labels that each got.

#6420 [MAP] Church Rework
  code/game/turfs/flooring/flooring_premade.dm
  icons/turf/flooring/wood.dmi
  maps/CEVEris/_CEV_Eris.dmm
  maps/CEVEris/_Eris_areas.dm
Labels: Map, New features

#6438 [JTB] Fix people being unable to get back in
  code/modules/dungeons/junk_tractor_beam.dm
Labels: Fix

#6439 [JTB] Rebalance loot
  maps/submaps/junk_field/j25_25/ironhammer/ironhammer1.dmm
  maps/submaps/junk_field/j25_25/ironhammer/ironhammer2.dmm
  maps/submaps/junk_field/j25_25/ironhammer/ironhammer3.dmm
  maps/submaps/junk_field/j25_25/serbian/serbian1.dmm
  maps/submaps/junk_field/j25_25/serbian/serbian2.dmm
  maps/submaps/junk_field/j25_25/serbian/serbian3.dmm
Labels: Balance

#6437 changes shotgun shell box size
  code/modules/projectiles/ammunition/boxes.dm
Labels: Balance

#6435 [MAP] Church rework hotfix
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map, Fix

#6433 HICU: bluespace fix and radial fix
  code/_onclick/hud/radial.dm
  code/modules/integrated_electronics/subtypes/input.dm
  code/modules/integrated_electronics/subtypes/manipulation.dm
  code/modules/integrated_electronics/subtypes/output.dm
Labels: Fix

#6430 RCD's bug fix and some balancing
  code/game/objects/items/weapons/RCD.dm
Labels: Fix, Balance

#6436 Autodoc
  cev_eris.dme
  code/datums/autolathe/circuits.dm
  code/game/machinery/autodoc.dm
  code/game/machinery/autodoc_excelsior.dm
  code/game/machinery/excelsior/ex_teleporter.dm
  code/game/objects/items/weapons/circuitboards/machinery/excelsior.dm
  icons/obj/machines/excelsior/autodoc.dmi
Labels: New features

#6459 [MAP] Add missing plating in lower bar
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map, Fix

#6455 Adds a lot of music tapes
  code/game/machinery/jukebox.dm
  code/game/objects/items/boombox.dm
  code/game/objects/items/musictapes.dm
  code/modules/media/media_tracks.dm
  code/modules/mob/living/carbon/superior_animal/roach/roach.dm
Labels: New features
