Repository discordia-space/CEV-Eris, pull requests merged in 2021-10, with the labels that each got.

#6550 Some love for the Kitchen
  code/game/machinery/biogenerator.dm
  code/game/objects/effects/roaches.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
Labels: New features

#6569 Fixes AI being able to see unintended places by moving up or down a z-level
  code/modules/mob/observer/freelook/ai/eye.dm
  code/modules/mob/observer/freelook/eye.dm
Labels: Fix

#6574 Explosions no longer force paralyse people
  code/modules/mob/living/carbon/human/human.dm
Labels: Balance

#6575 Fixes random wave radio oddity stacking
  code/game/objects/items/devices/radio/radio.dm
Labels: Fix

#6578 Reduces Techno-Tribalism Enforcer(cube) cooldown to something more manageable
  code/game/objects/items/devices/techno_tribalism.dm
Labels: Balance

#6554 fuck poopendarken wood
  code/game/turfs/flooring/flooring_premade.dm
  icons/turf/flooring/wood.dmi
Labels: Sprites

#6571 Fixes some roach/spider AI related runtimes
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Labels: Fix

#6577 NOW YOU GET TO BE A BIG SHOT
  code/__DEFINES/perks.dm
  code/datums/perks/oddity.dm
  code/game/objects/items/oddities.dm
  code/modules/mob/living/say.dm
  icons/inventory/face/icon.dmi
  icons/inventory/face/mob.dmi
Labels: Sprites, New features

#6562 Prefix for medspec
  code/modules/mob/living/carbon/human/human.dm
Labels: New features

#6555 glasses again (and bottles)
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/reagents/reagents/food-Drinks.dm
  icons/obj/drinks.dmi
  icons/obj/reagentfillings.dmi
Labels: Sprites

#6568 Ports server to 514, updates atmos to TauCeti state.
  cev_eris.dme
  code/ZAS/Airflow.dm
  code/__DEFINES/_extools_api.dm
  code/__DEFINES/callbacks.dm
  code/__DEFINES/tick.dm
  code/_global_vars/misc.dm
  code/controllers/configuration.dm
  code/controllers/master.dm
  code/controllers/subsystems/air.dm
  code/game/world.dm
  code/modules/admin/verbs/diagnostics.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/admin/verbs/ticklag.dm
  code/modules/client/client_defines.dm
  config/example/config.txt
  dependencies.sh
  html/add2changelog.html
  html/templates/footer.html
  html/templates/header.html
Labels: Refactoring

#6556 Buffs most pouches
  code/game/objects/items/weapons/storage/pouches.dm
Labels: Balance

#6576 Cognition now influences chance to trip,Cognition/Biological is required to see reagents inside a container, Chemist buff
  code/__DEFINES/misc.dm
  code/__DEFINES/mob_stats.dm
  code/__HELPERS/mobs.dm
  code/datums/mob_stats.dm
  code/datums/perks/job.dm
  code/datums/perks/perk.dm
  code/game/atoms.dm
  code/game/jobs/job/medical.dm
  code/game/turfs/flooring/flooring.dm
  code/modules/clothing/glasses/science.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/living.dm
Labels: Balance

#6677 Fix Malf AI Roll when using AI drone or joining after roundstart
  code/game/jobs/job/silicon.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/drone/_drone.dm
  code/modules/mob/living/silicon/robot/drone/drone_manufacturer.dm
  code/modules/mob/new_player/new_player.dm
Labels: Fix
