Repository discordia-space/CEV-Eris, pull requests merged in 2021-03, with the labels that each got.

#5949 Removes a debug tool that was spamming.
  code/modules/core_implant/cruciform/cruciform.dm
Labels: Fix

#5948 fix score for converting players to the church.
  code/modules/core_implant/cruciform/cruciform.dm
  code/modules/core_implant/cruciform/upgrades.dm
Labels: Fix

#5946 fix makeshift laser carbine sprites
  icons/obj/guns/energy/makeshift_carbine.dmi
Labels: Fix

#5939 Carrion organ eating buff
  code/game/antagonist/station/changeling.dm
  code/modules/organs/internal/carrion.dm
Labels: Balance

#5906 slowdown for most full body vests
  code/modules/clothing/suits/armor.dm
Labels: Balance

#5919 Detection of excels based on a timer
  code/datums/contract.dm
  code/datums/objective/objective.dm
  code/datums/objective/rev.dm
  code/defines/procs/announce.dm
  code/game/antagonist/station/revolutionary/excel_faction.dm
  code/game/machinery/excelsior/implantmaker.dm
  code/game/objects/items/weapons/implant/implanter.dm
Labels: New features

#5958 another fix to the craft system.
  code/datums/craft/step.dm
Labels: High priority issue

#5923 Porting ticket system with Discord support
  cev_eris.dme
  code/__DEFINES/subsystems-priority.dm
  code/__DEFINES/subsystems.dm
  code/__HELPERS/game.dm
  code/controllers/subsystems/tickets/mentor_tickets.dm
  code/controllers/subsystems/tickets/tickets.dm
  code/datums/topic/world.dm
  code/modules/admin/admin.dm
  code/modules/admin/tickets/adminticketsverbs.dm
  code/modules/admin/tickets/mentorticketsverbs.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/webhook/webhook.dm
Labels: New features, Testing required

#5969 Stats ritual rework
  code/modules/core_implant/cruciform/machinery/eotp.dm
  code/modules/core_implant/cruciform/rituals/group.dm
Labels: Refactoring, Testing required

#5929 Adds 2 new implant types
  cev_eris.dme
  code/datums/craft/recipes/weapon.dm
  code/game/objects/items/devices/organ_module/active/armguns.dm
  code/game/objects/items/devices/organ_module/active/armshields.dm
  code/modules/trade/datums/trade_stations_presets/zarya.dm
  icons/obj/guns/projectile/armsmg.dmi
  icons/obj/surgery.dmi
  icons/obj/weapons.dmi
Labels: New features

#5933 Makes atmos fires less painful for engineers to deal with
  code/ATMOSPHERICS/components/unary/vent_pump.dm
  code/ATMOSPHERICS/components/unary/vent_scrubber.dm
  code/__DEFINES/machinery.dm
  code/game/machinery/alarm.dm
  code/modules/power/apc.dm
  maps/CEVEris/_CEV_Eris.dmm
Labels: Balance

#5978 Sprite Fix
  code/modules/projectiles/guns/projectile/pistol/avasarala.dm
  icons/obj/guns/projectile/avasarala.dmi
  icons/obj/guns/projectile/colt.dmi
  icons/obj/guns/projectile/deckard.dmi
  icons/obj/guns/projectile/sky_driver.dmi
Labels: Fix, Sprites

#5975 Changes to cruciform energy regeneration and rituals.
  code/__DEFINES/components.dm
  code/datums/objective/individual_objective/church.dm
  code/modules/core_implant/core_implant.dm
  code/modules/core_implant/cruciform/cruciform.dm
  code/modules/core_implant/cruciform/modules.dm
  code/modules/core_implant/cruciform/rituals/base.dm
  code/modules/core_implant/cruciform/rituals/construction.dm
  code/modules/core_implant/cruciform/rituals/crusader.dm
  code/modules/core_implant/cruciform/rituals/machinery.dm
  code/modules/core_implant/group_ritual.dm
  code/modules/core_implant/ritual.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/say.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagents.dm
  code/modules/reagents/reagents/dispenser.dm
  code/modules/reagents/reagents/drugs.dm
  nano/images/kneeling.png
  nano/templates/sanity.tmpl
Labels: New features

#5984 MRE endless heating fix
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Fix

#5983 QoL: Cyborg tile stack can copy steel tiles by clicking on them
  code/game/objects/items/stacks/tiles/tile_types.dm
Labels: QOL, READY FOR REVIEW

#5989 Fixes/tweaks Hivemind mobs speed
  code/modules/hivemind/mobs.dm
Labels: Balance, Fix

#5993 [Hotfix] Reduce shuttle travel time on overmap
  code/modules/overmap/overmap_shuttle.dm
Labels: Fix, High priority issue

#5994 [Hotfix] Fix shuttles not being able to move back to Eris
  code/modules/overmap/overmap_shuttle.dm
  code/modules/overmap/sectors.dm
Labels: Fix, High priority issue

#5941 Gun sprite tweaks
  code/datums/autolathe/guns.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/modules/cargo/packs.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/plasma.dm
  code/modules/projectiles/guns/projectile/pistol/selfload.dm
  code/modules/projectiles/guns/projectile/shotgun/pump.dm
  code/modules/trade/datums/trade_stations_presets/hellcat.dm
  icons/obj/guns/energy/cassad.dmi
  icons/obj/guns/energy/iongun.dmi
  icons/obj/guns/launcher/crossbow-solid.dmi
  icons/obj/guns/launcher/rxb.dmi
  icons/obj/guns/matter/reclaimer.dmi
  icons/obj/guns/projectile/ak.dmi
  icons/obj/guns/projectile/bull.dmi
  icons/obj/guns/projectile/chinalake.dmi
  icons/obj/guns/projectile/gladstone.dmi
  icons/obj/guns/projectile/l6.dmi
  icons/obj/guns/projectile/pk.dmi
  icons/obj/guns/projectile/regulator.dmi
  icons/obj/guns/projectile/rocket.dmi
  icons/obj/guns/projectile/shotgun.dmi
  icons/obj/guns/projectile/sol.dmi
Labels: Sprites
