Repository discordia-space/CEV-Eris, pull requests merged in 2021-11, with the labels that each got.

#6714 IH medical HUD + EMT belt for medspec
  code/datums/outfits/jobs/security.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/glasses/hud.dm
Labels: New features

#6621 Hardcases
  cev_eris.dme
  code/datums/autolathe/containers.dm
  code/datums/craft/recipes/guns.dm
  code/datums/craft/recipes/tools.dm
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/design_disks/asters.dm
  code/game/objects/items/weapons/design_disks/excelsior.dm
  code/game/objects/items/weapons/design_disks/ironhammer.dm
  code/game/objects/items/weapons/design_disks/moebius.dm
  code/game/objects/items/weapons/design_disks/technomancers.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  icons/obj/cases.dmi
Labels: Sprites, New features

#6563 languages tweak
  code/game/jobs/job/church.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/guild.dm
  code/game/jobs/job/security.dm
  code/game/objects/items/devices/last_shelter.dm
Labels: QOL

#6584 Grenade launchers
  cev_eris.dme
  code/datums/autolathe/guns.dm
  code/datums/contract.dm
  code/datums/craft/recipes/guns.dm
  code/datums/uplink/grenades.dm
  code/game/objects/items/weapons/grenades/explosive.dm
  code/game/objects/items/weapons/grenades/frag.dm
  code/game/objects/items/weapons/grenades/grenade.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/storage/deferred.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/projectiles/guns/launcher/grenade_launcher.dm
  code/modules/projectiles/guns/launcher/projectile_grenade_launcher.dm
  code/modules/projectiles/guns/projectile/automatic/z8.dm
  code/modules/trade/datums/trade_stations_presets/fs_weapon_factory.dm
  code/modules/trade/datums/trade_stations_presets/nt_cruisers.dm
  maps/CEVEris/_CEV_Eris.dmm
Labels: New features

#6737 Add Create Portals verb in Fun tab
  code/game/objects/effects/portals.dm
  code/modules/admin/admin_verbs.dm
Labels: Admin, New features

#6739 Fix Move Shuttle verb in Secret panel
  code/modules/admin/secrets/admin_secrets/move_shuttle.dm
Labels: Admin, Fix

#6750 Lowers pistol wield delay and wield factor in general
  code/modules/projectiles/guns/projectile/pistol/colt.dm
  code/modules/projectiles/guns/projectile/pistol/giskard.dm
  code/modules/projectiles/guns/projectile/pistol/handmade.dm
  code/modules/projectiles/guns/projectile/pistol/mandella.dm
  code/modules/projectiles/guns/projectile/pistol/mk58.dm
  code/modules/projectiles/guns/projectile/pistol/olivaw.dm
  code/modules/projectiles/guns/projectile/pistol/paco.dm
  code/modules/projectiles/guns/projectile/pistol/selfload.dm
Labels: Skill issue

#6628 Maint fauna changes
  cev_eris.dme
  code/game/objects/effects/spiders.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/ai.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/attack.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/life.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
  code/modules/mob/living/carbon/superior_animal/roach/roach.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/bluespace.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/hunter.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/nanites.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/roachling.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/support.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
  code/modules/reagents/reagents/other.dm
  code/modules/reagents/reagents/toxins.dm
Labels: New features, Balance

#6615 Ports various Mech fixes/tweaks from Occulus-Eris and Aurora
  code/__DEFINES/mobs.dm
  code/modules/mechs/components/arms.dm
  code/modules/mechs/equipment/utility.dm
  code/modules/mechs/mech.dm
  code/modules/mechs/mech_interaction.dm
  code/modules/mechs/mech_movement.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/hivetechboss.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/onestarboss.dm
  code/modules/mob/mob.dm
  sound/mechs/mech_punch.ogg
  sound/mechs/mech_punch_fast.ogg
  sound/mechs/mech_punch_slow.ogg
Labels: Sounds, Fix
