Repository discordia-space/CEV-Eris, pull requests merged in 2021-06, with the labels that each got.

#6138 Add Dusty the bluespace cat
  code/game/machinery/mindswapper.dm
  code/modules/error_handler/error_handler.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  icons/mob/animal.dmi
Labels: New features

#6304 Vertically centering ID cards
  icons/obj/card.dmi
Labels: Sprites

#6298 makes True Faith activate like Exotic Inspiration
  code/datums/perks/job.dm
  code/modules/core_implant/cruciform/cruciform.dm
  code/modules/core_implant/cruciform/machinery/obelisk.dm
Labels: Fix

#6306 Malf AI should not be able to recall bluespace jumps
  code/game/gamemodes/malfunction/newmalf_ability_trees/tree_interdiction.dm
Labels: Balance

#6303 Fix slipping on ladders
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/weapons/clown_items.dm
  code/game/objects/items/weapons/implant/implants/carrion/smooth_spider.dm
Labels: Fix

#6302 Modifies .60 rarity to something more sane, unblacklists .35 ammo types
  code/modules/projectiles/ammunition/boxes.dm
Labels: Balance

#6307 Fixes no guns having a bayonet slot
  code/modules/projectiles/gun.dm
Labels: Fix

#6308 Motherfucker melee damage nerf
  code/modules/projectiles/guns/projectile/automatic/motherfucker.dm
Labels: Balance

#6309 Dusty cannot be carried anymore
  code/modules/mob/living/simple_animal/friendly/cat.dm
Labels: Fix

#6256 Adds random disk crate to Zarya
  code/game/objects/items/weapons/storage/deferred.dm
  code/modules/trade/datums/trade_stations_presets/zarya.dm
Labels: New features

#6349 Guild Lobby Map Rework
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map
