Repository discordia-space/CEV-Eris, pull requests merged in 2021-04, with the labels that each got.

#5998 Update gravgen sprite and add glowing effect
  code/modules/power/gravitygenerator.dm
  icons/obj/machines/gravity_generator.dmi
Labels: Sprites

#5997 Improve ticket system based on feedbacks
  code/controllers/subsystems/tickets/tickets.dm
  code/modules/admin/tickets/mentorticketsverbs.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/goonchat/browserassets/css/browserOutput_override.css
  code/stylesheet.dm
Labels: Admin, READY FOR REVIEW

#5988 loot rework: clothing edition
  cev_eris.dme
  code/__DEFINES/spawner/_spawner.dm
  code/datums/loot_spawner.dm
  code/game/objects/items/weapons/tanks/jetpack.dm
  code/game/objects/items/weapons/tools/pickaxe.dm
  code/game/objects/random/cloth.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/accessories/holster.dm
  code/modules/clothing/chameleon.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/glasses/misc.dm
  code/modules/clothing/glasses/thermal.dm
  code/modules/clothing/glasses/welding.dm
  code/modules/clothing/gloves/boxing.dm
  code/modules/clothing/gloves/color.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/gloves/stungloves.dm
  code/modules/clothing/head/armor.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/head/soft_caps.dm
  code/modules/clothing/masks/balaclava.dm
  code/modules/clothing/masks/boxing.dm
  code/modules/clothing/masks/breath.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/masks/voice.dm
  code/modules/clothing/shoes/colour.dm
  code/modules/clothing/shoes/jobs.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/spacesuits/bomb.dm
  code/modules/clothing/spacesuits/captain.dm
  code/modules/clothing/spacesuits/void/merc.dm
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/clothing/spacesuits/void/void.dm
  code/modules/clothing/spawn_data/spawn_data.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/bio.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/suits/storage.dm
  code/modules/clothing/suits/utility.dm
  code/modules/clothing/under/jobs/security.dm
Labels: Refactoring

#5987 Part 1 of fix for large casings and misc magazine icon fixes
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/guns/projectile.dm
  icons/obj/ammo.dmi
  icons/obj/ammo_mags.dmi
Labels: Fix

#5980 Areas without apc are no longer considered for the Disturbance objective.
  code/__HELPERS/areas.dm
  code/datums/objective/individual_objective/technomancers.dm
Labels: Fix

#6015 Glide size recursion removal
  code/game/atoms_movable.dm
Labels: Optimization

#6019 Fix: Chem Duping Bug
  code/modules/reagents/reagent_containers.dm
Labels: Fix

#6007 removes stun from AMR
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullettypes.dm
Labels: Balance

#6014 [Fix] Bunch of planetoids fixes
  code/game/atoms.dm
  code/game/objects/effects/spawners/corpsespawner.dm
  code/modules/mining/mine_items.dm
  code/modules/overmap/_defines.dm
  code/modules/overmap/exoplanets/helpers.dm
  code/modules/overmap/exoplanets/planet_types/volcanic.dm
  code/modules/overmap/exoplanets/turfs.dm
  code/modules/shuttles/landmarks.dm
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
  maps/CEVEris/overmap-eris.dm
  maps/CEVEris/shuttles-eris.dm
  maps/encounters/spacefortress/spacefortress.dm
  maps/encounters/spaceruins/spaceruins.dm
  maps/submaps/planetary_ruins/crashed_pod/crashed_pod.dmm
  maps/submaps/planetary_ruins/datacapsule/datacapsule.dm
  maps/submaps/planetary_ruins/deserted_lab/deserted_lab.dm
  maps/submaps/planetary_ruins/deserted_lab/deserted_lab.dmm
  maps/submaps/planetary_ruins/drill_site/drill_site.dm
  maps/submaps/planetary_ruins/ec_old_crash/ec_old_crash.dm
  maps/submaps/planetary_ruins/ec_old_crash/ec_old_crash.dmm
  maps/submaps/planetary_ruins/fountain/fountain_ruin.dm
  maps/submaps/planetary_ruins/hut/hut.dm
  maps/submaps/planetary_ruins/hydrobase/hydrobase.dm
  maps/submaps/planetary_ruins/hydrobase/hydrobase.dmm
  maps/submaps/planetary_ruins/lodge/lodge.dm
  maps/submaps/planetary_ruins/lodge/lodge.dmm
  maps/submaps/planetary_ruins/marooned/marooned.dm
  maps/submaps/planetary_ruins/marooned/marooned.dmm
  maps/submaps/planetary_ruins/marooned/marooned_icons.dmi
  maps/submaps/planetary_ruins/oasis/oasis.dm
  maps/submaps/planetary_ruins/oldpod/oldpod.dmm
  maps/submaps/planetary_ruins/radshrine/radshrine.dm
  maps/submaps/planetary_ruins/radshrine/radshrine.dmm
  maps/submaps/planetary_ruins/spider_nest/spider_nest.dm
  maps/submaps/planetary_ruins/spider_nest/spider_nest.dmm
  maps/submaps/planetary_ruins/tar_anomaly/tar_anomaly.dm
  oldcode/old_emergency_shuttle_controller.dm
Labels: Fix

#6025 Fix shuttle landing area not having any mineral ressources
  code/modules/random_map/noise/ore.dm
Labels: Fix

#6020 Hivemind sprite
  code/modules/hivemind/mobs.dm
  icons/mob/hivemind.dmi
Labels: Sprites

#6021 Medical RIG resprite
  icons/inventory/feet/icon.dmi
  icons/inventory/feet/mob.dmi
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/mob/rig_back.dmi
  icons/obj/rig_modules.dmi
Labels: Sprites

#6023 IH now has less base score.
  code/game/gamemodes/scores.dm
Labels: Balance, Fix

#6012 Ghosts can occupy borers whenever
  code/game/antagonist/alien/borer.dm
  code/modules/mob/living/simple_animal/borer/borer.dm
Labels: New features

#6013 Fixes monkey cubes
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Fix

#6026 Make mining great again
  code/modules/mining/drilling/drill.dm
  code/modules/overmap/exoplanets/planet_types/grass.dm
  code/modules/random_map/_random_map_setup.dm
  code/modules/random_map/noise/ore.dm
Labels: Balance

#6041 NeoTheology Voidsuit
  code/datums/autolathe/biomatter.dm
  code/game/objects/items/weapons/design_disks/NeoTheology.dm
  code/modules/clothing/suits/neotheology.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
Labels: New features, Sprites

#6039 Remove salary of NT jobs
  code/game/jobs/job/church.dm
Labels: Balance

#6024 Adds RIG tab and bunch of related crates to Guild Console
  code/modules/cargo/packs.dm
Labels: New features

#6061 New sprites for smartfridge, soda dispenser and drinks showcase
  code/game/machinery/kitchen/smartfridge.dm
  code/modules/reagents/machinery/chem_dispenser.dm
  icons/obj/chemical.dmi
  icons/obj/vending.dmi
Labels: Sprites

#6101 Gun and Armour parts
  code/datums/autolathe/biomatter.dm
  code/datums/craft/crafting_items.dm
  code/game/objects/items/weapons/design_disks/NeoTheology.dm
  code/game/objects/items/weapons/storage/pouches.dm
Labels: Balance, New features

#6081 autopsy score fixes
  code/game/objects/items/weapons/autopsy.dm
  code/modules/core_implant/cruciform/rituals/priest.dm
Labels: Fix

#6083 Fixed broken overlays for beakers
  code/modules/reagents/reagent_containers/glass/beaker.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  icons/obj/reagentfillings.dmi
Labels: Fix

#6085 offerings fixes
  code/modules/core_implant/cruciform/rituals/priest.dm
Labels: Fix

#6110 Ironhammer resprite and broken code removal, credits to CeUvi
  code/modules/clothing/head/armor.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  icons/inventory/belt/icon.dmi
  icons/inventory/belt/mob.dmi
  icons/inventory/face/icon.dmi
  icons/inventory/face/mob.dmi
  icons/inventory/feet/icon.dmi
  icons/inventory/feet/mob.dmi
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
Labels: Sprites

#6112 caps the makeshift spear damage
  code/game/objects/items/weapons/material/material_weapons.dm
Labels: Balance

#6090 Fix the coolant tanks
  code/modules/reagents/reagents/other.dm
  code/modules/research/xenoarchaeology/machinery/coolant.dm
Labels: Fix

#6109 Psyionic to psionic
  code/datums/perks/fate.dm
  code/datums/setup_option/backgrounds/fate.dm
Labels: Fix

#6108 Tweak decloner price
  code/modules/projectiles/guns/energy/decloner.dm
Labels: Balance

#6106 encodes helm computer
  code/modules/overmap/ships/computers/helm.dm
Labels: Fix

#6098 More acolytes and all dedicated NTs speak latin now
  code/game/jobs/job/church.dm
  maps/CEVEris/_CEV_Eris.dmm
Labels: Balance

#6099 Tweaked gun vendor prices
  code/game/machinery/vending.dm
  code/modules/projectiles/guns/energy/egun.dm
  code/modules/projectiles/guns/projectile/automatic/atreides.dm
  code/modules/projectiles/guns/projectile/boltgun.dm
  code/modules/projectiles/guns/projectile/pistol/giskard.dm
  code/modules/projectiles/guns/projectile/pistol/olivaw.dm
  code/modules/projectiles/guns/projectile/revolver/havelock.dm
  code/modules/projectiles/guns/projectile/shotgun/gladstone.dm
  code/modules/projectiles/guns/projectile/shotgun/pump.dm
Labels: Balance

#6107 AKening
  code/datums/autolathe/guns.dm
  code/datums/craft/recipes/guns.dm
  code/game/objects/items/weapons/design_disks/autolathe_disks.dm
  code/game/objects/items/weapons/design_disks/frozen_star.dm
  code/modules/cargo/packs.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/trade/datums/trade_stations_presets/hellcat.dm
  icons/obj/guns/projectile/ak.dmi
  icons/obj/guns/projectile/ak/brushmaster.dmi
  icons/obj/guns/projectile/ak/excel.dmi
  icons/obj/guns/projectile/ak/kalash.dmi
  icons/obj/guns/projectile/ak/krinkov.dmi
  icons/obj/guns/projectile/ak/venger.dmi
  icons/obj/guns/projectile/ak/vipr.dmi
  icons/obj/guns/projectile/ak/wasp.dmi
Labels: New features

#6100 another day another fix to the craft system.
  code/__DEFINES/craft.dm
  code/datums/craft/recipe.dm
  code/datums/craft/step.dm
Labels: Fix

#6095 Players with godlike strength(robustness) can tear apart handcuffs
  code/modules/mob/living/carbon/resist.dm
Labels: New features

#6091 Remove the carrion part in reveal adversaries litany
  code/modules/core_implant/cruciform/rituals/base.dm
Labels: Balance

#6086 Divine blessing ritual
  code/modules/core_implant/cruciform/rituals/priest.dm
Labels: New features

#6094 Fixes infinite handcuff exploit and minor resist improvements.
  code/game/objects/items/weapons/traps.dm
  code/modules/mob/living/carbon/resist.dm
Labels: Fix

#6111 Buffs internal storage module for RIG's
  code/modules/clothing/spacesuits/rig/modules/storage.dm
Labels: Balance

#6104 Most mobs can be mind-swapped
  code/game/machinery/mindswapper.dm
Labels: New features

#6105 Refactors and fixes malf AI emergency forcefield , buffs emergency forcefield
  code/game/gamemodes/malfunction/newmalf_ability_trees/tree_manipulation.dm
  code/modules/shieldgen/emergency_shield.dm
Labels: Balance, Fix

#6120 Spear Banishment
  code/game/objects/items/weapons/improvised_components.dm
  code/game/objects/items/weapons/material/misc.dm
Labels: god forgive us

#6118 Trade fixes
  code/controllers/subsystems/trade.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/modules/trade/datums/trade_stations_presets/zarya.dm
Labels: Balance

#6131 Fixes closets
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Fix

#6134 Lets you put tools in the suit slot.
  code/modules/clothing/clothing.dm
Labels: QOL

#6123 Remove ladder cheese with slipping items, traps and mines
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/weapons/clown_items.dm
  code/game/objects/items/weapons/implant/implants/carrion/smooth_spider.dm
  code/game/objects/items/weapons/mine.dm
  code/game/objects/items/weapons/traps.dm
  code/game/turfs/simulated.dm
Labels: Balance

#6127 cruciform energy fixes v3
  code/modules/core_implant/cruciform/cruciform.dm
Labels: Fix

#6122 Spear is now craftable
  code/datums/craft/recipes/weapon.dm
  code/game/objects/items/weapons/tools/knives.dm
  icons/inventory/back/mob.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/weapons.dmi
Labels: New features, Sprites

#6119 Remove NT pipes from bioreactor room
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map

#6133 Tones down the explosive potential of water/pot bombs
  code/modules/reagents/recipes.dm
Labels: Balance

#5910 Turns the AMR into the shitcoded snowflake gun it was always meant to be
  code/__DEFINES/items.dm
  code/datums/uplink/ammunition.dm
  code/game/machinery/doors/door.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
  code/game/turfs/simulated/walls.dm
  code/modules/clothing/glasses/thermal.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile/sniper.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullettypes.dm
Labels: Balance, New features

#6125 Replaces spare sols in armoury (not the lockers) with the new IH AK.
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map
