Repository discordia-space/CEV-Eris, pull requests merged in 2022-05, with the labels that each got.

#7201 Fix and tweak serial numbers
  code/datums/craft/gun_parts.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/decloner.dm
  code/modules/projectiles/guns/energy/floragun.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/lasersmg.dm
  code/modules/projectiles/guns/energy/nuclear.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/guns/energy/temperature.dm
  code/modules/projectiles/guns/energy/toxgun.dm
  code/modules/projectiles/guns/launcher/syringe_gun.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/dallas.dm
  code/modules/projectiles/guns/projectile/automatic/drozd.dm
  code/modules/projectiles/guns/projectile/automatic/luty.dm
  code/modules/projectiles/guns/projectile/automatic/maxim.dm
  code/modules/projectiles/guns/projectile/automatic/motherfucker.dm
  code/modules/projectiles/guns/projectile/automatic/slaught_o_matic.dm
  code/modules/projectiles/guns/projectile/automatic/vintorez.dm
  code/modules/projectiles/guns/projectile/pistol/mandella.dm
Labels: Merge Conflict

#7224 FBP changes
  code/datums/autolathe/prostheses.dm
  code/game/objects/items/weapons/design_disks/excelsior.dm
  code/modules/organs/body_modifications.dm
  code/modules/organs/external/subtypes/robotic_types.dm
  icons/mob/human_races/cyberlimbs/asters.dmi
  icons/mob/human_races/cyberlimbs/excelsior.dmi
  icons/mob/human_races/cyberlimbs/ghetto.dmi
  icons/mob/human_races/cyberlimbs/moebius.dmi
  icons/mob/human_races/cyberlimbs/serbian.dmi
  icons/mob/human_races/cyberlimbs/technomancer.dmi
Labels: Sprites, New features

#7225 Mining Overhaul Part 2.4
  code/modules/mining/drilling/deep_drill.dm
Labels: New features
