Repository discordia-space/CEV-Eris, pull requests merged in 2022-11, with the labels that each got.

#7599 Codespeak refactor, serb codes [TEST]
  code/__DEFINES/perks.dm
  code/controllers/subsystems/ticker.dm
  code/datums/perks/job.dm
  code/game/antagonist/outer/mercenary/mercenary.dm
  code/game/jobs/job/security.dm
  code/modules/mob/hear_say.dm
  code/modules/mob/language/codespeak.dm
  icons/effects/perks.dmi
Labels: New features

#7704 Blocking(melee)
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/datums/datum_hud.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/species/species_hud.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/mob_movement.dm
  icons/mob/misc_overlays.dmi
  icons/mob/screen/ErisStyleHolo.dmi
  interface/skin.dmf
Labels: Testing required

#7821 Another(last one) batch of melee rework fixes
  code/_onclick/item_attack.dm
  code/datums/datum_hud.dm
  code/game/objects/items/weapons/melee/energy.dm
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Merge Conflict

#7813 Fix Jive comms
  code/game/objects/items/devices/radio/radio.dm
  code/modules/mob/language/jive.dm
  code/modules/mob/living/say.dm
Labels: Testing required
