Repository discordia-space/CEV-Eris, pull requests merged in 2022-02, with the labels that each got.

#7014 New sprites for teargas and smoke grenades
  code/game/objects/items/weapons/grenades/chem_grenade.dm
  code/game/objects/items/weapons/grenades/smokebomb.dm
  icons/obj/grenade.dmi
Labels: Sprites

#7015 Mining Overhaul Part 2.1
  cev_eris.dme
  code/modules/mining/drilling/golem_wave.dm
  code/modules/mob/living/carbon/superior_animal/golem/golem.dm
  code/modules/mob/living/carbon/superior_animal/golem/golem_core.dm
  code/modules/mob/living/carbon/superior_animal/golem/types/ansible.dm
  code/modules/mob/living/carbon/superior_animal/golem/types/coal.dm
  code/modules/mob/living/carbon/superior_animal/golem/types/diamond.dm
  code/modules/mob/living/carbon/superior_animal/golem/types/iron.dm
  code/modules/mob/living/carbon/superior_animal/golem/types/platinum.dm
  code/modules/mob/living/carbon/superior_animal/golem/types/silver.dm
  code/modules/mob/living/carbon/superior_animal/golem/types/uranium.dm
  icons/mob/golems.dmi
Labels: New features, Balance

#6995 NT "Inferno" grenade, more quotes
  cev_eris.dme
  code/datums/autolathe/biomatter.dm
  code/game/objects/items/weapons/design_disks/NeoTheology.dm
  code/game/objects/items/weapons/grenades/flashbang.dm
  code/game/objects/items/weapons/grenades/frag.dm
  code/game/objects/items/weapons/grenades/heatwave.dm
  code/modules/projectiles/guns/energy/crossbow.dm
  code/modules/projectiles/guns/energy/plasma.dm
Labels: New features

#7030 Fix microwav, fire barrel, hydroponics tray secure unsecure verbs
  code/game/machinery/kitchen/microwave.dm
  code/modules/hydroponics/trays/tray.dm
Labels: Fix

#7031 Remove cables and pipes from planetary ruins to reduce server load.
  maps/submaps/planetary_ruins/crashed_pod/crashed_pod.dmm
  maps/submaps/planetary_ruins/ec_old_crash/ec_old_crash.dmm
  maps/submaps/planetary_ruins/marooned/marooned.dmm
  maps/submaps/planetary_ruins/oldpod/oldpod.dmm
Labels: Map

#7032 Warn player if they are trying to spawn without brain or eyes
  code/modules/mob/new_player/new_player.dm
Labels: New features

#7037 Mining Overhaul Part 2.2
  code/modules/mining/drilling/deep_drill.dm
  code/modules/mining/drilling/golem_wave.dm
  code/modules/mob/living/carbon/superior_animal/golem/golem.dm
Labels: Balance

#7033 Fix ricochet text
  code/game/turfs/simulated/walls.dm
Labels: Fix

#7036 fixes scopes
  code/game/objects/items.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/projectiles/gun.dm
Labels: Fix

#7035 LMG and HMG fix
  code/modules/mob/living/recoil.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  code/modules/projectiles/guns/projectile/automatic/maxim.dm
Labels: Balance

#6977 Armor buff
  code/modules/clothing/head/armor.dm
  code/modules/clothing/spacesuits/rig/suits/combat.dm
  code/modules/clothing/spacesuits/rig/suits/merc.dm
  code/modules/clothing/spacesuits/rig/suits/station.dm
  code/modules/clothing/spacesuits/void/anomaly_suit.dm
  code/modules/clothing/spacesuits/void/excelsior.dm
  code/modules/clothing/spacesuits/void/merc.dm
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/clothing/suits/neotheology.dm
  code/modules/projectiles/projectile/beams.dm
Labels: Balance

#6965 Recoil and Armor QoL
  code/__DEFINES/items_clothing.dm
  code/modules/mob/living/recoil.dm
  code/modules/projectiles/gun.dm
Labels: Merge Conflict
