Repository discordia-space/CEV-Eris, pull requests merged in 2022-10, with the labels that each got.

#7499 Penetration improvements and bugfixes [ready]
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/misc.dm
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/mob/living/living_defense.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/plasma.dm
Labels: Testing required

#7650 Fix missing disposal pipe in medical
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map

#7651 Switch stalker position in armory dungeon room
  maps/submaps/dungeon_rooms/rooms/armory.dmm
Labels: Map

#7525 Accuracy tweaks [ready]
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullets.dm
Labels: Testing required

#7672 Fixes a codebit
  code/modules/genetics/moecubes.dm
Labels: Fix

#7676 Fix division by zero
  code/game/objects/heatwave.dm
  code/modules/mechs/mech_damage.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/superior_animal/defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/mob/mob_grab_specials.dm
Labels: Fix

#7677 Fix click handler runtime
  code/datums/datum_click_handlers.dm
Labels: Fix

#7674 Set default recoil for /obj/item/arrow
  code/modules/projectiles/guns/matter/launcher/nt_sprayer.dm
Labels: Fix

#7675 Add check for division by 0 in block_damage
  code/modules/projectiles/projectile.dm
Labels: Fix

#7684 fix knuckle dusters oversights
  code/datums/craft/recipes/clothing.dm
  code/modules/clothing/gloves/miscellaneous.dm
Labels: Fix

#7678 OS dungeon generated only when teleporter is triggered
  code/__DEFINES/components.dm
  code/modules/dungeons/crawler/dungeon_gen.dm
  code/modules/dungeons/teleporter.dm
Labels: Optimization

#7679 Fixes von krabin deconstruction
  code/game/objects/items/devices/von-krabin.dm
Labels: Fix

#7681 Fixes grip not updating result on junk frames
  code/datums/craft/gun_parts.dm
Labels: Fix
