Repository discordia-space/CEV-Eris, pull requests merged in 2022-09, with the labels that each got.

#7462 Fix map issues for the CI
  code/modules/unit_tests/map_tests.dm
  maps/CEVEris/_CEV_Eris.dmm
  maps/CEVEris/_Eris_areas.dm
Labels: Map

#7473 Unlocks fullauto limits, Molly burstfire mode
  code/__DEFINES/items.dm
  code/__DEFINES/weapons.dm
  code/datums/datum_click_handlers.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/mods/research_mods.dm
  code/modules/projectiles/guns/projectile/automatic/maxim.dm
  code/modules/projectiles/guns/projectile/automatic/molly.dm
Labels: Merge Conflict

#7543 It's a ship!
  code/modules/economy/cash_register.dm
  code/modules/integrated_electronics/subtypes/time.dm
  code/modules/mob/mob.dm
  nano/templates/pda.tmpl
Labels: Critical, High priority issue

#7546 Ultimate gun assembly update (part 1) [do merge now]
  code/datums/craft/gun_parts.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/atreides.dm
  code/modules/projectiles/guns/projectile/automatic/c20r.dm
  code/modules/projectiles/guns/projectile/automatic/dallas.dm
  code/modules/projectiles/guns/projectile/automatic/drozd.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  code/modules/projectiles/guns/projectile/automatic/luty.dm
  code/modules/projectiles/guns/projectile/automatic/maxim.dm
  code/modules/projectiles/guns/projectile/automatic/molly.dm
  code/modules/projectiles/guns/projectile/automatic/motherfucker.dm
  code/modules/projectiles/guns/projectile/automatic/sol.dm
  code/modules/projectiles/guns/projectile/automatic/straylight.dm
  code/modules/projectiles/guns/projectile/automatic/sts35.dm
  code/modules/projectiles/guns/projectile/automatic/vintorez.dm
  code/modules/projectiles/guns/projectile/automatic/wintermute.dm
  code/modules/projectiles/guns/projectile/automatic/z8.dm
  code/modules/projectiles/guns/projectile/automatic/zoric.dm
  code/modules/projectiles/guns/projectile/battle_rifle/boltgun.dm
  code/modules/projectiles/guns/projectile/battle_rifle/kovacs.dm
  code/modules/projectiles/guns/projectile/pistol/avasarala.dm
  code/modules/projectiles/guns/projectile/pistol/colt.dm
  code/modules/projectiles/guns/projectile/pistol/giskard.dm
  code/modules/projectiles/guns/projectile/pistol/handmade.dm
  code/modules/projectiles/guns/projectile/pistol/lamia.dm
  code/modules/projectiles/guns/projectile/pistol/mandella.dm
  code/modules/projectiles/guns/projectile/pistol/mk58.dm
  code/modules/projectiles/guns/projectile/pistol/olivaw.dm
  code/modules/projectiles/guns/projectile/pistol/paco.dm
  code/modules/projectiles/guns/projectile/pistol/selfload.dm
  code/modules/projectiles/guns/projectile/revolver/consul.dm
  code/modules/projectiles/guns/projectile/revolver/deckard.dm
  code/modules/projectiles/guns/projectile/revolver/handmade.dm
  code/modules/projectiles/guns/projectile/revolver/havelock.dm
  code/modules/projectiles/guns/projectile/revolver/mateba.dm
  code/modules/projectiles/guns/projectile/revolver/revolver.dm
  code/modules/projectiles/guns/projectile/revolver/sky_driver.dm
  code/modules/projectiles/guns/projectile/shotgun/bojevic.dm
  code/modules/projectiles/guns/projectile/shotgun/bull.dm
  code/modules/projectiles/guns/projectile/shotgun/doublebarrel.dm
  code/modules/projectiles/guns/projectile/shotgun/gladstone.dm
  code/modules/projectiles/guns/projectile/shotgun/handmade.dm
  code/modules/projectiles/guns/projectile/shotgun/pump.dm
  code/modules/projectiles/guns/projectile/shotgun/regulator.dm
  code/modules/projectiles/guns/projectile/sniper.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/tb_cheapammofactorys.dm
  icons/obj/crafts.dmi
  icons/obj/guns/projectile/obrez_bolt.dmi
Labels: Merge Conflict

#7549 Gun smithing update 2: Makeshift frames
  code/datums/craft/recipes/guns.dm
  code/game/objects/items/devices/organ_module/active/armguns.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/motherfucker.dm
  code/modules/projectiles/guns/projectile/flaregun.dm
Labels: Merge Conflict

#7493 Firedoors are no longer instant , vents and scrubbers no longer use atmos signals and go back to processing.
  code/ATMOSPHERICS/components/unary/vent_scrubber.dm
  code/ZAS/Zone.dm
  code/__DEFINES/components.dm
  code/game/machinery/doors/firedoor.dm
Labels: Testing required

#7512 update getflaticon
  code/__HELPERS/icons.dm
  code/datums/datacore.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/holy_door.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/modules/admin/view_variables/view_variables.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/client/preference_setup/preview.dm
  code/modules/mob/new_player/preferences_setup.dm
  code/modules/modular_computers/file_system/reports/crew_record.dm
  icons/blanks/32x32.dmi
Labels: Testing required

#7504 Nerf flashes, again
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
Labels: Discussion needed

#7570 Changes the Takeshi to .25CS and edits the .25 caliber
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  code/modules/projectiles/projectile/bullettypes.dm
  maps/CEVEris/_CEV_Eris.dmm
Labels: Merge Conflict

#7567 New Rome now buffs the stats that NeoTheology members use.
  code/datums/setup_option/backgrounds/origin.dm
Labels: Discussion needed
