Repository discordia-space/CEV-Eris, pull requests merged in 2022-12, with the labels that each got.

#7621 Monkey resprite
  code/modules/organs/external/organ_icon.dm
  icons/effects/species.dmi
  icons/mob/human.dmi
  icons/mob/human_races/monkeys/r_monkey.dmi
Labels: Sprites, Testing required

#7866 Sets FPS/ticklag on /world to match config (40 FPS)
  code/world.dm
Labels: Merge only on Monday

#7613 Presenting: The FS .40 "Voodoo"
  cev_eris.dme
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/storage/holster.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/projectiles/guns/projectile/pistol/avasarala.dm
  code/modules/projectiles/guns/projectile/pistol/voodoo.dm
  icons/obj/crafts.dmi
  icons/obj/guns/projectile/voodoo.dmi
Labels: New features
