Repository discordia-space/CEV-Eris, pull requests merged in 2023-04, with the labels that each got.

#8083 Excelsior KS-23
  cev_eris.dme
  code/datums/autolathe/guns.dm
  code/game/objects/items/weapons/design_disks/excelsior.dm
  code/modules/projectiles/guns/projectile/shotgun/ks23.dm
  icons/obj/guns/projectile/ks23.dmi
Labels: New features

#8085 Slime changes + electrocution changes
  code/modules/admin/player_panel.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/species/species_attack.dm
  code/modules/mob/living/carbon/human/species/station/slime.dm
  code/modules/mob/living/carbon/slime/life.dm
  code/modules/mob/living/carbon/slime/powers.dm
  code/modules/reagents/reagents/toxins.dm
  icons/mob/human_races/r_slime.dmi
  tgui/public/tgui.bundle.js
Labels: Testing required

#8093 Fixes infinite materials through recycling
  code/game/machinery/smelter.dm
Labels: Testing required, Merge only on Monday

#8126 Custom Seed Packet Labels
  code/modules/hydroponics/seed_packets.dm
Labels: Question asked
