Repository discordia-space/CEV-Eris, pull requests merged in 2023-09, with the labels that each got.

#8267 convert stats UI to TGUI
  cev_eris.dme
  code/datums/mob_stats_menu.dm
  code/modules/asset_cache/asset_list.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/asset_cache/assets/sanity.dm
  code/modules/asset_cache/assets/sheetmaterials.dm
  code/modules/asset_cache/assets/stats.dm
  code/modules/mob/mob.dm
  tgui/packages/tgui/interfaces/Stats.tsx
  tgui/packages/tgui/styles/interfaces/Stats.scss
  tgui/packages/tgui/styles/main.scss
  tgui/public/tgui.bundle.css
  tgui/public/tgui.bundle.js
Labels: Merge Conflict

#8292 Shift pulsar sat to avoid overlapping on overmap
  maps/pulsar/pulsar.dmm
Labels: YES ABSOLUTELY MERGE

#8288 Mining rework (continued)
  code/modules/mining/drilling/cave_generator.dm
  code/modules/mining/drilling/cave_mineral.dm
  code/modules/mining/drilling/deep_drill.dm
  code/modules/mining/drilling/scanner.dm
  code/modules/mob/living/carbon/superior_animal/golem/types/plasma.dm
Labels: YES ABSOLUTELY MERGE

#8306 SM now comes in crates
  code/controllers/subsystems/trade.dm
Labels: Question asked

#8323 Caverns are now radshielded
  code/game/area/Space Station 13 areas.dm
  code/game/gamemodes/events/weather/rad_storm.dm
Labels: YES ABSOLUTELY MERGE

#8320 New TGUI for ore box
  code/modules/mining/satchel_ore_boxdm.dm
  tgui/packages/tgui/interfaces/OreBox.tsx
  tgui/public/tgui.bundle.js
Labels: YES ABSOLUTELY MERGE
