Repository discordia-space/CEV-Eris, pull requests merged in 2023-06, with the labels that each got.

#8203 Reworks Bowls to hold both solids and liquids
  cev_eris.dme
  code/datums/autolathe/containers.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/modules/food/drywet.dm
  code/modules/goonchat/browserOutput.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/glass/beaker.dm
Labels: Question asked

#8142 Metabolism changes
  code/__DEFINES/chemistry.dm
  code/modules/organs/blood.dm
  code/modules/reagents/reagents.dm
Labels: Testing required

#8213 SSchunks round 3.
  cev_eris.dme
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/maths.dm
  code/__DEFINES/subsystems.dm
  code/__HELPERS/game.dm
  code/__HELPERS/global_lists.dm
  code/controllers/subsystems/chunks.dm
  code/controllers/subsystems/garbage.dm
  code/controllers/subsystems/jamming.dm
  code/datums/components/jamming.dm
  code/datums/datum_click_handlers.dm
  code/datums/movement/atom_movable.dm
  code/datums/movement/mob.dm
  code/datums/movement/movement.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/cryo.dm
  code/game/machinery/cryopod.dm
  code/game/machinery/gym.dm
  code/game/machinery/hologram.dm
  code/game/machinery/jammers.dm
  code/game/objects/items/_inventory.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/devices/spy_bug.dm
  code/game/objects/items/devices/taperecorder.dm
  code/game/objects/items/weapons/implant/implants/explosive.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/objs.dm
  code/game/world.dm
  code/modules/assembly/holder.dm
  code/modules/assembly/voice.dm
  code/modules/client/preferences_spawnpoints.dm
  code/modules/core_implant/core_implant.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/slime/life.dm
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
  code/modules/mob/living/carbon/superior_animal/life.dm
  code/modules/mob/living/carbon/superior_animal/roach/life.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/mob/observer/ghost/login.dm
  code/modules/mob/observer/ghost/logout.dm
  code/modules/modular_computers/computers/modular_computer/core.dm
Labels: Merge Conflict, Question asked
