Repository discordia-space/CEV-Eris, pull requests merged in 2023-05, with the labels that each got.

#8097 You can't spawn infinite mice by spamming "respawn as mouse" as a ghost.
  code/modules/mob/observer/ghost/ghost.dm
Labels: Question asked

#8104 Removes all ties of style from combat , makes style buff insight gain from all sources.
  code/game/objects/items.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/nt_melee.dm
  code/game/objects/items/weapons/tools/knives.dm
  code/game/objects/objs.dm
  code/modules/clothing/clothing.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/resist.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/mob_grab_specials.dm
  code/modules/onestar/os_turret.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile/battle_rifle/boltgun.dm
  code/modules/projectiles/guns/projectile/battle_rifle/levergun.dm
  code/modules/projectiles/guns/projectile/pistol/handmade.dm
  code/modules/projectiles/guns/projectile/revolver/revolver.dm
  code/modules/projectiles/guns/projectile/shotgun/doublebarrel.dm
  code/modules/projectiles/guns/projectile/shotgun/handmade.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullettypes.dm
  code/modules/projectiles/projectile/force.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/sanity/sanity_mob.dm
  code/modules/tables/flipping.dm
  code/modules/tables/interactions.dm
Labels: Discussion needed

#8086 [Ready]Codebase optimizations part 3: SSchunks strikes back
  cev_eris.dme
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/maths.dm
  code/__DEFINES/subsystems.dm
  code/__HELPERS/game.dm
  code/__HELPERS/global_lists.dm
  code/controllers/subsystems/chunks.dm
  code/controllers/subsystems/garbage.dm
  code/controllers/subsystems/jamming.dm
  code/datums/components/jamming.dm
  code/datums/datum_click_handlers.dm
  code/datums/movement/atom_movable.dm
  code/datums/movement/mob.dm
  code/datums/movement/movement.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/cryo.dm
  code/game/machinery/cryopod.dm
  code/game/machinery/gym.dm
  code/game/machinery/hologram.dm
  code/game/machinery/jammers.dm
  code/game/objects/items/_inventory.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/devices/spy_bug.dm
  code/game/objects/items/devices/taperecorder.dm
  code/game/objects/items/weapons/implant/implants/explosive.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/objs.dm
  code/game/world.dm
  code/modules/assembly/holder.dm
  code/modules/assembly/voice.dm
  code/modules/client/preferences_spawnpoints.dm
  code/modules/core_implant/core_implant.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/slime/life.dm
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
  code/modules/mob/living/carbon/superior_animal/life.dm
  code/modules/mob/living/carbon/superior_animal/roach/life.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/mob/observer/ghost/login.dm
  code/modules/mob/observer/ghost/logout.dm
  code/modules/modular_computers/computers/modular_computer/core.dm
Labels: Testing required, DO NOT MERGE
