Repository discordia-space/CEV-Eris, pull requests merged in 2023-01, with the labels that each got.

#7961 Warrant projector resprite
  icons/obj/device.dmi
Labels: Sprites

#7962 Cruciform Forge resprite
  icons/obj/neotheology_machinery.dmi
Labels: Sprites

#7963 Eye of The Protector resprite.
  icons/obj/eotp.dmi
Labels: Sprites

#7943 Mining QOL (Selective alloying, TGUI'ed smelter)
  .gitignore
  code/__DEFINES/materials.dm
  code/modules/mining/alloys.dm
  code/modules/mining/machine_processing.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mining/ore.dm
  code/modules/mining/ore_datum.dm
  tgui/packages/tgui/interfaces/Processor.js
  tgui/public/tgui.bundle.js
Labels: Merge only on Monday

#7931 Full auto cleanup and burst fire fix
  code/__DEFINES/items.dm
  code/__DEFINES/weapons.dm
  code/datums/datum_click_handlers.dm
  code/modules/projectiles/gun.dm
Labels: Testing required, Merge only on Monday

#7966 Neotheology uniform resprite (+ minor OneStar uniform fix)
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
Labels: Sprites

#7979 Calculation error fixes
  code/modules/mob/living/living_defense.dm
  code/modules/projectiles/projectile.dm
Labels: Merge only on Monday

#7845 Window grab interaction rework
  code/game/objects/structures/window.dm
  code/modules/mob/mob_grab.dm
Labels: Discussion needed

#7997 IH Badge Additions and Changes [FUCKING Finally Works]
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/accessories/badges.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
Labels: Merge only on Monday

#7996 Nerfs hornet and mandella
  code/modules/projectiles/guns/projectile/pistol/mandella.dm
  code/modules/projectiles/guns/projectile/revolver/hornet.dm
Labels: Merge only on Monday

#7995 Fixes penetration calculations
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/plasma.dm
Labels: Merge only on Monday

#7992 readds old guild tech jacket
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/modules/clothing/suits/jobs.dm
Labels: Merge only on Monday

#7989 Add sound notification when someone logins with a cookie from a banned account
  code/modules/goonchat/browserOutput.dm
Labels: Testing required
