Repository discordia-space/CEV-Eris, pull requests merged in 2023-03, with the labels that each got.

#7981 Re-do of #7757 (Exosuit Balance)
  code/__DEFINES/misc.dm
  code/datums/uplink/highly visible and dangerous weapons.dm
  code/modules/mechs/components/_components.dm
  code/modules/mechs/components/armour.dm
  code/modules/mechs/components/arms.dm
  code/modules/mechs/components/body.dm
  code/modules/mechs/components/head.dm
  code/modules/mechs/components/legs.dm
  code/modules/mechs/components/software.dm
  code/modules/mechs/equipment/medical.dm
  code/modules/mechs/interface/screen_objects.dm
  code/modules/mechs/mech.dm
  code/modules/mechs/mech_damage.dm
  code/modules/mechs/mech_damage_immunity.dm
  code/modules/mechs/mech_interaction.dm
  code/modules/mechs/premade/combat.dm
  code/modules/mechs/premade/heavy.dm
  code/modules/mechs/premade/light.dm
  code/modules/mechs/premade/misc.dm
  code/modules/mechs/premade/powerloader.dm
  icons/mechs/mech_parts.dmi
Labels: Testing required, Merge only on Monday

#8024 Increases upload limit to 10 MB
  code/modules/client/client_procs.dm
Labels: Testing required

#8020 Add matter to instruments
  code/modules/synthesized_instruments/real_instruments/Guitar/guitar.dm
  code/modules/synthesized_instruments/real_instruments/Piano/piano.dm
  code/modules/synthesized_instruments/real_instruments/Synthesizer/synthesizer.dm
  code/modules/synthesized_instruments/real_instruments/Trumpet/trumpet.dm
  code/modules/synthesized_instruments/real_instruments/Violin/violin.dm
Labels: New features

#8018 Block people from leaving/entering shuttles through their ceiling
  code/modules/multiz/movement.dm
Labels: Fix
