Repository discordia-space/CEV-Eris, pull requests merged in 2024-09, with the labels that each got.

#8523 Fix window interactions
  code/game/objects/structures/low_wall.dm
  code/game/turfs/simulated/wall_attacks.dm
  code/game/turfs/simulated/wall_icon.dm
  code/game/turfs/simulated/walls.dm
  code/modules/mob/mob_grab.dm
Labels: Bug fixes

#8522 Better 515 compatibility
  code/_onclick/hud/HUD_element/HUD_element.dm
  code/_onclick/hud/HUD_element/external_procs.dm
  code/datums/mutable_appearance.dm
  code/modules/mob/inventory/slots.dm
Labels: Bug fixes

#8521 Remove satchel gathering limit of 15.
  code/game/objects/items/weapons/storage/storage.dm
Labels: QOL

#8514 Shield generator and Long range scanner refactor + Bioreactor fixes
  cev_eris.dme
  code/__DEFINES/lrange_scanner.dm
  code/__HELPERS/turfs.dm
  code/controllers/subsystems/staverbs.dm
  code/datums/wires/lrange_scanner.dm
  code/datums/wires/shield_generator.dm
  code/game/gamemodes/events/space_weather.dm
  code/game/gamemodes/scores.dm
  code/game/machinery/machinery.dm
  code/game/machinery/multistructure.dm
  code/game/objects/items/weapons/circuitboards/machinery/lrange_scanner.dm
  code/game/objects/items/weapons/circuitboards/machinery/shieldgen.dm
  code/modules/biomatter_manipulation/bioreactor/bioreactor.dm
  code/modules/biomatter_manipulation/bioreactor/platform.dm
  code/modules/biomatter_manipulation/solidifier.dm
  code/modules/core_implant/cruciform/rituals/machinery.dm
  code/modules/long_range_scanner/hull.dm
  code/modules/long_range_scanner/long_range_scanner.dm
  code/modules/modular_computers/file_system/programs/engineering/shield_control.dm
  code/modules/nano/modules/nano_module.dm
  code/modules/overmap/ships/ship.dm
  code/modules/power/shipside_machinery.dm
  code/modules/reagents/reagents/food-Drinks.dm
  code/modules/research/designs/circuits.dm
  code/modules/research/nodes/bluespace.dm
  code/modules/shield_generators/hull.dm
  code/modules/shield_generators/shield.dm
  code/modules/shield_generators/shield_generator.dm
  maps/CEVEris/_CEV_Eris.dmm
Labels: Fix, Balance

#8139 Disposable gun: ... Svalinn!
  code/datums/autolathe/guns.dm
  code/game/objects/items/weapons/design_disks/NeoTheology.dm
  code/modules/projectiles/guns/energy/nt_svalinn.dm
Labels: Guns, Balance
