Repository discordia-space/CEV-Eris, pull requests merged in 2025-01, with the labels that each got.

#8539 Optimize action buttons
  code/game/objects/items/_inventory.dm
  code/game/objects/items/devices/lighting/toggleable/flashlight.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/login.dm
Labels: Optimization

#8541 Fixes overdose runtime
  code/modules/reagents/reagents/medicine.dm
Labels: Fix

#8542 Fix Liberty HUD not working & unify functions
  code/_onclick/hud/screen_objects/base_screen_objects.dm
Labels: Fix

#8545 Fixes shutter buttons breaking for rounds that play near 24:00 GMT and reach 00:00
  code/game/machinery/doors/blast_door.dm
Labels: Fix

#8543 Superglue is printable with an advanced tools disk + superglue buffs
  code/datums/autolathe/tools.dm
  code/game/objects/items/weapons/design_disks/technomancers.dm
  code/game/objects/items/weapons/tools/tape.dm
Labels: Balance

#8544 Brings back chunk hearing. Fixes MMIs/Radios not picking up and hearing messages
  code/__HELPERS/game.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/objs.dm
  code/modules/mob/living/say.dm
Labels: Fix
